(function () {
  'use strict';
  const H=(i,t,d)=>`<div class="lab-head"><div><h3>Q${i} · ${t}</h3><p>${d}</p></div><button type="button" class="lab-close" data-lab-close>닫기</button></div>`;
  const S=(l,m)=>`<div class="lab-status" aria-live="polite"><b data-status-label>${l}</b><span data-status-message>${m}</span></div>`;
  const T=(h,s,v)=>{const n=h.querySelector(s);if(n)n.textContent=v};

  CSLabs.register(71,{html:()=>`<section class="cs-lab locality-choice-lab">${H(71,'O(n) 안의 memory journey','projectile을 연속 배열과 흩어진 node로 배치하고 순회 경로를 비교하세요.')}
    <div class="locality-memory" data-locality-memory></div><svg class="locality-path" viewBox="0 0 640 80" role="img" aria-label="projectile 순회가 메모리 cache line을 따라 이동하는 경로" data-locality-path></svg>
    <div class="io-numbers"><span>cache lines <b data-locality-lines></b></span><span>pointer waits <b data-pointer-waits></b></span><span>erase 이동 <b data-erase-cost></b></span></div>
    <div class="lab-controls"><label>저장 구조 <select data-projectile-layout><option value="vector">dense vector</option><option value="list">linked list</option></select></label><label>projectile 수 <input type="range" min="8" max="64" step="8" value="32" data-projectiles><output data-projectile-out>32</output></label><button type="button" class="primary" data-traverse>한 frame 순회</button></div>${S('연속 cache line 순회','삭제 이동보다 매 frame 읽기 빈도가 훨씬 큽니다.')}</section>`,
    bind:h=>{const d=()=>{const n=+h.querySelector('[data-projectiles]').value,list=h.querySelector('[data-projectile-layout]').value==='list';const order=list?Array.from({length:n},(_,i)=>(i*13)%n):Array.from({length:n},(_,i)=>i);h.querySelector('[data-locality-memory]').innerHTML=Array.from({length:n},(_,i)=>`<i>${i}</i>`).join('');h.querySelector('[data-locality-path]').innerHTML=`<polyline points="${order.slice(0,20).map((x,i)=>`${10+x*(620/Math.max(1,n-1))},${12+(i%2)*48}`).join(' ')}"/><title>${list?'흩어진 node pointer 순회':'연속 cache line 순회'}</title>`;T(h,'[data-locality-lines]',list?n:Math.ceil(n/8));T(h,'[data-pointer-waits]',list?n-1:0);T(h,'[data-erase-cost]',list?'O(1) after lookup':'swap 1 element');T(h,'[data-projectile-out]',n);T(h,'[data-status-label]',list?'pointer chasing O(n)':'prefetch 가능한 O(n)');T(h,'[data-status-message]',list?'다음 주소를 현재 node에서 읽어야 해 miss latency가 직렬로 이어집니다.':'한 cache line이 여러 projectile을 데려오고 다음 line 주소도 예측됩니다.')};h.querySelectorAll('input,select').forEach(n=>n.oninput=d);h.querySelector('[data-traverse]').onclick=d;d()}});

  CSLabs.register(72,{html:()=>`<section class="cs-lab hash-lab">${H(72,'평균 O(1)의 bucket 가정','ID 분포와 capacity를 바꿔 probe chain과 rehash 순간을 확인하세요.')}
    <div class="hash-buckets" data-hash-buckets></div><div class="hash-spike" data-hash-spike></div>
    <div class="lab-controls"><label>key 분포 <select data-hash-mode><option value="uniform">seeded uniform</option><option value="sequential">낮은 bit 반복</option><option value="attack">의도적 collision</option></select></label><label>element <input type="range" min="8" max="64" value="28" data-hash-count><output data-hash-out>28</output></label><label>bucket <select data-bucket-count><option>16</option><option selected>32</option><option>64</option></select></label></div>${S('균일 bucket 분포','평균 probe가 짧고 capacity 안에 있습니다.')}</section>`,
    bind:h=>{const d=()=>{const n=+h.querySelector('[data-hash-count]').value,b=+h.querySelector('[data-bucket-count]').value,mode=h.querySelector('[data-hash-mode]').value,loads=Array(b).fill(0);for(let i=0;i<n;i++){const x=mode==='attack'?3:mode==='sequential'?(i*8)%b:(i*17+Math.floor(i/3)*7)%b;loads[x]++}const max=Math.max(...loads),rehash=n/b>.8;h.querySelector('[data-hash-buckets]').innerHTML=loads.map((x,i)=>`<span><b>${i}</b><i style="height:${x*16}px">${x||''}</i></span>`).join('');h.querySelector('[data-hash-spike]').innerHTML=rehash?'<i>CAPACITY CROSSED</i><b>all elements migrate this tick</b>':'capacity headroom';T(h,'[data-hash-out]',n);T(h,'[data-status-label]',rehash?'rehash frame spike':max>6?`최장 chain ${max}`:'평균 짧은 probe');T(h,'[data-status-message]',max>6?'기대 O(1)을 지탱하던 균일 분포 가정이 깨졌습니다.':rehash?'amortized 비용이 이번 한 frame에 집중됩니다.':'load factor와 collision histogram이 통제됩니다.')};h.querySelectorAll('input,select').forEach(n=>n.oninput=d);d()}});

  CSLabs.register(73,{html:()=>`<section class="cs-lab heap-open-lab">${H(73,'stale entry를 버리는 heap','같은 node의 더 짧은 거리를 push하고 pop 시점 검증을 진행하세요.')}
    <div class="binary-heap" data-binary-heap></div><div class="best-distance">BEST B = <b data-best-b>9</b></div>
    <div class="lab-controls"><button type="button" data-push-shorter>B 거리 4 발견 · push</button><button type="button" data-pop-heap>heap pop</button><label><input type="checkbox" data-check-stale> pop 거리==best 검증</label><button type="button" class="primary" data-heap-reset>초기화</button></div>${S('B:9가 heap에 있음','더 짧은 B:4를 찾아도 기존 항목을 선형 탐색하지 않습니다.')}</section>`,
    bind:h=>{let heap=[['A',3],['C',6],['B',9]],best=9;const draw=()=>{heap.sort((a,b)=>a[1]-b[1]);h.querySelector('[data-binary-heap]').innerHTML=heap.map((x,i)=>`<span class="${x[0]==='B'&&x[1]!==best?'stale':''}" style="--heap-index:${i}">${x[0]}:${x[1]}</span>`).join('');T(h,'[data-best-b]',best)};h.querySelector('[data-push-shorter]').onclick=()=>{best=4;heap.push(['B',4]);draw()};h.querySelector('[data-pop-heap]').onclick=()=>{if(!heap.length)return;const x=heap.shift(),stale=x[0]==='B'&&x[1]!==best,check=h.querySelector('[data-check-stale]').checked;T(h,'[data-status-label]',stale&&check?`B:${x[1]} stale · 폐기`:`${x[0]}:${x[1]} 확정`);T(h,'[data-status-message]',stale&&check?'현재 best와 다른 duplicate는 graph 상태를 바꾸지 않습니다.':stale?'오래된 거리로 node를 확정해 최단 경로 invariant를 깨뜨렸습니다.':'heap top의 유효한 최소 거리를 꺼냈습니다.');draw()};h.querySelector('[data-heap-reset]').onclick=()=>{heap=[['A',3],['C',6],['B',9]];best=9;draw()};draw()}});

  CSLabs.register(74,{html:()=>`<section class="cs-lab spatial-grid-lab">${H(74,'cell 해상도의 두 비용','cell 크기와 boss 크기를 바꿔 candidate pair와 중복 등록을 함께 보세요.')}
    <div class="spatial-grid" data-spatial-grid><div class="spatial-boss" data-spatial-boss>BOSS</div><div class="spatial-bullets" data-spatial-bullets></div></div>
    <div class="io-numbers"><span>boss 등록 cell <b data-boss-cells></b></span><span>candidate pairs <b data-candidates></b></span><span>index update <b data-grid-updates></b></span></div>
    <div class="lab-controls"><label>cell 크기 <input type="range" min="20" max="100" step="10" value="50" data-cell-size><output data-cell-out>50</output></label><label>boss 크기 <input type="range" min="30" max="180" step="10" value="100" data-boss-size><output data-boss-out>100</output></label></div>${S('중간 해상도 grid','후보 수와 큰 object 중복 등록이 균형을 이룹니다.')}</section>`,
    bind:h=>{const d=()=>{const cell=+h.querySelector('[data-cell-size]').value,boss=+h.querySelector('[data-boss-size]').value,cols=Math.ceil(400/cell),rows=Math.ceil(220/cell),touch=Math.min(cols*rows,Math.ceil(boss/cell+1)**2),candidates=Math.round(cell*cell/120+touch*3);h.querySelector('[data-spatial-grid]').style.backgroundSize=`${100/cols}% ${100/rows}%`;h.querySelector('[data-spatial-boss]').style.width=`${boss/4}%`;h.querySelector('[data-spatial-boss]').style.height=`${boss/2.2}%`;h.querySelector('[data-spatial-bullets]').innerHTML=Array.from({length:18},(_,i)=>`<i style="left:${(i*37)%93}%;top:${(i*53)%88}%"></i>`).join('');T(h,'[data-boss-cells]',touch);T(h,'[data-candidates]',candidates);T(h,'[data-grid-updates]',`${touch}/move`);T(h,'[data-cell-out]',cell);T(h,'[data-boss-out]',boss);T(h,'[data-status-label]',touch>12?'큰 object 중복 폭증':candidates>80?'cell 안 후보 폭증':'두 비용 균형');T(h,'[data-status-message]',touch>12?'boss는 별도 giant 구조로 분리할 근거가 생겼습니다.':candidates>80?'cell이 너무 커 narrow phase로 넘길 거짓 후보가 많습니다.':'분포에 맞는 해상도입니다.')};h.querySelectorAll('input').forEach(n=>n.oninput=d);d()}});

  CSLabs.register(75,{html:()=>`<section class="cs-lab path-cost-lab">${H(75,'칸 수가 아니라 이동 cost','늪의 weight와 heuristic 배율을 바꿔 탐색 범위와 경로 선택을 비교하세요.')}
    <div class="weighted-map" data-weighted-map></div><div class="path-score"><span>선택 경로 cost <b data-path-cost></b></span><span>확장 node <b data-expanded></b></span></div>
    <div class="lab-controls"><label>알고리즘 <select data-path-algo><option value="bfs">BFS</option><option value="dijkstra">Dijkstra</option><option value="astar">A*</option></select></label><label>늪 cost <input type="range" min="1" max="9" value="5" data-swamp-cost><output data-swamp-out>5</output></label><label>heuristic 배율 <input type="range" min="0" max="3" step=".5" value="1" data-heuristic-weight><output data-heuristic-out>1</output></label></div>${S('BFS는 가장 적은 edge 선택','가운데 늪의 weight는 queue 순서에 반영되지 않습니다.')}</section>`,
    bind:h=>{const d=()=>{const algo=h.querySelector('[data-path-algo]').value,swamp=+h.querySelector('[data-swamp-cost]').value,w=+h.querySelector('[data-heuristic-weight]').value;const direct=4+swamp*3,detour=11,useDirect=algo==='bfs'||(algo==='astar'&&w>1.5)||direct<=detour,cost=useDirect?direct:detour,expanded=algo==='bfs'?20:algo==='dijkstra'?26:Math.max(7,18-Math.round(w*5));h.querySelector('[data-weighted-map]').innerHTML=Array.from({length:35},(_,i)=>{const swampCell=[16,17,18].includes(i),path=useDirect?[14,15,16,17,18,19,20].includes(i):[14,7,8,9,10,11,12,13,20].includes(i);return `<i class="${swampCell?'swamp':''} ${path?'path':''}">${i===14?'S':i===20?'G':swampCell?'~':''}</i>`}).join('');T(h,'[data-path-cost]',cost);T(h,'[data-expanded]',expanded);T(h,'[data-swamp-out]',swamp);T(h,'[data-heuristic-out]',w);T(h,'[data-status-label]',algo==='bfs'?'weight 무시':algo==='astar'&&w>1?'과대 heuristic · 근사 경로':algo==='astar'?'admissible A*':'Dijkstra 기준 해');T(h,'[data-status-message]',algo==='astar'&&w>1?'탐색은 줄지만 아직 싼 detour를 보기 전에 직선 경로를 선택할 수 있습니다.':useDirect?'현재 weight에서는 직선 경로의 총 cost가 선택됩니다.':'edge 수는 많아도 총 이동 cost가 낮은 우회로를 선택합니다.')};h.querySelectorAll('select,input').forEach(n=>n.oninput=d);d()}});

  CSLabs.register(76,{html:()=>`<section class="cs-lab dsu-lab">${H(76,'합칠 수 있지만 쉽게 나눌 수 없는 숲','섬 사이 다리를 추가·파괴해 DSU parent와 실제 연결을 비교하세요.')}
    <div class="island-chain" data-island-chain></div><div class="dsu-parents" data-dsu-parents></div>
    <div class="lab-controls"><button type="button" data-bridge="01">A-B 다리 추가</button><button type="button" data-bridge="12">B-C 다리 추가</button><button type="button" data-destroy-bridge>A-B 파괴</button><label><input type="checkbox" data-rebuild-component> 파괴 component BFS 재구축</label><button type="button" class="primary" data-query-connect>A와 C 연결?</button></div>${S('세 섬이 분리됨','union은 parent 숲을 합치는 방향으로만 진행합니다.')}</section>`,
    bind:h=>{let edges=new Set(),parent=[0,1,2];const root=x=>{while(parent[x]!==x)x=parent[x];return x},unite=(a,b)=>{a=root(a);b=root(b);if(a!==b)parent[b]=a},draw=()=>{h.querySelector('[data-island-chain]').innerHTML=['A','B','C'].map((x,i)=>`<span>${x}</span>${i<2?`<i class="${edges.has(`${i}${i+1}`)?'on':''}">BRIDGE</i>`:''}`).join('');h.querySelector('[data-dsu-parents]').innerHTML=parent.map((p,i)=>`<i>${'ABC'[i]}→${'ABC'[p]}</i>`).join('')};h.querySelectorAll('[data-bridge]').forEach(b=>b.onclick=()=>{const e=b.dataset.bridge;edges.add(e);unite(+e[0],+e[1]);draw()});h.querySelector('[data-destroy-bridge]').onclick=()=>{edges.delete('01');if(h.querySelector('[data-rebuild-component]').checked){parent=[0,1,2];edges.forEach(e=>unite(+e[0],+e[1]))}draw()};h.querySelector('[data-query-connect]').onclick=()=>{const dsu=root(0)===root(2),actual=edges.has('01')&&edges.has('12');T(h,'[data-status-label]',dsu===actual?actual?'연결됨':'분리됨':'DSU가 stale 연결 반환');T(h,'[data-status-message]',dsu!==actual?'삭제는 압축된 parent 숲을 자동으로 되돌리지 않습니다. dirty component 재탐색이 필요합니다.':'parent 결과와 실제 bridge graph가 일치합니다.')};draw()}});

  CSLabs.register(77,{html:()=>`<section class="cs-lab ring-lab">${H(77,'같은 index의 다른 세대','write/read sequence를 한 칸씩 움직여 empty와 full이 같은 물리 index를 갖는 순간을 보세요.')}
    <div class="ring-wheel" data-ring-wheel></div><div class="ring-sequences"><span>readSeq <b data-read-seq>0</b></span><span>writeSeq <b data-write-seq>0</b></span><span>size <b data-ring-size>0</b></span></div>
    <div class="lab-controls"><button type="button" data-ring-write>write 1</button><button type="button" data-ring-read>read 1</button><label><input type="checkbox" data-store-sequence> monotonic sequence 보존</label><button type="button" class="primary" data-ring-reset>초기화</button></div>${S('index 0 == index 0 · empty','물리 index만 보면 한 바퀴 뒤 full과 구분할 정보가 없습니다.')}</section>`,
    bind:h=>{let r=0,w=0;const d=()=>{const size=w-r;h.querySelector('[data-ring-wheel]').innerHTML=Array.from({length:8},(_,i)=>`<i class="${i===r%8?'read':''} ${i===w%8?'write':''} ${i>=r%8&&i<(r+Math.min(size,8))%8?'filled':''}">${i}</i>`).join('');T(h,'[data-read-seq]',h.querySelector('[data-store-sequence]').checked?r:r%8);T(h,'[data-write-seq]',h.querySelector('[data-store-sequence]').checked?w:w%8);T(h,'[data-ring-size]',h.querySelector('[data-store-sequence]').checked?size:(r%8===w%8?'?':(w-r+8)%8));const ambiguous=!h.querySelector('[data-store-sequence]').checked&&r%8===w%8&&w>r;T(h,'[data-status-label]',ambiguous?'index 같음 · empty/full 모호':size===8?'full · 한 바퀴 차이':size===0?'empty':'진행량 보존');T(h,'[data-status-message]',ambiguous?'나머지만 저장해 write가 read보다 한 바퀴 앞섰다는 세대 정보를 잃었습니다.':'slot 접근 때만 mask하고 sequence 차이로 size를 계산합니다.')};h.querySelector('[data-ring-write]').onclick=()=>{if(w-r<8)w++;d()};h.querySelector('[data-ring-read]').onclick=()=>{if(w>r)r++;d()};h.querySelector('[data-store-sequence]').oninput=d;h.querySelector('[data-ring-reset]').onclick=()=>{r=0;w=0;d()};d()}});

  CSLabs.register(78,{html:()=>`<section class="cs-lab sort-order-lab">${H(78,'동등 key 안의 규칙 만들기','동일 priority 이벤트를 섞고 stable 또는 total-key 정렬 결과를 비교하세요.')}
    <div class="event-deck" data-event-deck></div><div class="sort-arrow">SORT ↓</div><div class="sorted-events" data-sorted-events></div>
    <div class="lab-controls"><button type="button" data-shuffle-events>입력 순서 섞기</button><label>정렬 계약 <select data-sort-contract><option value="unstable">priority만 · unstable</option><option value="stable">priority만 · stable</option><option value="total">priority + eventSeq</option></select></label><button type="button" class="primary" data-sort-events>정렬</button></div>${S('동일 priority 이벤트 5개','priority comparator는 이들 사이의 순서를 정의하지 않습니다.')}</section>`,
    bind:h=>{let events=[['A',2,5],['B',1,3],['C',2,1],['D',1,4],['E',2,2]];const render=(s,a)=>h.querySelector(s).innerHTML=a.map(x=>`<i>P${x[1]}·${x[0]}<small>#${x[2]}</small></i>`).join('');render('[data-event-deck]',events);h.querySelector('[data-shuffle-events]').onclick=()=>{events=[...events].sort(()=>Math.random()-.5);render('[data-event-deck]',events)};h.querySelector('[data-sort-events]').onclick=()=>{const mode=h.querySelector('[data-sort-contract]').value;let out=[...events];if(mode==='unstable')out.sort((a,b)=>a[1]-b[1]||((a[2]*7)%5)-((b[2]*7)%5));else if(mode==='stable')out.sort((a,b)=>a[1]-b[1]);else out.sort((a,b)=>a[1]-b[1]||a[2]-b[2]);render('[data-sorted-events]',out);T(h,'[data-status-label]',mode==='total'?'입력과 플랫폼에 독립적인 total order':mode==='stable'?'현재 입력 순서 보존':'동등 항목 순서 미정');T(h,'[data-status-message]',mode==='total'?'eventSeq tie-break가 모든 쌍의 앞뒤를 정의합니다.':mode==='stable'?'입력 순서 자체가 결정적이라는 전제가 추가로 필요합니다.':'priority만 같으면 어떤 순서도 comparator 계약을 만족합니다.')};render('[data-sorted-events]',events)}});

  CSLabs.register(79,{html:()=>`<section class="cs-lab cache-admission-lab">${H(79,'one-pass scan으로부터 hot set 지키기','UI texture를 반복 사용한 뒤 cutscene stream을 흘려 eviction 정책을 확인하세요.')}
    <div class="cache-slots" data-cache-slots></div><div class="cache-trace" data-cache-trace></div>
    <div class="lab-controls"><button type="button" data-warm-hot>UI A·B·C 반복 사용</button><label>정책 <select data-cache-policy><option value="lru">plain LRU</option><option value="segmented">probation / protected</option></select></label><button type="button" data-scan-cache>cutscene X1~X8 scan</button><button type="button" class="primary" data-reuse-hot>UI A 다시 요청</button></div>${S('cache 6칸 비어 있음','hot set을 만든 다음 capacity보다 큰 scan을 통과시키세요.')}</section>`,
    bind:h=>{let slots=[],hot=new Set(),trace=[];const draw=()=>{h.querySelector('[data-cache-slots]').innerHTML=Array.from({length:6},(_,i)=>`<i class="${hot.has(slots[i])?'hot':''}">${slots[i]||'·'}</i>`).join('');h.querySelector('[data-cache-trace]').innerHTML=trace.slice(-12).map(x=>`<span>${x}</span>`).join('')},touch=(x,protect=false)=>{slots=slots.filter(y=>y!==x);slots.push(x);if(protect)hot.add(x);while(slots.length>6){let victim=0;if(h.querySelector('[data-cache-policy]').value==='segmented'){victim=slots.findIndex(y=>!hot.has(y));if(victim<0)victim=0}const [gone]=slots.splice(victim,1);hot.delete(gone)}trace.push(x)};h.querySelector('[data-warm-hot]').onclick=()=>{for(let n=0;n<3;n++)['A','B','C'].forEach(x=>touch(x,true));draw()};h.querySelector('[data-scan-cache]').onclick=()=>{for(let i=1;i<=8;i++)touch(`X${i}`);draw()};h.querySelector('[data-reuse-hot]').onclick=()=>{const hit=slots.includes('A');touch('A',true);T(h,'[data-status-label]',hit?'UI A cache hit':'UI A critical miss');T(h,'[data-status-message]',hit?'일회성 stream은 probation에서 서로 교체되어 protected hot set을 지켰습니다.':'plain LRU가 최근이라는 이유만으로 다시 쓰지 않을 scan block을 받아 hot set을 밀어냈습니다.');draw()};draw()}});

  CSLabs.register(80,{html:()=>`<section class="cs-lab topk-lab">${H(80,'필요한 K개만 순서 만들기','전체 N과 필요한 K를 바꿔 세 알고리즘의 비교 범위를 확인하세요.')}
    <div class="topk-race"><div data-sort-work><b>FULL SORT</b><i></i><span></span></div><div data-heap-work><b>K HEAP</b><i></i><span></span></div><div data-select-work><b>SELECT + SORT K</b><i></i><span></span></div></div>
    <div class="topk-output" data-topk-output></div>
    <div class="lab-controls"><label>N entities <input type="range" min="1000" max="100000" step="1000" value="50000" data-topk-n><output data-topk-n-out>50,000</output></label><label>K nearest <input type="range" min="5" max="200" step="5" value="20" data-topk-k><output data-topk-k-out>20</output></label><button type="button" class="primary" data-run-topk>작업량 비교</button></div>${S('N=50,000 중 K=20만 필요','버릴 49,980개 사이의 순서는 출력에 포함되지 않습니다.')}</section>`,
    bind:h=>{const d=()=>{const n=+h.querySelector('[data-topk-n]').value,k=+h.querySelector('[data-topk-k]').value,works=[n*Math.log2(n),n*Math.log2(k),n+k*Math.log2(k)],max=works[0];[['sort',0],['heap',1],['select',2]].forEach(([x,i])=>{h.querySelector(`[data-${x}-work] i`).style.width=`${works[i]/max*100}%`;T(h,`[data-${x}-work] span`,`${Math.round(works[i]/1000).toLocaleString()}k comparisons`)});h.querySelector('[data-topk-output]').innerHTML=Array.from({length:Math.min(k,20)},(_,i)=>`<i>#${i+1}</i>`).join('');T(h,'[data-topk-n-out]',n.toLocaleString());T(h,'[data-topk-k-out]',k);const best=works.indexOf(Math.min(...works));T(h,'[data-status-label]',['full sort','K-size max heap','quickselect + K sort'][best]+' 작업량 최소');T(h,'[data-status-message]','필요한 출력이 K개 집합인지 K개 내부 정렬까지인지에 따라 계산하지 않아도 될 순서를 제거합니다.')};h.querySelectorAll('input').forEach(n=>n.oninput=d);h.querySelector('[data-run-topk]').onclick=d;d()}});
})();
