(function () {
  'use strict';
  const H=(i,t,d)=>`<div class="lab-head"><div><h3>Q${i} · ${t}</h3><p>${d}</p></div><button type="button" class="lab-close" data-lab-close>닫기</button></div>`;
  const S=(l,m)=>`<div class="lab-status" aria-live="polite"><b data-status-label>${l}</b><span data-status-message>${m}</span></div>`;
  const T=(h,s,v)=>{const n=h.querySelector(s);if(n)n.textContent=v};

  CSLabs.register(81,{html:()=>`<section class="cs-lab percentile-lab">${H(81,'평균 아래 숨은 hitch','hitch 빈도와 크기를 바꿔 평균·p99·maximum이 무엇을 드러내는지 보세요.')}
    <div class="frame-histogram" data-frame-histogram></div><div class="frame-threshold">16.6ms budget</div>
    <div class="frame-stats"><span>평균 <b data-frame-avg></b></span><span>p99 <b data-frame-p99></b></span><span>maximum <b data-frame-max></b></span></div>
    <div class="lab-controls"><label>hitch frame / 100 <input type="range" min="0" max="10" value="1" data-hitch-count><output data-hitch-count-out>1</output></label><label>hitch 크기 <input type="range" min="20" max="120" step="10" value="100" data-hitch-size><output data-hitch-size-out>100ms</output></label></div>${S('평균은 9ms 근처','한 번의 100ms frame이 플레이 감각을 끊지만 평균에는 거의 희석됩니다.')}</section>`,
    bind:h=>{const d=()=>{const c=+h.querySelector('[data-hitch-count]').value,size=+h.querySelector('[data-hitch-size]').value,frames=Array.from({length:100},(_,i)=>i>=100-c?size:8+(i%5)*.25).sort((a,b)=>a-b),avg=frames.reduce((a,b)=>a+b,0)/100,p99=frames[98];h.querySelector('[data-frame-histogram]').innerHTML=frames.map((x,i)=>`<i class="${x>16.6?'miss':''}" style="height:${Math.min(100,x/120*100)}%" aria-label="frame ${i+1}: ${x}ms"></i>`).join('');T(h,'[data-frame-avg]',`${avg.toFixed(1)}ms`);T(h,'[data-frame-p99]',`${p99.toFixed(1)}ms`);T(h,'[data-frame-max]',`${frames[99].toFixed(1)}ms`);T(h,'[data-hitch-count-out]',c);T(h,'[data-hitch-size-out]',`${size}ms`);T(h,'[data-status-label]',c?`${c}% deadline miss`:'deadline miss 없음');T(h,'[data-status-message]',c?'평균 FPS 대신 tail frame의 빈도와 크기가 실제 끊김을 설명합니다.':'모든 표본이 frame budget 아래입니다.')};h.querySelectorAll('input').forEach(n=>n.oninput=d);d()}});

  CSLabs.register(82,{html:()=>`<section class="cs-lab observer-lab">${H(82,'측정 도구가 더한 시간','marker 밀도와 sampling 주기를 바꿔 원래 work 위의 관측 비용을 분리하세요.')}
    <div class="observer-frame"><span class="true-work">GAME WORK 8ms</span><span class="marker-work" data-marker-work></span><i class="sample-pins" data-sample-pins></i></div>
    <div class="frame-stats"><span>관측 frame <b data-observed-frame></b></span><span>도구 overhead <b data-profiler-overhead></b></span><span>누락 가능성 <b data-miss-risk></b></span></div>
    <div class="lab-controls"><label>instrumented scope <input type="range" min="0" max="10000" step="500" value="1000" data-marker-count><output data-marker-out>1,000</output></label><label>sampling interval <input type="range" min="1" max="20" value="10" data-sample-rate><output data-sample-out>10ms</output></label><label><input type="checkbox" data-thread-local-trace> thread-local trace buffer</label></div>${S('관측 frame은 원래보다 김','clock read와 trace 기록도 프로그램이 실행한 일입니다.')}</section>`,
    bind:h=>{const d=()=>{const m=+h.querySelector('[data-marker-count]').value,s=+h.querySelector('[data-sample-rate]').value,local=h.querySelector('[data-thread-local-trace]').checked,over=m*(local?.00012:.00035)+.05/s;h.querySelector('[data-marker-work]').style.width=`${Math.min(60,over/8*100)}%`;h.querySelector('[data-sample-pins]').style.backgroundSize=`${Math.max(4,s*3)}px 100%`;T(h,'[data-observed-frame]',`${(8+over).toFixed(2)}ms`);T(h,'[data-profiler-overhead]',`${(over/8*100).toFixed(1)}%`);T(h,'[data-miss-risk]',s>12?'짧은 event 높음':s>5?'중간':'낮음');T(h,'[data-marker-out]',m.toLocaleString());T(h,'[data-sample-out]',`${s}ms`);T(h,'[data-status-label]',over>2?'관측이 병목을 재배치':'측정 overhead 제한');T(h,'[data-status-message]',over>2?'작은 scope보다 marker·buffer contention 비용이 커져 원래 hot path를 바꿨습니다.':'sampling으로 후보를 찾고 필요한 범위만 trace합니다.')};h.querySelectorAll('input').forEach(n=>n.oninput=d);d()}});

  CSLabs.register(83,{html:()=>`<section class="cs-lab cpu-gpu-lab">${H(83,'Present 안의 GPU 대기','CPU와 GPU workload를 바꿔 Present scope가 늘어나는 선행 원인을 확인하세요.')}
    <div class="dual-timeline"><div><b>CPU</b><span class="cpu-submit">SUBMIT</span><span class="cpu-present" data-present-block>PRESENT</span></div><div><b>GPU</b><span class="gpu-work" data-gpu-work>RENDER</span><span class="gpu-done">FENCE</span></div></div>
    <div class="frame-stats"><span>CPU work <b data-cpu-time></b></span><span>GPU work <b data-gpu-time></b></span><span>Present wait <b data-present-time></b></span></div>
    <div class="lab-controls"><label>CPU submit <input type="range" min="2" max="14" value="5" data-cpu-work><output data-cpu-out>5ms</output></label><label>GPU render <input type="range" min="4" max="24" value="16" data-gpu-ms><output data-gpu-out>16ms</output></label><label>frames in flight <select data-flight-frames><option value="1">1</option><option value="2">2</option><option value="3">3</option></select></label></div>${S('CPU가 GPU fence를 기다림','긴 CPU scope는 기다림이 관측된 장소일 뿐입니다.')}</section>`,
    bind:h=>{const d=()=>{const cpu=+h.querySelector('[data-cpu-work]').value,gpu=+h.querySelector('[data-gpu-ms]').value,f=+h.querySelector('[data-flight-frames]').value,wait=Math.max(0,gpu/f-cpu);h.querySelector('[data-present-block]').style.flex=`${Math.max(1,wait)}`;h.querySelector('[data-gpu-work]').style.flex=gpu;T(h,'[data-cpu-time]',`${cpu}ms`);T(h,'[data-gpu-time]',`${gpu}ms`);T(h,'[data-present-time]',`${wait.toFixed(1)}ms`);T(h,'[data-cpu-out]',`${cpu}ms`);T(h,'[data-gpu-out]',`${gpu}ms`);T(h,'[data-status-label]',wait>0?'Present에서 GPU backlog 대기':'CPU critical path');T(h,'[data-status-message]',wait>0?'GPU workload를 줄이는 통제 실험에서 이 CPU wait도 함께 줄어야 인과가 확인됩니다.':'CPU 제출이 GPU보다 늦어 GPU가 입력을 기다립니다.')};h.querySelectorAll('input,select').forEach(n=>n.oninput=d);d()}});

  CSLabs.register(84,{html:()=>`<section class="cs-lab causality-lab">${H(84,'함께 커진 subsystem 하나씩 개입하기','NPC 수를 고정하고 AI·animation·render를 no-op해 frame 변화의 원인을 분리하세요.')}
    <div class="causal-web"><div class="cause-node">NPC COUNT</div><div class="effect-nodes"><span data-cost-ai>AI</span><span data-cost-anim>ANIM</span><span data-cost-render>RENDER</span><span data-cost-physics>PHYSICS</span></div><div class="frame-node" data-causal-frame>FRAME 20ms</div></div>
    <div class="lab-controls"><label>NPC <input type="range" min="20" max="200" step="20" value="120" data-npc-count><output data-npc-out>120</output></label><label><input type="checkbox" data-disable-ai> AI no-op</label><label><input type="checkbox" data-disable-anim> animation freeze</label><label><input type="checkbox" data-disable-render> render cull</label></div>${S('네 subsystem이 함께 증가','상관계수만으로 어느 가지가 원인인지 분리할 수 없습니다.')}</section>`,
    bind:h=>{const d=()=>{const n=+h.querySelector('[data-npc-count]').value,off={ai:h.querySelector('[data-disable-ai]').checked,anim:h.querySelector('[data-disable-anim]').checked,render:h.querySelector('[data-disable-render]').checked},cost={ai:n*.035,anim:n*.025,render:n*.05,physics:n*.015};Object.keys(off).forEach(k=>h.querySelector(`[data-cost-${k}]`)?.classList.toggle('disabled',off[k]));const total=3+Object.entries(cost).reduce((s,[k,v])=>s+(off[k]?0:v),0);T(h,'[data-causal-frame]',`FRAME ${total.toFixed(1)}ms`);T(h,'[data-npc-out]',n);const removed=Object.keys(off).filter(k=>off[k]);T(h,'[data-status-label]',removed.length?`${removed.join('+')} 개입 효과 측정`:'상관만 관측');T(h,'[data-status-message]',removed.length?'동일 replay에서 한 변수만 바꿔 frame 차이를 그 subsystem의 effect 후보로 좁힙니다.':'NPC는 여러 비용의 공통 원인이므로 AI counter 상관만으로 인과를 말할 수 없습니다.')};h.querySelectorAll('input').forEach(n=>n.oninput=d);d()}});

  CSLabs.register(85,{html:()=>`<section class="cs-lab heisenbug-lab">${H(85,'로그가 닫아 버린 race window','두 thread 사건 사이 logging 지연을 넣어 실패 interleaving이 어떻게 사라지는지 보세요.')}
    <div class="race-window"><div><b>THREAD A</b><i data-race-a1>read owner=none</i><i data-race-log-a>LOG</i><i data-race-a2>write owner=A</i></div><div><b>THREAD B</b><i data-race-b1>read owner=none</i><i data-race-log-b>LOG</i><i data-race-b2>write owner=B</i></div></div>
    <div class="race-result" data-race-result></div><div class="lab-controls"><label>관측 방식 <select data-race-observer><option value="none">없음</option><option value="printf">동기 printf + logger lock</option><option value="flight">thread-local binary ring</option></select></label><button type="button" class="primary" data-run-race>10,000회 schedule fuzz</button></div>${S('관측 없는 재현율 18%','read와 write 사이에 다른 thread가 들어오는 window가 열려 있습니다.')}</section>`,
    bind:h=>{h.querySelector('[data-run-race]').onclick=()=>{const mode=h.querySelector('[data-race-observer]').value,rate=mode==='printf'?.2:mode==='flight'?16:18;h.querySelectorAll('[data-race-log-a],[data-race-log-b]').forEach(n=>n.className=mode);T(h,'[data-race-result]',`double-owner 재현 ${rate}% · observer ${mode}`);T(h,'[data-status-label]',mode==='printf'?'로그를 넣으면 거의 사라짐':mode==='flight'?'schedule 보존에 가까운 breadcrumb':'원래 race 관측');T(h,'[data-status-message]',mode==='printf'?'logger mutex와 I/O delay가 두 thread를 직렬화해 실패 window를 닫았습니다.':mode==='flight'?'formatting 없이 thread-local ring에 작은 sequence만 남겨 교란을 제한합니다.':'증거가 없어 실패 순서를 재구성하기 어렵습니다.')}}});

  CSLabs.register(86,{html:()=>`<section class="cs-lab memory-diagnosis-lab">${H(86,'live·cache·RSS를 따로 보기','scene load/unload cycle을 반복해 증가하는 층과 plateau하는 층을 확인하세요.')}
    <div class="memory-layers-chart" data-memory-layers-chart></div><div class="memory-legend"><span>LIVE</span><span>CACHE</span><span>ALLOCATOR FREE</span></div>
    <div class="lab-controls"><button type="button" data-load-scene-memory>scene load</button><button type="button" data-unload-scene-memory>scene unload</button><label><input type="checkbox" data-inject-leak> owner ref leak 12MB/cycle</label><button type="button" class="primary" data-trim-heap>allocator trim</button></div>${S('baseline 180MB RSS','같은 checkpoint에서 각 층의 변화 방향을 비교하세요.')}</section>`,
    bind:h=>{let live=80,cache=60,free=40,loaded=false,cycles=0;const d=()=>{h.querySelector('[data-memory-layers-chart]').innerHTML=[['LIVE',live,'live'],['CACHE',cache,'cache'],['FREE',free,'free']].map(x=>`<div><b>${x[0]} ${x[1]}MB</b><i class="${x[2]}" style="height:${x[1]}px"></i></div>`).join('');const leak=h.querySelector('[data-inject-leak]').checked;T(h,'[data-status-label]',leak&&cycles>1?'cycle마다 live 증가 · leak 후보':!loaded&&cycles?'RSS plateau · retained high-water':'scene 상태 관측');T(h,'[data-status-message]',leak&&cycles>1?'unload 뒤에도 owner chain이 cycle별 allocation을 계속 도달 가능하게 유지합니다.':'unload로 live는 줄었지만 cache budget과 allocator free span이 OS에 즉시 반환되지 않습니다.')};h.querySelector('[data-load-scene-memory]').onclick=()=>{if(!loaded){loaded=true;live+=100;cache=Math.min(120,cache+35);free=Math.max(0,free-20)}d()};h.querySelector('[data-unload-scene-memory]').onclick=()=>{if(loaded){loaded=false;cycles++;live=80+(h.querySelector('[data-inject-leak]').checked?cycles*12:0);free=Math.min(110,free+80)}d()};h.querySelector('[data-trim-heap]').onclick=()=>{free=10;d()};d()}});

  CSLabs.register(87,{html:()=>`<section class="cs-lab crash-origin-lab">${H(87,'손상과 crash 사이의 거리','memory overwrite를 만든 뒤 여러 frame을 진행해 탐지 방식별 origin 거리를 보세요.')}
    <div class="corruption-timeline" data-corruption-timeline></div><div class="crash-stack" data-crash-stack>현재 stack: AllocParticle → HeapPop → AV</div>
    <div class="lab-controls"><button type="button" data-corrupt-memory>frame 100 · buffer overwrite</button><label>탐지 장치 <select data-detection-mode><option value="late">없음 · 나중 crash</option><option value="canary">canary check / frame</option><option value="guard">guard page</option></select></label><button type="button" data-advance-crash>100 frame 진행</button><button type="button" class="primary" data-inspect-breadcrumb>breadcrumb 조사</button></div>${S('아직 invariant 정상','crash top frame과 최초 손상 시점을 분리해 보세요.')}</section>`,
    bind:h=>{let corrupted=false,advanced=false,origin=100;const draw=()=>{const mode=h.querySelector('[data-detection-mode]').value,detect=!corrupted?null:mode==='guard'?100:mode==='canary'?101:advanced?200:null;h.querySelector('[data-corruption-timeline]').innerHTML=Array.from({length:11},(_,i)=>{const f=100+i*10;return `<i class="${f===origin&&corrupted?'origin':''} ${detect&&f>=detect?'detected':''}">${f}</i>`}).join('');if(detect){T(h,'[data-status-label]',`frame ${detect}에서 탐지`);T(h,'[data-status-message]',mode==='late'?'현재 crash stack은 100 frame 전 overwrite의 결과입니다.':`탐지 거리를 ${detect-origin} frame으로 줄여 origin 근처 stack과 owner를 보존합니다.`)}};h.querySelector('[data-corrupt-memory]').onclick=()=>{corrupted=true;draw()};h.querySelector('[data-advance-crash]').onclick=()=>{advanced=true;draw()};h.querySelector('[data-detection-mode]').oninput=draw;h.querySelector('[data-inspect-breadcrumb]').onclick=()=>{T(h,'[data-crash-stack]','last writer: PhysicsContact #882 · object gen 41 · frame 100')};draw()}});

  CSLabs.register(88,{html:()=>`<section class="cs-lab bisect-lab">${H(88,'noisy oracle로 하는 binary search','실제 회귀 크기와 측정 noise를 바꿔 good/bad 판정 신뢰도를 확인하세요.')}
    <div class="commit-bisect" data-commit-bisect></div><div class="sample-cloud" data-sample-cloud></div>
    <div class="lab-controls"><label>실제 회귀 <input type="range" min="0" max="4" step=".5" value="1" data-regression-size><output data-regression-out>1ms</output></label><label>환경 noise ± <input type="range" min="0" max="4" step=".5" value="2" data-benchmark-noise><output data-noise-out>2ms</output></label><label>반복 표본 <input type="range" min="1" max="15" value="1" data-bisect-samples><output data-sample-out>1</output></label><button type="button" class="primary" data-run-bisect>중간 commit 판정</button></div>${S('단일 측정 oracle','noise가 effect보다 크면 good/bad가 실행마다 뒤집힙니다.')}</section>`,
    bind:h=>{const d=()=>{const effect=+h.querySelector('[data-regression-size]').value,noise=+h.querySelector('[data-benchmark-noise]').value,n=+h.querySelector('[data-bisect-samples]').value,uncertainty=noise/Math.sqrt(n),conf=effect===0?0:Math.min(99,Math.round(50+49*(effect/(effect+uncertainty))));h.querySelector('[data-commit-bisect]').innerHTML=Array.from({length:15},(_,i)=>`<i class="${i<7?'good':i>7?'bad':'probe'}">${i+1}</i>`).join('');h.querySelector('[data-sample-cloud]').innerHTML=Array.from({length:n},(_,i)=>`<i style="left:${50+Math.sin(i*13)*noise*10}%"></i>`).join('');T(h,'[data-regression-out]',`${effect}ms`);T(h,'[data-noise-out]',`${noise}ms`);T(h,'[data-sample-out]',n);T(h,'[data-status-label]',conf<75?'판정 불확실 · 범위를 버리면 위험':`bad 판정 신뢰도 ${conf}%`);T(h,'[data-status-message]',conf<75?'warmup·deterministic replay·paired 반복으로 oracle부터 안정화해야 합니다.':'effect가 반복 표본의 불확실성보다 충분히 커졌습니다.')};h.querySelectorAll('input').forEach(n=>n.oninput=d);h.querySelector('[data-run-bisect]').onclick=d;d()}});

  CSLabs.register(89,{html:()=>`<section class="cs-lab benchmark-lab">${H(89,'micro 조건에서 제품 frame까지','cache·input·result 소비 조건을 바꿔 격리 개선이 실제 critical path에 남는지 보세요.')}
    <div class="benchmark-world"><div><b>MICRO LOOP</b><span data-micro-bar></span></div><div><b>REAL FRAME</b><span data-real-bar></span></div></div>
    <div class="frame-stats"><span>micro 개선 <b data-micro-gain></b></span><span>frame 개선 <b data-frame-gain></b></span><span>함수 frame 비중 <b data-frame-share></b></span></div>
    <div class="lab-controls"><label><input type="checkbox" data-cold-cache> 실제 cold/mixed cache</label><label><input type="checkbox" data-random-input> 실제 입력 분포</label><label><input type="checkbox" data-consume-result> 결과 observable</label><label>함수 frame 비중 <input type="range" min="1" max="60" value="10" data-function-share><output data-share-out>10%</output></label></div>${S('warm micro에서 20% 개선','함수가 frame의 10%라면 최대 제품 효과는 훨씬 작습니다.')}</section>`,
    bind:h=>{const d=()=>{const share=+h.querySelector('[data-function-share]').value,cold=h.querySelector('[data-cold-cache]').checked,random=h.querySelector('[data-random-input]').checked,consume=h.querySelector('[data-consume-result]').checked;let micro=20+(consume?0:35)-(cold?10:0)-(random?6:0);micro=Math.max(0,micro);const frame=micro*share/100;h.querySelector('[data-micro-bar]').style.width=`${Math.min(100,micro*1.5)}%`;h.querySelector('[data-real-bar]').style.width=`${Math.min(100,frame*5)}%`;T(h,'[data-micro-gain]',`${micro.toFixed(1)}%`);T(h,'[data-frame-gain]',`${frame.toFixed(1)}%`);T(h,'[data-frame-share]',`${share}%`);T(h,'[data-share-out]',`${share}%`);T(h,'[data-status-label]',!consume?'dead-code elimination 위험':cold&&random?'대표 조건에 가까움':'조건 일부 불일치');T(h,'[data-status-message]',!consume?'결과가 관측되지 않아 compiler가 실제 제품에서 필요한 일을 제거할 수 있습니다.':'micro 개선에는 frame 비중이라는 Amdahl 상한이 적용됩니다.')};h.querySelectorAll('input').forEach(n=>n.oninput=d);d()}});

  CSLabs.register(90,{html:()=>`<section class="cs-lab critical-path-lab">${H(90,'총 work와 frame span 분리','병렬 job과 dependency edge를 바꿔 합계가 아니라 present까지의 가장 긴 경로를 찾으세요.')}
    <div class="job-dag" data-job-dag></div><div class="frame-stats"><span>총 CPU work <b data-total-work></b></span><span>critical path <b data-critical-span></b></span><span>parallel slack <b data-parallel-slack></b></span></div>
    <div class="lab-controls"><label>AI job <input type="range" min="1" max="12" value="8" data-job-ai><output data-ai-out>8ms</output></label><label>physics job <input type="range" min="1" max="12" value="6" data-job-physics><output data-physics-out>6ms</output></label><label>cosmetic job <input type="range" min="1" max="12" value="10" data-job-cosmetic><output data-cosmetic-out>10ms</output></label><label><input type="checkbox" data-cosmetic-fence> cosmetic도 present fence에 연결</label></div>${S('AI→physics→render가 critical path','동시에 실행된 cosmetic work는 늦지 않으면 frame end를 움직이지 않습니다.')}</section>`,
    bind:h=>{const d=()=>{const ai=+h.querySelector('[data-job-ai]').value,p=+h.querySelector('[data-job-physics]').value,c=+h.querySelector('[data-job-cosmetic]').value,f=h.querySelector('[data-cosmetic-fence]').checked,main=ai+p+3,span=Math.max(main,f?c+3:0),work=ai+p+c+3;h.querySelector('[data-job-dag]').innerHTML=`<div class="dag-main"><i style="flex:${ai}">AI ${ai}</i><i style="flex:${p}">PHYS ${p}</i><i style="flex:3">RENDER 3</i></div><div class="dag-side"><i style="flex:${c}">COSMETIC ${c}</i>${f?'<i style="flex:3">FENCE</i>':'<span>slack</span>'}</div>`;T(h,'[data-total-work]',`${work}ms`);T(h,'[data-critical-span]',`${span}ms`);T(h,'[data-parallel-slack]',`${Math.max(0,span-c)}ms`);T(h,'[data-ai-out]',`${ai}ms`);T(h,'[data-physics-out]',`${p}ms`);T(h,'[data-cosmetic-out]',`${c}ms`);T(h,'[data-status-label]',f&&c+3>main?'cosmetic chain이 새 critical path':'AI→physics→render span');T(h,'[data-status-message]',f?'dependency edge를 추가하자 이전에는 숨었던 work가 frame 완료를 막습니다.':'critical path 밖의 job을 줄여도 present 시점은 그대로일 수 있습니다.')};h.querySelectorAll('input').forEach(n=>n.oninput=d);d()}});
})();
