(function () {
  'use strict';
  const H=(i,t,d)=>`<div class="lab-head"><div><h3>Q${i} · ${t}</h3><p>${d}</p></div><button type="button" class="lab-close" data-lab-close>닫기</button></div>`;
  const S=(l,m)=>`<div class="lab-status" aria-live="polite"><b data-status-label>${l}</b><span data-status-message>${m}</span></div>`;
  const T=(h,s,v)=>{const n=h.querySelector(s);if(n)n.textContent=v};

  CSLabs.register(91,{html:()=>`<section class="cs-lab packet-overflow-lab">${H(91,'검사 전 산술이 먼저 안전한가','count×elementSize를 좁은 정수와 checked 연산으로 계산해 allocation 차이를 보세요.')}
    <div class="packet-equation"><span>count <b data-packet-count-value></b></span><i>×</i><span>16 bytes</span><i>=</i><span data-packet-product></span></div>
    <div class="packet-buffer" data-packet-buffer><i></i><b data-buffer-label></b></div>
    <div class="lab-controls"><label>count <input type="range" min="1" max="300000000" step="10000000" value="280000000" data-packet-count><output data-packet-count-out></output></label><label>산술 <select data-length-arithmetic><option value="u32">uint32 wrap 후 비교</option><option value="checked">count ≤ remaining / size</option></select></label><button type="button" class="primary" data-decode-packet>decode 시도</button></div>${S('count는 wire에서 옴','비교에 들어가기 전 곱셈 결과의 표현 가능성을 확인하세요.')}</section>`,
    bind:h=>{const d=()=>{const count=+h.querySelector('[data-packet-count]').value,mode=h.querySelector('[data-length-arithmetic]').value,exact=count*16,wrapped=exact>>>0,remaining=64*1024*1024,accepted=mode==='u32'?wrapped<=remaining:count<=Math.floor(remaining/16),allocated=mode==='u32'?wrapped:accepted?exact:0;T(h,'[data-packet-count-value]',count.toLocaleString());T(h,'[data-packet-count-out]',count.toLocaleString());T(h,'[data-packet-product]',mode==='u32'?`${wrapped.toLocaleString()} (u32)`:`${exact.toLocaleString()} checked`);h.querySelector('[data-packet-buffer] i').style.width=`${Math.min(100,allocated/remaining*100)}%`;T(h,'[data-buffer-label]',accepted?`ALLOC ${allocated.toLocaleString()} bytes`:'REJECT BEFORE ALLOC');T(h,'[data-status-label]',accepted&&exact>allocated?'작은 검사값으로 통과 · 큰 copy 위험':accepted?'범위 안 packet':'overflow/limit 거부');T(h,'[data-status-message]',accepted&&exact>allocated?`실제 ${exact.toLocaleString()} bytes 의미가 ${allocated.toLocaleString()}로 wrap했습니다.`:'remaining/elementSize와 count를 비교해 곱셈 전에 상한을 증명합니다.')};h.querySelectorAll('input,select').forEach(n=>n.oninput=d);h.querySelector('[data-decode-packet]').onclick=d;d()}});

  CSLabs.register(92,{html:()=>`<section class="cs-lab replay-window-lab">${H(92,'인증된 packet의 신선성 창','정상 packet을 복제·재정렬해 receive sequence window가 무엇을 기억하는지 보세요.')}
    <div class="sequence-window" data-sequence-window></div><div class="packet-inbox" data-packet-inbox></div>
    <div class="lab-controls"><button type="button" data-send-seq="104">SEQ 104 수신</button><button type="button" data-send-seq="106">SEQ 106 수신</button><button type="button" data-send-seq="105">SEQ 105 지연 수신</button><button type="button" data-replay-seq>SEQ 104 복제 재전송</button><label><input type="checkbox" data-replay-protection> sliding window 검사</label></div>${S('receive window 100~107','AEAD tag가 유효해도 이미 처리한 sequence인지 별도 상태가 필요합니다.')}</section>`,
    bind:h=>{const seen=new Set();let inbox=[];const draw=()=>{h.querySelector('[data-sequence-window]').innerHTML=Array.from({length:8},(_,i)=>{const n=100+i;return `<i class="${seen.has(n)?'seen':''}">${n}</i>`}).join('');h.querySelector('[data-packet-inbox]').innerHTML=inbox.slice(-5).map(x=>`<span class="${x.ok?'ok':'drop'}">${x.n} ${x.ok?'ACCEPT':'REPLAY DROP'}</span>`).join('')},receive=n=>{const protect=h.querySelector('[data-replay-protection]').checked,ok=!protect||!seen.has(n);if(ok)seen.add(n);inbox.push({n,ok});T(h,'[data-status-label]',ok?'authenticated + fresh packet':'tag는 유효하지만 duplicate');T(h,'[data-status-message]',ok?'sequence window에서 아직 처리하지 않은 번호입니다.':'암호문이 변조되지 않았다는 사실은 두 번째 적용을 허용한다는 뜻이 아닙니다.');draw()};h.querySelectorAll('[data-send-seq]').forEach(b=>b.onclick=()=>receive(+b.dataset.sendSeq));h.querySelector('[data-replay-seq]').onclick=()=>receive(104);h.querySelector('[data-replay-protection]').oninput=draw;draw()}});

  CSLabs.register(93,{html:()=>`<section class="cs-lab authority-lab">${H(93,'client는 결과가 아니라 의도를 보낸다','packet 내용을 결과 claim과 input command로 바꿔 server가 다시 계산하는 범위를 보세요.')}
    <div class="authority-boundary"><div class="client-side"><b>CLIENT</b><span data-client-claim></span></div><i>UNTRUSTED NETWORK →</i><div class="server-side"><b>SERVER</b><span data-server-validation></span></div></div>
    <div class="lab-controls"><label>packet 계약 <select data-command-contract><option value="result">DealDamage(9999)</option><option value="intent">Fire(slot=2, aim=41°)</option></select></label><label><input type="checkbox" data-server-recompute> position·cooldown·LOS·damage 재계산</label><button type="button" class="primary" data-apply-command>packet 적용</button></div>${S('client가 damage 결과 주장','TLS는 발신 session을 인증하지만 그 주장이 게임 규칙상 가능한지는 검증하지 않습니다.')}</section>`,
    bind:h=>{const d=()=>{const intent=h.querySelector('[data-command-contract]').value==='intent',verify=h.querySelector('[data-server-recompute]').checked;T(h,'[data-client-claim]',intent?'INPUT: fire slot 2 @ 41°':'RESULT: boss HP -9999');T(h,'[data-server-validation]',verify?'authoritative state → cooldown OK → LOS blocked → 0 damage':'packet value → inventory mutation');T(h,'[data-status-label]',verify&&intent?'허용 가능한 의도만 수락':verify?'결과를 버리고 재계산':'인증된 client claim을 신뢰');T(h,'[data-status-message]',verify?'서버가 자기 state와 규칙으로 side effect를 결정합니다.':'변조 client도 정상 protocol과 TLS를 사용해 불가능한 결과를 주장할 수 있습니다.')};h.querySelectorAll('select,input').forEach(n=>n.oninput=d);h.querySelector('[data-apply-command]').onclick=d;d()}});

  CSLabs.register(94,{html:()=>`<section class="cs-lab parser-budget-lab">${H(94,'valid 입력도 소비시킬 자원은 제한','압축률·nesting·object 수를 조절해 먼저 소진되는 parser budget을 확인하세요.')}
    <div class="budget-gauges"><div><b>EXPANDED BYTES</b><i data-byte-gauge></i><span data-byte-label></span></div><div><b>OBJECTS</b><i data-object-gauge></i><span data-object-label></span></div><div><b>DEPTH</b><i data-depth-gauge></i><span data-depth-label></span></div></div>
    <div class="lab-controls"><label>압축률 <input type="range" min="1" max="10000" step="100" value="100" data-compression-ratio><output data-ratio-out>100×</output></label><label>object 만 개 <input type="range" min="1" max="500" value="20" data-object-count><output data-object-out>20</output></label><label>nesting <input type="range" min="1" max="1000" value="20" data-parser-depth><output data-depth-out>20</output></label><label><input type="checkbox" data-parser-budgets> resource budget 강제</label></div>${S('2MB 입력 · 200MB 출력','형식이 정상이어도 허용 자원 범위를 넘어설 수 있습니다.')}</section>`,
    bind:h=>{const d=()=>{const ratio=+h.querySelector('[data-compression-ratio]').value,objects=+h.querySelector('[data-object-count]').value,depth=+h.querySelector('[data-parser-depth]').value,guard=h.querySelector('[data-parser-budgets]').checked,vals=[ratio/256,objects/100,depth/64],over=vals.findIndex(x=>x>1);[['byte',vals[0],`${(2*ratio/1024).toFixed(1)}GB`],['object',vals[1],`${objects}만`],['depth',vals[2],depth]].forEach(([k,v,label])=>{h.querySelector(`[data-${k}-gauge]`).style.height=`${Math.min(100,v*100)}%`;T(h,`[data-${k}-label]`,label)});T(h,'[data-ratio-out]',`${ratio}×`);T(h,'[data-object-out]',objects);T(h,'[data-depth-out]',depth);T(h,'[data-status-label]',guard&&over>=0?['expanded byte 상한','object quota','nesting depth'][over]+'에서 중단':over>=0?'문법은 valid · 자원 고갈':'budget 안');T(h,'[data-status-message]',guard&&over>=0?'allocation·recursion을 계속하기 전에 일정한 비용으로 실패합니다.':over>=0?'checksum과 schema 통과만으로 CPU·RAM·stack 안전은 보장되지 않습니다.':'현재 입력은 모든 처리 budget 안에 있습니다.')};h.querySelectorAll('input').forEach(n=>n.oninput=d);d()}});

  CSLabs.register(95,{html:()=>`<section class="cs-lab retry-lab">${H(95,'timeout 뒤 결과 불명과 retry 부하','응답 지연·retry 정책을 바꿔 같은 구매의 중복 적용과 요청 파동을 보세요.')}
    <div class="retry-timeline" data-retry-timeline></div><div class="purchase-ledger" data-purchase-ledger></div>
    <div class="lab-controls"><label>응답 지연 <input type="range" min="100" max="5000" step="100" value="2500" data-response-delay><output data-delay-out>2500ms</output></label><label>client timeout <input type="range" min="200" max="3000" step="100" value="1000" data-client-timeout><output data-timeout-out>1000ms</output></label><label><input type="checkbox" data-idempotency-key> command ID dedup</label><label><input type="checkbox" data-backoff> exponential backoff + jitter</label><button type="button" class="primary" data-run-retry>구매 실행</button></div>${S('응답이 timeout보다 늦음','첫 commit의 결과를 모른 채 client가 retry합니다.')}</section>`,
    bind:h=>{h.querySelector('[data-run-retry]').onclick=()=>{const delay=+h.querySelector('[data-response-delay]').value,to=+h.querySelector('[data-client-timeout]').value,dedup=h.querySelector('[data-idempotency-key]').checked,back=h.querySelector('[data-backoff]').checked,retries=Math.min(5,Math.floor(delay/to)),effects=delay>to?(dedup?1:1+retries):1;h.querySelector('[data-retry-timeline]').innerHTML=Array.from({length:1+retries},(_,i)=>`<i style="left:${Math.min(92,(back?(2**i-1)*10:i*18))}%">REQ ${i+1}</i>`).join('');h.querySelector('[data-purchase-ledger]').innerHTML=Array.from({length:effects},(_,i)=>`<span>item credit #${i+1}</span>`).join('');T(h,'[data-delay-out]',`${delay}ms`);T(h,'[data-timeout-out]',`${to}ms`);T(h,'[data-status-label]',effects>1?`${effects}회 중복 지급`:retries?'retry해도 효과 1회':'첫 요청 완료');T(h,'[data-status-message]',effects>1?'timeout은 실패가 아니라 결과 불명인데 새 구매로 다시 적용했습니다.':dedup?'같은 command ID의 이전 결과를 반환하고 side effect는 반복하지 않습니다.':'응답이 deadline 안에 왔습니다.')}}});

  CSLabs.register(96,{html:()=>`<section class="cs-lab overload-lab">${H(96,'끝낼 수 있는 요청만 admission','도착률과 처리 capacity를 바꿔 queue 지연·goodput·빠른 거부를 비교하세요.')}
    <div class="overload-pipe"><div class="arrival-flow" data-arrival-flow></div><div class="request-queue" data-request-queue></div><div class="server-capacity" data-server-capacity>SERVER</div></div>
    <div class="frame-stats"><span>queue wait <b data-queue-wait></b></span><span>goodput <b data-goodput></b></span><span>reject <b data-reject-rate></b></span></div>
    <div class="lab-controls"><label>도착 req/s <input type="range" min="50" max="500" step="10" value="300" data-arrival-rate><output data-arrival-out>300</output></label><label>처리 req/s <input type="range" min="50" max="300" step="10" value="150" data-service-rate><output data-service-out>150</output></label><label>admission <select data-admission-mode><option value="unbounded">모두 queue</option><option value="bounded">queue 100 + fast reject</option><option value="reserved">핵심 30% capacity 예약</option></select></label></div>${S('도착률이 capacity의 2배','지속 overload는 queue로 처리량을 만들 수 없습니다.')}</section>`,
    bind:h=>{const d=()=>{const a=+h.querySelector('[data-arrival-rate]').value,s=+h.querySelector('[data-service-rate]').value,mode=h.querySelector('[data-admission-mode]').value,over=Math.max(0,a-s),bounded=mode!=='unbounded',queue=bounded?Math.min(100,over):over*5,reject=bounded?Math.max(0,a-s-100):0,good=mode==='unbounded'&&queue>500?Math.round(s*.65):s;h.querySelector('[data-arrival-flow]').innerHTML=Array.from({length:Math.min(20,Math.ceil(a/25))},()=>'<i></i>').join('');h.querySelector('[data-request-queue]').innerHTML=Array.from({length:Math.min(30,Math.ceil(queue/20))},()=>'<i></i>').join('');T(h,'[data-queue-wait]',`${(queue/Math.max(1,s)).toFixed(1)}s`);T(h,'[data-goodput]',`${good}/s`);T(h,'[data-reject-rate]',`${reject}/s`);T(h,'[data-arrival-out]',a);T(h,'[data-service-out]',s);T(h,'[data-status-label]',mode==='unbounded'&&over?'queue·retry positive feedback':reject?'빠른 overload reject':'capacity 안');T(h,'[data-status-message]',mode==='unbounded'&&over?'기다림이 timeout을 넘고 retry가 더해져 실제 완료 처리량까지 감소합니다.':reject?'완료 불가능한 요청을 즉시 거부해 memory·핵심 goodput·회복 시간을 지킵니다.':'도착 요청을 deadline 안에 처리할 수 있습니다.')};h.querySelectorAll('input,select').forEach(n=>n.oninput=d);d()}});

  CSLabs.register(97,{html:()=>`<section class="cs-lab config-rollout-lab">${H(97,'설정 version을 transaction에 고정','fleet의 config를 단계적으로 갱신하고 match가 어느 version을 사용하는지 보세요.')}
    <div class="server-fleet" data-server-fleet></div><div class="match-route"><span>SERVER A</span><i>TRANSFER</i><span>SERVER D</span><b data-match-config></b></div>
    <div class="lab-controls"><label>V13 rollout <input type="range" min="0" max="8" value="2" data-rollout-count><output data-rollout-out>2/8</output></label><label><input type="checkbox" data-pin-config> match 시작 시 config ID pin</label><button type="button" data-start-match>V12에서 match 시작</button><button type="button" class="primary" data-transfer-match>V13 서버로 이동</button></div>${S('2/8 canary가 V13','진행 중 match의 일관성 범위를 정의해야 합니다.')}</section>`,
    bind:h=>{let match=false;const d=()=>{const count=+h.querySelector('[data-rollout-count]').value;h.querySelector('[data-server-fleet]').innerHTML=Array.from({length:8},(_,i)=>`<i class="${i<count?'new':''}">S${i+1}<small>V${i<count?13:12}</small></i>`).join('');T(h,'[data-rollout-out]',`${count}/8`)};h.querySelector('[data-rollout-count]').oninput=d;h.querySelector('[data-start-match]').onclick=()=>{match=true;T(h,'[data-match-config]','MATCH CONFIG V12')};h.querySelector('[data-transfer-match]').onclick=()=>{if(!match)return;const pin=h.querySelector('[data-pin-config]').checked;T(h,'[data-match-config]',`MATCH CONFIG ${pin?'V12 PINNED':'V12 → V13 MIXED'}`);T(h,'[data-status-label]',pin?'transaction config 일관':'보상 formula 혼합');T(h,'[data-status-message]',pin?'서버가 바뀌어도 match identity에 묶인 immutable V12를 사용합니다.':'전투 시작과 보상 지급이 서로 다른 config version을 사용했습니다.')};d()}});

  CSLabs.register(98,{html:()=>`<section class="cs-lab clocks-lab">${H(98,'달력 시각과 경과 시간 분리','wall clock을 앞뒤로 점프시켜 cooldown deadline 계산 차이를 확인하세요.')}
    <div class="dual-clocks"><div><b>WALL CLOCK</b><span data-wall-clock>12:00:00</span><i data-wall-hand></i></div><div><b>MONOTONIC</b><span data-mono-clock>100.0s</span><i data-mono-hand></i></div></div><div class="cooldown-bar"><i data-cooldown-fill></i><b data-cooldown-label></b></div>
    <div class="lab-controls"><button type="button" data-clock-tick>1초 진행</button><button type="button" data-clock-back>wall -30초</button><button type="button" data-clock-forward>wall +60초</button><label>cooldown clock <select data-cooldown-clock><option value="wall">wall time</option><option value="mono">monotonic</option></select></label></div>${S('10초 cooldown 시작','경과 시간은 현실 시각 조정 때문에 역행해서는 안 됩니다.')}</section>`,
    bind:h=>{let wall=0,mono=0;const d=()=>{const useMono=h.querySelector('[data-cooldown-clock]').value==='mono',elapsed=useMono?mono:wall,remain=10-elapsed;T(h,'[data-wall-clock]',`12:00:${String((wall+120)%60).padStart(2,'0')}`);T(h,'[data-mono-clock]',`${(100+mono).toFixed(1)}s`);h.querySelector('[data-wall-hand]').style.transform=`rotate(${wall*6}deg)`;h.querySelector('[data-mono-hand]').style.transform=`rotate(${mono*6}deg)`;h.querySelector('[data-cooldown-fill]').style.width=`${Math.max(0,Math.min(100,elapsed/10*100))}%`;T(h,'[data-cooldown-label]',remain<=0?'READY':`${remain}s remaining`);T(h,'[data-status-label]',!useMono&&wall<0?'cooldown이 뒤로 늘어남':!useMono&&wall>=10?'wall jump로 즉시 완료':useMono?'경과 시간 단조 증가':'wall clock 사용');T(h,'[data-status-message]',useMono?'달력 시각이 점프해도 같은 boot의 duration deadline은 역행하지 않습니다.':'사용자·NTP 시각 조정이 gameplay duration을 바꿉니다.')};h.querySelector('[data-clock-tick]').onclick=()=>{wall++;mono++;d()};h.querySelector('[data-clock-back]').onclick=()=>{wall-=30;d()};h.querySelector('[data-clock-forward]').onclick=()=>{wall+=60;d()};h.querySelector('[data-cooldown-clock]').oninput=d;d()}});

  CSLabs.register(99,{html:()=>`<section class="cs-lab rng-security-lab">${H(99,'재현 가능한 난수와 예측 불가능한 난수','gameplay seed를 공개하고 다음 출력 예측이 token에 미치는 영향을 보세요.')}
    <div class="rng-machines"><div><b>GAMEPLAY PRNG</b><span data-game-seed>seed 1337</span><i data-game-rng></i></div><div><b>OS CSPRNG</b><span>hidden entropy pool</span><i data-secure-rng></i></div></div><div class="token-prediction" data-token-prediction></div>
    <div class="lab-controls"><button type="button" data-next-rng>다음 출력</button><label>token source <select data-token-source><option value="game">gameplay PRNG</option><option value="secure">OS secure random</option></select></label><button type="button" class="primary" data-predict-token>관측 출력로 다음 token 예측</button></div>${S('gameplay seed는 replay에 기록','결정성은 simulation 장점이지만 security token에는 미래 예측 취약점입니다.')}</section>`,
    bind:h=>{let state=1337,last=0;const next=()=>{state=(state*1664525+1013904223)>>>0;return state};h.querySelector('[data-next-rng]').onclick=()=>{last=next();T(h,'[data-game-rng]',last);T(h,'[data-secure-rng]',Array.from({length:4},()=>Math.floor(Math.random()*256).toString(16).padStart(2,'0')).join(''))};h.querySelector('[data-predict-token]').onclick=()=>{const game=h.querySelector('[data-token-source]').value==='game';const predicted=(state*1664525+1013904223)>>>0;T(h,'[data-token-prediction]',game?`ATTACKER PREDICTS NEXT TOKEN: ${predicted}`:'NEXT TOKEN: unknowable from prior public output');T(h,'[data-status-label]',game?'token 미래 출력 노출':'보안 entropy 분리');T(h,'[data-status-message]',game?'replay seed와 PRNG state 전이를 알면 통계 품질과 무관하게 다음 token을 계산합니다.':'production entropy를 로그에 남기지 않고 OS CSPRNG가 예측 저항성을 제공합니다.')}}});

  CSLabs.register(100,{html:()=>`<section class="cs-lab invariant-lab">${H(100,'실패 지점마다 같은 불변식 지키기','보상 command를 한 단계씩 진행하고 원하는 지점에 crash·retry를 넣어 보세요.')}
    <div class="reward-transaction" data-reward-transaction></div><div class="invariant-board"><span>inventory credits <b data-credit-count>0</b></span><span>outbox events <b data-outbox-count>0</b></span><span>client notices <b data-notice-count>0</b></span></div>
    <div class="lab-controls"><button type="button" data-reward-next>다음 단계</button><button type="button" data-reward-crash>지금 process crash</button><button type="button" data-reward-retry>같은 command retry</button><label><input type="checkbox" data-transactional-outbox> idempotency + transactional outbox</label><button type="button" class="primary" data-reward-recover>복구 worker 실행</button></div>${S('CMD-77 수신 전','불변식: command ID당 credit≤1, 승인된 credit은 결국 notice로 수렴.')}</section>`,
    bind:h=>{const steps=['RECEIVE CMD-77','DEDUP CHECK','INVENTORY CREDIT','OUTBOX INSERT','COMMIT','PUBLISH','CLIENT NOTICE'];let step=-1,credits=0,outbox=0,notices=0,crashed=false;const draw=()=>{h.querySelector('[data-reward-transaction]').innerHTML=steps.map((x,i)=>`<i class="${i<step?'done':i===step?'now':''}">${x}</i>`).join('');T(h,'[data-credit-count]',credits);T(h,'[data-outbox-count]',outbox);T(h,'[data-notice-count]',notices);const violated=credits>1;T(h,'[data-status-label]',violated?'불변식 위반 · duplicate credit':credits===1&&notices===1?'효과와 관측 수렴':crashed?'중간 실패 상태':'command 진행 중');T(h,'[data-status-message]',violated?'endpoint mutex가 process 밖의 retry·재시작 경계를 보호하지 못했습니다.':credits===1&&notices===1?'at-least-once 전달이어도 idempotent effect와 dedup consumer로 한 번의 제품 효과를 만들었습니다.':'각 crash 지점에서 credit≤1과 eventual notice가 유지되는지 확인하세요.')};h.querySelector('[data-reward-next]').onclick=()=>{if(crashed||step>=6)return;step++;const safe=h.querySelector('[data-transactional-outbox]').checked;if(step===2)credits++;if(step===3)outbox++;if(step===6)notices++;if(safe&&step===4&&outbox===0)outbox=1;draw()};h.querySelector('[data-reward-crash]').onclick=()=>{crashed=true;draw()};h.querySelector('[data-reward-retry]').onclick=()=>{const safe=h.querySelector('[data-transactional-outbox]').checked;crashed=false;step=1;if(!safe&&credits>0)credits++;draw()};h.querySelector('[data-reward-recover]').onclick=()=>{crashed=false;if(credits>0&&outbox>0){step=6;notices=1}draw()};draw()}});
})();
