(function () {
  'use strict';
  window.CSInterviewData.questions.push(
    {
      id: 81, category: 'I',
      question: '평균 frame이 8ms인데 플레이어는 끊긴다고 한다. 평균이 숨긴 한 장면을 어떤 분포로 찾아낼까?',
      scenario: '999 frame은 8ms지만 asset finalize가 일어난 한 frame은 120ms다. 평균은 8.1ms로 거의 변하지 않는다.',
      concepts: ['percentile', 'histogram', 'tail latency', 'frame pacing'],
      labLabel: '같은 평균에 가까운 frame series에서 hitch와 percentile 직접 찾기',
      boundary: '처리량·평균 frame time과 사용자가 경험하는 연속 frame 간격·tail latency를 구분한다.',
      naive: '긴 capture의 평균 FPS가 목표를 넘으면 성능 문제가 없다고 결론낸다.',
      failure: '희귀한 긴 frame이 평균에 희석되고 FPS 역수 평균은 frame-time 평균과도 다르게 왜곡될 수 있다.',
      reasoning: 'frame-time histogram과 p95/p99/p99.9, budget 초과 연속 길이를 보고 hitch frame을 event trace로 연결한다.',
      build: 'CPU submit, GPU present, streaming marker를 같은 frame ID로 기록하고 rolling percentile과 hitch threshold를 운영 지표로 둔다.',
      verify: '실제 플레이 trace에서 percentile, maximum, consecutive miss와 영상 frame pacing을 대조한다.',
      trade: '높은 percentile은 더 많은 표본과 메모리가 필요해 streaming quantile sketch를 사용할 수 있다.',
      core: '실시간 품질은 평균 작업량보다 deadline을 놓친 frame의 빈도와 크기로 설명해야 한다.'
    },
    {
      id: 82, category: 'I',
      question: '모든 함수에 timestamp를 넣자 병목 함수가 바뀌었다. 측정이 프로그램을 바꾸는 비용을 어떻게 통제할까?',
      scenario: 'instrumentation call, clock read, trace buffer contention이 작은 함수보다 비싸고 code layout·cache behavior까지 바꾼다.',
      concepts: ['observer effect', 'instrumentation', 'sampling profiler', 'measurement overhead'],
      labLabel: 'marker 밀도와 sampling 주기를 바꿔 원래 frame과 관측된 frame 비교하기',
      boundary: '측정하려는 비용과 측정 도구가 추가한 비용·timing perturbation을 분리한다.',
      naive: 'marker가 많을수록 더 정확하므로 모든 scope를 항상 기록한다.',
      failure: 'hot 작은 scope에서 수백만 clock read가 실행되고 shared trace buffer가 새로운 contention hotspot이 된다.',
      reasoning: '먼저 저오버헤드 sampling으로 hotspot을 찾고 제한된 범위에 instrumentation을 확대하며 baseline overhead를 계측한다.',
      build: 'thread-local buffer, sampling rate, category mask, compile-time disable을 두고 drop count와 profiler overhead를 함께 보고한다.',
      verify: 'profiling off/on 여러 강도의 wall time·hardware counter를 비교하고 결론이 안정적인지 본다.',
      trade: 'sampling은 짧고 드문 event와 인과 순서를 놓칠 수 있어 trace와 단계적으로 조합한다.',
      core: '성능 측정값에는 대상과 도구가 함께 들어 있으므로 관측 비용을 별도 변수로 다뤄야 한다.'
    },
    {
      id: 83, category: 'I',
      question: 'CPU profiler에서 Present가 7ms라 렌더링 제출이 느리다고 봤는데 실제로는 GPU가 원인일 수 있다. 그 7ms 동안 누가 누구를 기다렸나?',
      scenario: 'CPU가 frame queue 제한이나 swapchain acquire에서 GPU 완료를 기다리며 driver call 안에 block된다.',
      concepts: ['CPU-GPU synchronization', 'frame queue', 'fence', 'critical path'],
      labLabel: 'CPU submit과 GPU 실행 cursor를 움직여 Present 대기의 실제 선행 작업 찾기',
      boundary: 'CPU call stack에 시간이 귀속된 위치와 그 시간을 발생시킨 자원·선행 dependency를 구분한다.',
      naive: 'CPU scope가 길면 그 함수 내부 CPU 계산을 최적화한다.',
      failure: 'Present wrapper를 줄여도 GPU backlog와 fence wait가 그대로라 frame time은 변하지 않는다.',
      reasoning: 'CPU·GPU timeline을 공통 frame ID와 fence로 맞추고 wait reason과 queue depth를 확인한다.',
      build: 'submit/present/acquire/fence marker, GPU timestamp query, frames-in-flight를 함께 캡처한다.',
      verify: 'GPU workload를 줄이거나 queue depth를 바꾼 통제 실험에서 Present wait가 따라 변하는지 본다.',
      trade: 'frames-in-flight 증가는 CPU stall을 숨길 수 있지만 input latency와 메모리를 늘린다.',
      core: 'profile의 긴 함수는 원인이 아니라 기다림이 관측된 장소일 수 있어 dependency의 반대편을 찾아야 한다.'
    },
    {
      id: 84, category: 'I',
      question: 'NPC 수와 frame time이 함께 늘었다. AI가 원인이라는 결론을 내리기 전에 어떤 통제 실험을 해야 하나?',
      scenario: 'NPC가 늘 때 draw call, animation, physics contact, network replication도 동시에 늘어 상관관계만으로 원인을 분리할 수 없다.',
      concepts: ['correlation', 'causality', 'controlled experiment', 'confounder'],
      labLabel: 'NPC 수와 하위 시스템을 독립적으로 고정해 원인 후보 제거하기',
      boundary: '함께 변하는 metric과 한 변수를 바꿨을 때 결과가 재현되는 인과 증거를 구분한다.',
      naive: '상관계수가 가장 큰 counter의 subsystem을 바로 최적화한다.',
      failure: '공통 원인인 NPC 수가 여러 subsystem을 키워 proxy metric을 원인으로 오해한다.',
      reasoning: '동일 world state에서 AI만 no-op, animation freeze, render cull 등 한 축씩 개입하고 paired capture를 비교한다.',
      build: 'deterministic replay와 runtime feature gate를 만들어 같은 입력에서 subsystem 비용을 켜고 끈다.',
      verify: '반복 순서를 무작위화하고 thermal·cache warmup을 통제해 effect size와 분산을 기록한다.',
      trade: '완벽한 격리는 상호작용 비용을 놓칠 수 있어 단독·조합 실험을 단계적으로 수행한다.',
      core: '프로파일 counter의 상관은 후보를 만들 뿐이며 원인 주장은 통제된 개입으로 결과가 변해야 성립한다.'
    },
    {
      id: 85, category: 'I',
      question: '로그를 넣으면 사라지는 data race를 어떻게 잡을까? 더 많은 printf가 왜 증거를 파괴할 수 있는가?',
      scenario: 'logging lock과 I/O delay가 thread scheduling·memory ordering을 바꿔 잘못된 interleaving을 더 이상 만들지 않는다.',
      concepts: ['Heisenbug', 'schedule perturbation', 'flight recorder', 'race detector'],
      labLabel: '두 thread 사건 사이에 logging delay를 넣어 race interleaving 변화 보기',
      boundary: '관찰을 통해 남긴 증거와 관찰 자체가 synchronization·delay를 추가한 효과를 구분한다.',
      naive: 'race 직전과 직후에 동기식 로그를 충분히 넣으면 원래 순서를 볼 수 있다고 생각한다.',
      failure: 'global logger mutex가 happens-before를 만들고 thread를 직렬화해 실패 window를 닫는다.',
      reasoning: '고정 크기 thread-local flight recorder에 작은 event를 lock 없이 기록하고 실패 후 snapshot하거나 sanitizer를 사용한다.',
      build: 'monotonic sequence, thread ID, object generation을 binary ring에 남기고 log formatting은 사후 처리한다.',
      verify: 'instrumentation 강도별 재현율을 비교하고 scheduler fuzz와 TSan 결과를 같은 invariant 위반과 연결한다.',
      trade: 'flight recorder도 완전 무비용은 아니며 overwrite와 clock 정렬 문제를 가진다.',
      core: '동시성 버그 관측은 원래 schedule을 최대한 보존하면서 invariant를 판별할 최소 증거만 수집해야 한다.'
    },
    {
      id: 86, category: 'I',
      question: 'RSS가 계속 높아 보여 leak이라 했지만 scene을 여러 번 오가도 더 늘지 않는다. live bytes, retained cache, allocator RSS를 어떻게 구분할까?',
      scenario: '객체는 해제됐지만 allocator가 page를 OS에 반환하지 않고 asset cache가 budget까지 유지한다.',
      concepts: ['memory leak', 'high-water mark', 'allocator retention', 'heap snapshot'],
      labLabel: 'scene load·unload를 반복해 live·cache·RSS 세 층의 변화를 분리하기',
      boundary: '도달 가능한 live allocation, 정책적으로 retained된 cache, allocator가 보유한 free span, OS resident page를 나눈다.',
      naive: '작업 관리자 RSS가 unload 뒤 줄지 않으면 모두 leak이라고 본다.',
      failure: '잘못된 가설로 allocator trim을 반복해 성능을 악화시키거나 실제 owner chain은 찾지 못한다.',
      reasoning: '동일 checkpoint의 heap snapshot을 generation별로 diff하고 allocation stack·owner graph와 cache budget을 본다.',
      build: 'tagged allocator metric에 live/requested/reserved/resident를 분리하고 scene epoch별 outstanding owner를 집계한다.',
      verify: '반복 cycle 후 live set이 계속 증가하는지, plateau인지, trim 시 RSS만 줄어드는지 비교한다.',
      trade: '상세 allocation tracking은 비용이 커 dev build·sampling을 사용하고 production은 aggregate tag를 둔다.',
      core: '높은 메모리는 현상이고 leak은 수명이 끝난 객체가 참조로 계속 살아 증가하는 특정 원인이다.'
    },
    {
      id: 87, category: 'I',
      question: 'optimized crash dump의 top frame만 고치면 될까? corruption이 수천 frame 앞에서 시작됐을 때 어떤 증거를 남길까?',
      scenario: 'allocator metadata가 먼저 덮였고 나중의 unrelated allocation에서 crash한다. 현재 stack은 탐지 지점이지 손상 지점이 아니다.',
      concepts: ['fault origin', 'crash dump', 'canary', 'event breadcrumbs'],
      labLabel: '메모리 손상 시점과 crash 탐지 시점을 분리해 breadcrumb 추적하기',
      boundary: '오류가 만들어진 origin, 손상이 전파된 기간, invariant가 처음 탐지된 crash site를 구분한다.',
      naive: 'dump의 access violation instruction과 top stack 함수가 버그를 만든 곳이라고 단정한다.',
      failure: '그 함수는 이미 손상된 pointer를 처음 역참조했을 뿐이고 재현 없는 수정은 symptom만 이동시킨다.',
      reasoning: 'guard page, canary, allocator quarantine로 탐지 시점을 origin에 가깝게 당기고 최근 owner/event history를 보존한다.',
      build: 'object generation·last writer breadcrumb, sampled allocation stack, build ID, deterministic replay seed를 crash artifact에 포함한다.',
      verify: '의도적 overwrite를 주입해 어느 탐지 기법이 origin과 crash 거리, overhead를 얼마나 줄이는지 본다.',
      trade: 'quarantine·guard는 메모리와 성능 비용이 커 선택적 대상과 재현 환경에 집중한다.',
      core: 'crash stack은 실패가 보인 지점이며 원인을 찾으려면 invariant가 처음 깨진 시점까지 시간을 거슬러 갈 증거가 필요하다.'
    },
    {
      id: 88, category: 'I',
      question: '최근 200개 commit 중 성능 회귀를 찾으려는데 benchmark noise 때문에 good/bad 판정이 뒤집힌다. bisect를 어떻게 신뢰할 수 있게 만들까?',
      scenario: 'thermal throttling, shader cache, background process, random spawn이 commit 차이보다 큰 분산을 만든다.',
      concepts: ['regression bisect', 'benchmark noise', 'confidence interval', 'reproducibility'],
      labLabel: 'commit 효과와 측정 noise를 조절해 bisect 판정 오류 확인하기',
      boundary: '실제 code effect와 환경·입력에 따른 측정 분산, 단일 threshold 판정을 구분한다.',
      naive: '각 commit을 한 번 실행하고 16.6ms보다 크면 bad로 분류한다.',
      failure: '중간 commit의 잘못된 판정이 탐색 범위를 반대로 버려 culprit를 놓친다.',
      reasoning: 'deterministic workload, warmup, paired repeated samples와 회귀 임계 effect size를 사용하고 불확실하면 재측정한다.',
      build: 'artifact 고정, machine isolation, randomized A/B 실행, median·bootstrap interval을 자동 bisect gate에 넣는다.',
      verify: '알려진 synthetic regression을 여러 크기로 주입해 탐지율과 false positive를 계산한다.',
      trade: '표본 수를 늘리면 CI 시간이 증가해 초기 빠른 판정 후 경계 commit에 adaptive sampling을 쓴다.',
      core: 'binary search는 각 good/bad 판정이 신뢰할 수 있을 때만 빠르며 noisy oracle을 먼저 고쳐야 한다.'
    },
    {
      id: 89, category: 'I',
      question: '최적화 전후 microbenchmark가 20% 빨라졌는데 실제 전투 frame은 그대로다. benchmark가 무엇을 빼먹었을 수 있나?',
      scenario: '작은 loop가 warm L1 data, turbo 최대, dead-code elimination 조건에서 실행되고 실제 workload의 cache miss·contention·input 분포가 없다.',
      concepts: ['microbenchmark', 'warmup', 'representative workload', 'dead-code elimination'],
      labLabel: 'cache 상태·입력 분포·결과 소비를 바꿔 micro와 frame 효과 비교하기',
      boundary: '함수 자체 service time 개선과 end-to-end critical path에서 그 함수가 차지하는 비율을 구분한다.',
      naive: '격리 benchmark의 상대 개선율을 실제 frame 전체 개선율로 그대로 예측한다.',
      failure: 'compiler가 결과를 제거하거나 실제 병목이 GPU·memory wait여서 줄인 CPU 산술이 critical path에 없다.',
      reasoning: 'benchmark가 실제 입력 크기·분포·cache state를 재현하고 결과를 observable하게 만들며 full replay로 최종 검증한다.',
      build: 'cold/warm 두 조건, randomized input, black-box consume, hardware counter와 end-to-end A/B를 둔다.',
      verify: 'micro 결과를 subsystem capture와 실제 frame change에 단계적으로 연결하고 Amdahl 예상과 비교한다.',
      trade: '현실적인 benchmark는 느리고 변동성이 크다. 빠른 micro는 원리 검증, replay는 제품 효과 검증에 쓴다.',
      core: 'benchmark는 질문에 답하는 실험이며 실제 제품 질문과 다른 조건이면 정확한 숫자도 잘못된 결론을 준다.'
    },
    {
      id: 90, category: 'I',
      question: 'CPU 함수 시간을 합치면 22ms인데 frame wall time은 14ms다. 병렬 job의 합계와 critical path 중 무엇을 줄여야 하나?',
      scenario: '여러 worker scope가 동시에 실행되어 inclusive CPU time 합은 wall time보다 크고 일부 job은 frame 완료를 막지 않는다.',
      concepts: ['critical path', 'work vs span', 'parallel timeline', 'Amdahl'],
      labLabel: 'worker job 길이와 dependency를 바꿔 총 work와 frame critical path 비교하기',
      boundary: '모든 core가 수행한 work 합과 dependency chain의 가장 긴 span, idle wait를 구분한다.',
      naive: 'profiler에서 inclusive time이 가장 큰 함수부터 줄이면 frame도 같은 비율로 빨라진다고 본다.',
      failure: 'critical path 밖의 병렬 job을 줄여도 fence 완료 시점은 변하지 않고 반대로 작은 직렬 barrier가 전체를 막을 수 있다.',
      reasoning: 'frame DAG와 synchronized timeline에서 present까지 이어지는 dependency chain을 찾고 그 위의 work·wait를 먼저 줄인다.',
      build: 'job enqueue/start/finish와 dependency edge를 trace ID로 연결해 work, span, parallel slack을 계산한다.',
      verify: '후보 job을 인위적으로 지연·단축해 frame end가 따라 움직이는지 확인한다.',
      trade: 'critical path는 장면과 frame마다 바뀌어 평균 하나가 아니라 대표 workload별 분포가 필요하다.',
      core: '병렬 성능에서 총 work는 자원 비용이고 frame latency는 dependency가 만든 가장 긴 경로로 결정된다.'
    }
  );
})();
