(function () {
  'use strict';
  window.CSInterviewData.questions.push(
    {
      id: 61, category: 'G',
      question: 'Release 빌드에서만 체력 감소 검사가 사라진다. signed overflow 하나가 왜 앞선 분기까지 “불가능”하게 만들 수 있는가?',
      scenario: '`if (hp + damage < hp)`로 overflow를 감지하려 했지만 C++ signed overflow는 정의된 wraparound가 아니다. 최적화기는 정의된 실행만 보존하면 된다.',
      concepts: ['undefined behavior', 'as-if rule', 'signed overflow', 'optimizer assumptions'],
      labLabel: '입력 범위와 최적화 가정을 바꿔 사라지는 분기 확인하기',
      boundary: '컴파일러 버그와 언어가 아무 의미도 약속하지 않은 실행을 구분하고, unsigned의 정의된 modulo 연산과 비교한다.',
      naive: 'CPU가 2의 보수로 wrap하므로 Release에서도 같은 machine result를 얻는다고 생각한다.',
      failure: '최적화기는 정의된 signed 덧셈이라면 `hp + damage < hp`가 성립하지 않는다고 추론해 검사를 제거할 수 있다.',
      reasoning: 'overflow가 가능한 입력이면 더 넓은 타입에서 범위를 먼저 검사하거나 명시적 checked arithmetic을 사용해야 한다.',
      build: '도메인 경계에서 입력을 검증하고 `damage > max - hp`처럼 overflow 전 비교한다. sanitizer 빌드와 compiler warning을 CI에 둔다.',
      verify: 'Debug/Release, 여러 최적화 수준과 compiler에서 경계값·fuzz 입력을 돌리고 UBSan 결과를 수집한다.',
      trade: '모든 연산을 checked로 만들면 비용과 코드량이 든다. 외부 입력·경제·보안 경계에 우선 적용한다.',
      core: '최적화는 실제 CPU 습관이 아니라 언어가 정의한 프로그램만 보존하며, UB 이후의 직관은 증거가 아니다.'
    },
    {
      id: 62, category: 'G',
      question: '작은 AI 함수를 전부 force-inline했더니 instruction 수는 줄었는데 프레임이 느려졌다. 호출 제거가 왜 항상 이득이 아닌가?',
      scenario: '수십 종류 행동 코드가 각 call site에 복제되어 hot loop의 instruction working set이 L1I와 uop cache를 넘는다.',
      concepts: ['inlining', 'instruction cache', 'code size', 'profile-guided optimization'],
      labLabel: 'inline 비율을 올려 call 비용과 instruction-cache miss가 교차하는 지점 찾기',
      boundary: '한 호출의 overhead와 전체 hot path의 code footprint·frontend stall을 함께 본다.',
      naive: 'call/return과 register save가 사라지므로 가능한 모든 함수에 inline을 강제한다.',
      failure: '복제된 cold branch까지 hot loop에 들어와 I-cache line을 밀어내고 branch predictor의 주소 footprint도 커진다.',
      reasoning: '작고 빈번하며 call site별 상수 전파 이득이 큰 함수만 inline하고, 큰 오류·희귀 경로는 outline한다.',
      build: 'compiler heuristic을 기본으로 두고 PGO·BOLT류 profile을 활용한다. force-inline은 측정된 병목에만 제한한다.',
      verify: 'cycles뿐 아니라 retired instructions, L1I miss, frontend bound, binary text size를 빌드별로 비교한다.',
      trade: 'outline은 call overhead를 되돌리지만 code locality와 build time, 디버깅 가능성을 개선할 수 있다.',
      core: 'inline은 호출 비용을 없애는 대신 code를 복제하는 교환이며 최적점은 CPU frontend의 실제 working set으로 결정된다.'
    },
    {
      id: 63, category: 'G',
      question: '입자 업데이트 loop가 auto-vectorize되지 않는다. 컴파일러가 두 pointer의 겹침 가능성을 왜 무시하지 못하는가?',
      scenario: '`positions`와 `velocities`가 같은 allocation을 가리킬 수 있는 API라면 store가 다음 load를 바꿀 수 있어 loop iteration을 자유롭게 묶지 못한다.',
      concepts: ['alias analysis', 'auto-vectorization', 'restrict contract', 'dependency'],
      labLabel: '두 buffer의 겹침 여부와 alias 계약을 바꿔 SIMD 묶음 가능성 보기',
      boundary: '실제로 겹치지 않는다는 개발자 지식과 함수 signature로 compiler가 증명할 수 있는 사실을 구분한다.',
      naive: '현재 call site에서 다른 vector를 넘겼으니 compiler도 당연히 안다고 생각한다.',
      failure: '별도 컴파일 단위나 공개 API에서는 alias 가능성을 보수적으로 가정해 load/store 순서를 유지한다.',
      reasoning: '데이터 소유 구조가 비겹침을 보장하도록 만들고, 언어·compiler가 지원하는 alias contract를 정확히 전달한다.',
      build: 'SoA buffer와 명확한 span 범위, restrict 계열 한정자 또는 runtime overlap guard 뒤 vector path를 둔다.',
      verify: 'vectorization report와 disassembly로 SIMD 생성 여부를 보고, 의도적으로 겹친 입력에서 contract 위반을 테스트한다.',
      trade: '강한 non-alias 계약은 최적화를 열지만 위반 시 잘못된 코드가 된다. 안전한 fallback과 API 경계가 필요하다.',
      core: '컴파일러 최적화는 개발자의 의도가 아니라 코드가 증명하거나 명시한 메모리 의존성 계약 위에서만 가능하다.'
    },
    {
      id: 64, category: 'G',
      question: 'ECS component 조합을 template로 확장했더니 실행은 빠른데 빌드와 binary가 폭증한다. 어떤 중복이 생긴 것인가?',
      scenario: 'translation unit마다 동일한 template 조합을 파싱·인스턴스화하고 서로 다른 타입 조합마다 거의 같은 machine code가 생성된다.',
      concepts: ['template instantiation', 'code bloat', 'explicit instantiation', 'type erasure'],
      labLabel: 'component 타입과 조합 수를 늘려 생성되는 인스턴스·빌드 비용 계산하기',
      boundary: '런타임 dispatch 제거 이득과 compile-time 조합 폭발·code size 비용을 분리한다.',
      naive: 'template는 zero-cost abstraction이므로 조합 수가 늘어도 비용은 실행 시점에만 없다고 본다.',
      failure: '조합 수가 곱셈으로 늘고 각 TU가 반복 작업한다. linker가 identical code folding을 해도 compile time과 debug info는 이미 지불했다.',
      reasoning: '성능이 필요한 축만 정적으로 남기고 변화가 큰 축은 runtime descriptor나 type erasure로 접는다.',
      build: '명시적 instantiation TU, extern template, stable archetype set, 공통 non-template core를 사용한다.',
      verify: 'compiler time trace, object별 text/debug size, instantiation count, incremental rebuild fan-out을 측정한다.',
      trade: 'type erasure는 간접 호출과 타입 안전성 비용이 있지만 build scalability와 ABI 안정성을 얻는다.',
      core: 'zero-cost는 비용이 없다는 뜻이 아니라 추상화의 런타임 비용을 다른 단계와 code size로 옮길 수 있다는 뜻이다.'
    },
    {
      id: 65, category: 'G',
      question: '게임 시작 때 가끔 component factory가 비어 있다. 전역 registrar가 main 전에 실행되는데 왜 순서를 믿을 수 없는가?',
      scenario: '한 translation unit의 registry 생성자와 다른 translation unit의 registrar 생성자 사이 초기화 순서는 정해지지 않았다.',
      concepts: ['static initialization order', 'translation unit', 'construct-on-first-use', 'registration'],
      labLabel: '두 번역 단위의 초기화 순서를 바꿔 registry-before-registrar 실패 재현하기',
      boundary: '한 TU 내부의 선언 순서와 서로 다른 TU 사이의 동적 초기화 순서를 구분한다.',
      naive: '소스 파일이나 linker 입력 목록의 순서대로 전역 생성자가 실행된다고 기대한다.',
      failure: 'registrar가 먼저 실행되면 아직 생성되지 않은 registry를 접근하며 시작 전 crash나 누락을 만든다.',
      reasoning: '초기화가 필요한 전역 객체 사이 숨은 의존성을 제거하고 명시적 bootstrap 순서로 옮긴다.',
      build: '함수 지역 static registry 또는 dependency가 드러난 `RegisterAllComponents()`를 main 초기화 phase에서 호출한다.',
      verify: 'link 순서를 섞은 빌드와 여러 플랫폼에서 startup registry 내용, shutdown 역순 문제까지 확인한다.',
      trade: '명시적 등록은 boilerplate와 누락 위험이 있어 generated list나 linker section을 사용할 수 있지만 수명 계약은 여전히 필요하다.',
      core: '프로그램 시작 전 전역 부작용은 보이지 않는 dependency graph이며, 순서가 중요하면 코드로 그 순서를 소유해야 한다.'
    },
    {
      id: 66, category: 'G',
      question: '헤더는 같아 보이는데 한 모듈은 Entity를 24바이트, 다른 모듈은 32바이트로 본다. 실행 중 어떤 식으로 무너지는가?',
      scenario: '서로 다른 compile define과 packing pragma로 class layout이 달라졌고 두 모듈이 inline 함수와 배열 stride를 각자 생성했다.',
      concepts: ['ODR', 'class layout', 'packing', 'compile flags'],
      labLabel: '모듈별 field layout과 stride를 겹쳐 잘못 읽는 주소 확인하기',
      boundary: 'linker가 탐지하는 duplicate symbol과 탐지하지 못한 채 서로 다른 정의를 사용한 ODR 위반을 구분한다.',
      naive: '같은 header 파일 경로를 include했으니 모든 모듈의 타입 layout도 같다고 본다.',
      failure: '조건부 field, alignment, packing이 다르면 배열 두 번째 원소 주소부터 어긋나고 inline accessor는 각 모듈의 offset을 사용한다.',
      reasoning: '공유 타입의 compile configuration을 단일화하고 ABI 경계에는 layout에 민감한 C++ class 대신 고정 폭 wire 구조나 accessor를 둔다.',
      build: 'generated config, static_assert(sizeof/alignof/offsetof), ABI fingerprint를 빌드·load 시 비교한다.',
      verify: '각 binary가 출력한 layout manifest를 diff하고 sanitizer·cross-module integration test를 돌린다.',
      trade: '모든 내부 타입을 ABI 안정화하면 진화가 느려진다. 실제 module 경계의 소수 타입만 엄격히 관리한다.',
      core: '타입 이름이 같다는 사실은 binary layout 계약이 같다는 증거가 아니며 모든 compile 조건이 정의의 일부다.'
    },
    {
      id: 67, category: 'G',
      question: '새 DLL 플러그인에 bool field 하나를 추가했더니 옛 게임이 이후 float를 엉뚱하게 읽는다. field 목록 외에 무엇이 ABI를 정하는가?',
      scenario: 'compiler별 alignment와 padding, enum 크기, calling convention이 다르고 host가 plugin struct를 값으로 직접 읽는다.',
      concepts: ['ABI', 'alignment', 'padding', 'calling convention'],
      labLabel: 'field를 추가하고 정렬 규칙을 바꿔 host와 plugin의 offset 비교하기',
      boundary: 'source 호환성과 이미 빌드된 binary가 같은 bytes·register를 해석하는 binary 호환성을 구분한다.',
      naive: '뒤에 field를 추가하거나 작은 bool을 넣는 변화는 기존 field에 영향을 주지 않는다고 본다.',
      failure: 'padding이 재배치되고 struct 크기·array stride가 바뀐다. compiler가 다르면 인자 전달 register와 name mangling도 달라질 수 있다.',
      reasoning: '플러그인 경계는 version과 size가 있는 C ABI function table로 좁히고 host가 모르는 tail을 건너뛸 수 있어야 한다.',
      build: '`GetApi(requestedVersion, ApiTable*)`와 fixed-width type, opaque handle, create/destroy pair를 사용한다.',
      verify: '이전 host×새 plugin, 새 host×이전 plugin matrix와 여러 compiler 빌드에서 handshake와 offset을 검사한다.',
      trade: 'C ABI는 표현력이 낮고 adapter가 필요하지만 compiler·표준 라이브러리 변화로부터 경계를 격리한다.',
      core: 'ABI는 source 문법이 아니라 bytes의 위치, register 사용, 이름과 객체 수명을 양쪽 binary가 동일하게 해석하는 계약이다.'
    },
    {
      id: 68, category: 'G',
      question: '플러그인이 만든 string을 게임이 delete하자 특정 배포판에서만 heap corruption이 난다. 포인터가 유효한데 무엇이 다른가?',
      scenario: 'DLL과 host가 다른 CRT/allocator instance를 사용하며 할당 metadata 형식과 heap 소유자가 다르다.',
      concepts: ['allocator boundary', 'CRT', 'ownership', 'module lifetime'],
      labLabel: '할당 heap과 해제 heap을 연결해 cross-module corruption 확인하기',
      boundary: '주소가 현재 매핑되어 있다는 것과 같은 allocator가 그 block의 metadata를 소유한다는 것을 구분한다.',
      naive: 'C++ 타입이 같고 포인터가 정상이라 어느 모듈에서 delete해도 같다고 생각한다.',
      failure: '다른 heap의 free list에 낯선 block을 넣거나 STL 구현·debug iterator 상태가 달라 즉시 또는 나중에 손상된다.',
      reasoning: '할당한 모듈이 해제하거나 양쪽이 명시적으로 같은 allocator callback을 사용해야 한다.',
      build: 'API에 `ReleaseString`을 제공하거나 caller-owned buffer와 size query 패턴을 쓴다. STL 객체와 exception을 경계 밖으로 내보내지 않는다.',
      verify: 'CRT 조합, Debug/Release, plugin unload 직전 outstanding allocation을 추적하고 heap verifier를 사용한다.',
      trade: '복사와 명시적 release API가 늘지만 소유권과 module unload 안전성이 분명해진다.',
      core: '메모리의 수명 계약에는 누가 만들었는지뿐 아니라 어떤 allocator와 binary가 파괴할 권한을 갖는지도 포함된다.'
    },
    {
      id: 69, category: 'G',
      question: 'hot reload 후 기존 NPC의 virtual Update가 새 함수가 아니라 해제된 DLL 주소로 간다. 객체를 살려 둔 채 코드만 바꿀 수 있는가?',
      scenario: '기존 객체의 vptr과 callback pointer가 old module의 code/data section을 가리킨 상태에서 DLL이 unload된다.',
      concepts: ['vtable', 'dynamic library lifetime', 'hot reload', 'indirection'],
      labLabel: 'DLL 세대를 교체하고 기존 객체의 vptr이 가리키는 주소 추적하기',
      boundary: '새 symbol을 load하는 것과 이미 생성된 객체·함수 포인터가 새 구현을 자동 참조하는 것을 구분한다.',
      naive: '같은 class 이름의 새 DLL을 load하면 기존 virtual dispatch도 새 vtable로 바뀐다고 생각한다.',
      failure: 'vptr은 객체 안의 주소 값이며 old DLL unload 뒤 dangling code pointer가 된다. layout까지 변하면 객체 bytes도 호환되지 않는다.',
      reasoning: 'reload 가능한 상태와 실행 코드를 분리하고 stable host indirection table을 통해 generation별 함수를 교체해야 한다.',
      build: 'opaque state blob 또는 migration 함수, handle 기반 instance, host-owned function table, quiescence barrier 뒤 old module unload를 사용한다.',
      verify: 'call in flight, worker callback, exception stack, 기존 instance가 모두 old generation을 떠났는지 refcount·epoch로 검사한다.',
      trade: '한 단계 간접 호출과 migration 제약을 받지만 dangling vtable과 ABI 결합을 피한다.',
      core: 'hot reload는 파일 교체가 아니라 살아 있는 데이터와 실행 주소의 모든 참조를 새 generation으로 안전하게 이전하는 프로토콜이다.'
    },
    {
      id: 70, category: 'G',
      question: '크래시 주소는 있는데 symbol server의 최신 PDB로 해석하니 전혀 다른 함수가 나온다. 주소만으로 source를 찾을 수 없는 이유는?',
      scenario: 'ASLR base를 뺀 RVA가 있어도 최적화·link 순서가 다른 build에서는 함수 배치와 inline 정보가 달라진다.',
      concepts: ['build ID', 'debug symbols', 'RVA', 'linker layout'],
      labLabel: '같은 RVA를 서로 다른 build map에 대입해 잘못된 symbolization 확인하기',
      boundary: '실행 시 module base 변화와 build 자체의 code layout 변화를 구분한다.',
      naive: '함수 이름이 같고 소스 revision이 비슷하면 최신 symbol로도 대략 맞게 해석된다고 본다.',
      failure: '작은 code change, LTO, identical folding, link order가 RVA를 바꾸며 inline call site 정보는 해당 binary의 debug artifact에만 있다.',
      reasoning: 'crash에는 module별 build ID, load base, architecture를 기록하고 exact binary와 symbol을 immutable 보관해야 한다.',
      build: 'CI가 build ID로 binary·PDB/dSYM·map을 content-addressed storage에 업로드하고 symbolizer가 ID 일치 없이는 해석을 거부한다.',
      verify: '의도적으로 다른 symbol을 넣었을 때 mismatch를 검출하고 stripped production dump를 exact artifact로 재현한다.',
      trade: 'symbol 보관 비용과 개인정보 관리가 필요하지만 잘못된 stack trace를 근거로 조사하는 비용보다 작다.',
      core: '기계 주소의 의미는 특정 build의 linker layout에 속하며 정확한 build identity 없는 symbolization은 추측이다.'
    }
  );
})();
