(function () {
  'use strict';
  window.CSInterviewData.questions.push(
    {
      id: 91, category: 'J',
      question: 'packet의 count×elementSize를 검사해 buffer를 할당했는데 작은 allocation 뒤 큰 memcpy가 실행된다. 길이 검증에서 어떤 산술을 먼저 의심할까?',
      scenario: '32-bit 곱셈이 wrap한 뒤 max packet보다 작다는 검사를 통과하고 decoder는 원래 count만큼 element를 복사한다.',
      concepts: ['integer overflow', 'bounds check', 'untrusted input', 'checked arithmetic'],
      labLabel: 'packet count와 정수 폭을 바꿔 검사를 통과하는 wraparound 만들기',
      boundary: 'wire field가 범위 안이라는 검사, 산술 중간값이 표현 가능한지, 실제 buffer 남은 bytes를 각각 확인한다.',
      naive: '`count * sizeof(T) <= packetSize` 한 줄이면 충분하다고 생각한다.',
      failure: '곱셈이 비교보다 먼저 좁은 타입에서 overflow하면 작아진 값으로 검사를 수행한다.',
      reasoning: '`count <= remaining / elementSize`처럼 나눗셈 형태로 검사하거나 checked multiply를 사용하고 protocol별 절대 상한을 둔다.',
      build: 'cursor-based reader가 매 field마다 remaining을 줄이고 allocation·nesting·element count budget을 함께 강제한다.',
      verify: '0, max, max±1, wrap 경계와 truncated packet을 fuzz하고 ASan/UBSan·property test를 돌린다.',
      trade: '검증 branch가 늘지만 network 입력 경계에서는 성능보다 memory safety가 우선이며 vectorized decode 전에도 검증이 필요하다.',
      core: '신뢰할 수 없는 길이는 산술 자체부터 검증돼야 하며 overflow한 결과에 대한 bounds check는 보호막이 아니다.'
    },
    {
      id: 92, category: 'J',
      question: '암호화된 이동 packet을 공격자가 그대로 다시 보내도 유효하다. 기밀성과 무결성이 있는데 왜 replay는 별도 문제인가?',
      scenario: 'AEAD tag는 bytes가 변조되지 않았음을 증명하지만 예전에 정상 생성된 ciphertext가 지금도 신선한지는 말하지 않는다.',
      concepts: ['replay attack', 'nonce', 'sequence window', 'AEAD'],
      labLabel: '정상 packet을 복제해 sequence window 유무에 따른 수락 결과 보기',
      boundary: '내용 비밀, 발신자·무결성, 메시지의 신선성과 한 번만 처리됨을 구분한다.',
      naive: '인증된 암호화를 사용하면 캡처된 packet의 재전송도 자동으로 막힌다고 생각한다.',
      failure: '같은 유효 packet이 여러 번 적용되어 이동·구매·보상 명령이 반복된다.',
      reasoning: 'session별 단조 sequence와 sliding receive window로 중복·너무 오래된 packet을 거부하고 nonce reuse도 방지한다.',
      build: 'connection epoch, packet sequence, bitmap window를 authenticated header에 넣고 reconnect 시 새 key·epoch를 발급한다.',
      verify: 'duplicate, reorder, loss, window 경계, reconnect old packet을 생성해 수락 집합과 nonce uniqueness를 검사한다.',
      trade: 'reorder window는 memory와 상태를 쓰고 너무 작으면 정상 지연 packet을 버리며 너무 크면 replay 표면이 넓어진다.',
      core: '암호 인증은 “누가 만든 어떤 bytes인가”를 보장할 뿐 “언제 몇 번 처리할 것인가”는 sequence 상태가 결정한다.'
    },
    {
      id: 93, category: 'J',
      question: '클라이언트가 보낸 “보스에게 9,999 damage” packet의 형식과 서명은 정상이다. 서버는 무엇을 다시 계산해야 하나?',
      scenario: '정상 클라이언트 binary도 변조될 수 있고 client가 가진 position·cooldown·inventory state는 공격자가 제어한다.',
      concepts: ['trust boundary', 'server authority', 'validation', 'capability'],
      labLabel: 'client가 결과 또는 의도를 보내게 바꿔 서버 검증 범위 비교하기',
      boundary: 'packet이 해당 session에서 왔다는 인증과 packet 속 게임 주장이 규칙상 가능한지 검증하는 것을 구분한다.',
      naive: 'TLS와 anti-cheat가 있으므로 client 계산 결과를 서버가 그대로 반영한다.',
      failure: '공격자는 정상 protocol로 불가능한 이동·fire rate·damage를 요청하며 형식 검사는 모두 통과한다.',
      reasoning: 'client는 입력·의도를 보내고 권위 있는 서버가 위치, cooldown, line-of-sight, damage를 자기 state에서 계산한다.',
      build: 'command별 precondition과 resource ownership을 server aggregate에서 검증하고 거부 reason·rate를 telemetry로 남긴다.',
      verify: 'reordered·forged command, boundary speed, lag compensation 악용을 property·adversarial test한다.',
      trade: 'server authority는 CPU·latency를 늘려 prediction·reconciliation이 필요하지만 경쟁 결과의 신뢰 경계를 명확히 한다.',
      core: '인증된 client도 신뢰 경계 밖에 있으며 서버가 결과가 아닌 허용 가능한 의도를 받아 규칙을 소유해야 한다.'
    },
    {
      id: 94, category: 'J',
      question: '압축 replay 2MB를 열었더니 20GB와 수백만 object로 팽창한다. parser가 형식상 정상인 입력에도 어떤 budget을 가져야 하나?',
      scenario: '깊은 nesting, 거대한 count, 높은 압축률이 CPU·RAM·stack을 고갈시켜 memory corruption 없이도 서비스 거부를 만든다.',
      concepts: ['resource exhaustion', 'decompression bomb', 'complexity attack', 'budget'],
      labLabel: '압축률·nesting·object count를 바꿔 parser resource budget 차단 보기',
      boundary: '문법적으로 valid한 입력과 제품이 처리하기로 약속한 자원 범위 안의 입력을 구분한다.',
      naive: 'checksum과 schema validation을 통과하면 안전하게 끝까지 parse한다.',
      failure: 'allocation과 recursion이 입력에 비례하지 않고 증폭되어 frame·process·서버 전체 자원을 고갈시킨다.',
      reasoning: 'compressed bytes, expanded bytes, object count, depth, CPU step, wall deadline을 별도 budget으로 둔다.',
      build: 'streaming decoder가 출력 상한 전에 중단하고 arena quota·iterative parser·cancel deadline을 사용한다.',
      verify: '고압축·deep nesting·pathological graph를 fuzz해 각 budget에서 빠르고 일정하게 실패하는지 본다.',
      trade: '정상 대형 콘텐츠도 상한에 걸릴 수 있어 버전·권한별 budget과 명확한 오류가 필요하다.',
      core: '안전한 parser는 올바른 bytes만 읽는 것을 넘어 공격자가 소비시킬 수 있는 모든 자원을 제한한다.'
    },
    {
      id: 95, category: 'J',
      question: '상점 서버 응답이 느려 client가 retry하자 구매가 두 번 처리되고 서버 부하는 더 커졌다. timeout과 retry를 어떻게 하나의 정책으로 설계할까?',
      scenario: '요청은 성공했지만 응답만 유실됐고 각 계층이 독립 retry하며 retry storm과 duplicate side effect를 만든다.',
      concepts: ['timeout', 'retry', 'idempotency', 'exponential backoff'],
      labLabel: '응답 지연과 retry 간격을 바꿔 duplicate 구매와 retry storm 만들기',
      boundary: '작업이 실패했다는 사실과 caller가 deadline 안에 결과를 관측하지 못했다는 timeout을 구분한다.',
      naive: 'timeout이면 같은 구매 요청을 즉시 다시 보내면 신뢰성이 올라간다고 본다.',
      failure: '첫 요청이 commit된 뒤 응답만 늦으면 두 번째 요청도 새 구매로 적용되고 동시 retry가 서버 회복을 막는다.',
      reasoning: 'side effect 요청에는 idempotency key와 결과 record를 두고 retry는 deadline·횟수·backoff·jitter·retryable error를 제한한다.',
      build: 'client command ID, server dedup table, exponential backoff with jitter, global retry budget을 사용한다.',
      verify: 'commit 전후 응답 loss, partial outage, 다수 client 동시 timeout에서 정확히 한 번의 효과와 부하 곡선을 검사한다.',
      trade: 'dedup state의 TTL·저장 비용이 들며 영구 exactly-once 대신 정의된 시간창의 idempotent effect를 제공한다.',
      core: 'timeout은 결과 불명 상태이며 retry는 새 부하이므로 중복 안전성과 전체 retry budget 없이 신뢰성을 높이지 못한다.'
    },
    {
      id: 96, category: 'J',
      question: '접속 폭주 때 모든 요청을 공평하게 queue에 쌓았더니 결국 전체가 timeout된다. 일부를 빨리 거부하는 편이 왜 더 신뢰할 수 있는가?',
      scenario: 'arrival rate가 service capacity를 넘고 무제한 queue가 latency와 memory를 키워 healthy instance까지 죽인다.',
      concepts: ['overload', 'load shedding', 'backpressure', 'graceful degradation'],
      labLabel: '도착률과 처리률을 바꿔 무제한 queue와 admission limit의 생존성 비교하기',
      boundary: '일시 burst를 흡수하는 queue와 지속 overload에서 완료 가능성이 없는 요청을 지연시키는 queue를 구분한다.',
      naive: '모든 요청을 받아 순서대로 처리하는 것이 가장 공평하고 성공률도 높다고 생각한다.',
      failure: 'queue wait가 client timeout을 넘고 retry가 추가되어 positive feedback으로 전체 처리량까지 무너진다.',
      reasoning: 'bounded concurrency, queue deadline, 중요 endpoint reservation, cheap reject를 통해 완료 가능한 작업만 admission한다.',
      build: 'token bucket·semaphore, Retry-After, login/commerce 우선순위, cosmetic 기능 degradation을 둔다.',
      verify: 'step load와 retry client를 포함한 부하에서 goodput, p99, reject rate, recovery time을 본다.',
      trade: '일부 사용자는 즉시 실패하지만 전체 시스템과 핵심 기능의 성공률·회복성을 지킨다.',
      core: '과부하에서 신뢰성은 모든 일을 받는 것이 아니라 제한된 capacity로 끝낼 수 있는 일만 선택하는 능력이다.'
    },
    {
      id: 97, category: 'J',
      question: '전 서버에 새 loot formula config를 한 번에 배포했는데 전투 중 서버 이동 후 보상이 달라졌다. 설정도 code처럼 어떤 rollout 계약이 필요한가?',
      scenario: 'instance마다 갱신 시점이 다르고 진행 중 match가 어느 version을 사용해야 하는지 정의되지 않았다.',
      concepts: ['configuration versioning', 'feature flag', 'rollout', 'rollback'],
      labLabel: '서버별 config version과 match pinning을 바꿔 혼합 결과 확인하기',
      boundary: '배포 시스템이 파일을 전달했다는 것과 하나의 game transaction이 일관된 version을 사용한다는 것을 구분한다.',
      naive: 'config는 data라 hot reload해도 code deploy보다 안전하다고 생각한다.',
      failure: '같은 match의 여러 단계가 다른 formula를 쓰고 rollback 뒤에도 cache된 중간 결과가 남는다.',
      reasoning: 'immutable config version을 만들고 match/session 시작 때 version을 pin하며 canary·metric gate 후 확대한다.',
      build: 'schema validation, content hash, target cohort, kill switch, previous-version retention과 audit log를 둔다.',
      verify: 'mixed fleet, reconnect, server transfer, rollback에서 한 transaction의 config ID가 일관되는지 검사한다.',
      trade: 'version pinning은 여러 config를 메모리에 유지하고 즉시 긴급 수정 반영을 늦출 수 있다.',
      core: '설정은 실행 동작을 바꾸는 프로그램 입력이므로 identity, 일관성 범위, 단계적 공개와 rollback 증거가 필요하다.'
    },
    {
      id: 98, category: 'J',
      question: 'PC 시계를 뒤로 맞추자 cooldown이 늘어나거나 즉시 끝난다. 경과 시간과 달력 시간에 같은 clock을 쓰면 왜 깨질까?',
      scenario: 'wall clock은 NTP 조정·사용자 변경·DST로 점프하지만 monotonic clock은 같은 boot 안에서 경과 측정을 위해 역행하지 않는다.',
      concepts: ['monotonic clock', 'wall clock', 'clock adjustment', 'deadline'],
      labLabel: 'wall clock을 앞뒤로 조정해 cooldown과 UTC 표시 요구를 분리하기',
      boundary: '“얼마나 지났는가”와 “현실 세계의 언제인가”를 서로 다른 시간 의미로 구분한다.',
      naive: '현재 Unix timestamp 차이로 animation·timeout·cooldown을 모두 계산한다.',
      failure: 'clock correction이 음수 delta·긴 freeze·즉시 timeout을 만들고 여러 machine의 wall time은 정확히 동기화되지 않는다.',
      reasoning: '프로세스 내부 duration·deadline은 monotonic clock, 기록·캘린더는 UTC wall clock을 사용하고 둘을 섞지 않는다.',
      build: 'deadline=`steady_now+duration`, 로그에는 wall timestamp와 monotonic sequence를 함께 기록한다.',
      verify: '시계 전후 점프, sleep/resume, wrap, 서버 간 skew에서 cooldown invariant와 log ordering을 테스트한다.',
      trade: 'monotonic timestamp는 reboot·machine 사이 비교가 안 되어 correlation ID와 clock offset metadata가 필요하다.',
      core: '시간 API 선택은 정밀도 문제가 아니라 값이 점프해도 되는 달력 시각인지 역행하면 안 되는 경과 시간인지의 의미 계약이다.'
    },
    {
      id: 99, category: 'J',
      question: 'loot token을 gameplay RNG로 만들었더니 seed를 본 client가 다음 token을 예측한다. 결정적 난수와 보안 난수는 무엇을 다르게 요구하나?',
      scenario: '빠르고 replay 가능한 PRNG state가 노출되면 이후 출력이 모두 계산 가능해 session token·nonce에 쓸 수 없다.',
      concepts: ['PRNG', 'CSPRNG', 'entropy', 'predictability'],
      labLabel: 'gameplay seed 일부를 관측해 다음 출력 예측과 보안 entropy 차이 보기',
      boundary: '분포가 무작위처럼 보이는 통계 성질과 내부 state를 알아도 미래 출력을 예측할 수 없는 보안 성질을 구분한다.',
      naive: '주기가 길고 품질 좋은 gameplay PRNG면 token과 nonce에도 사용할 수 있다고 본다.',
      failure: 'replay seed·출력이 노출되면 공격자가 다음 password reset·loot claim token을 생성한다.',
      reasoning: 'simulation은 명시적 seed와 분리 stream의 deterministic PRNG, security token은 OS CSPRNG를 사용한다.',
      build: 'API type을 GameplayRng와 SecureRandom으로 분리하고 nonce uniqueness·token bit 수·encoding을 명시한다.',
      verify: 'replay 결정성, stream 독립성, token collision budget과 entropy source 실패 처리를 검사한다.',
      trade: 'CSPRNG는 재현할 수 없어 테스트에는 injectable secure interface를 쓰되 production seed를 로그에 남기지 않는다.',
      core: '난수의 적합성은 “랜덤해 보임”이 아니라 재현이 필요한 simulation인지 예측 불가능성이 필요한 보안 경계인지로 결정된다.'
    },
    {
      id: 100, category: 'J',
      question: '출시일에 보상 지급 지연·retry·서버 재시작이 겹쳐 아이템 중복이 발생했다. 증상 하나를 막는 patch 전에 어떤 시스템 불변식부터 세울까?',
      scenario: 'client timeout, queue retry, DB commit, inventory cache, 메시지 발행이 서로 다른 경계에서 부분 성공한다.',
      concepts: ['system invariant', 'failure model', 'transaction boundary', 'observability'],
      labLabel: '보상 command의 각 단계를 중단하며 중복·유실 없는 불변식 설계하기',
      boundary: 'API 성공 응답, DB state, event 발행, client 관측 중 제품이 보장할 원자적 효과의 범위를 정한다.',
      naive: '중복된 endpoint에 mutex나 retry 횟수 제한을 급히 추가한다.',
      failure: 'process 밖의 commit과 메시지는 mutex로 묶이지 않고 다른 중단 지점에서 유실 또는 중복 경로가 다시 생긴다.',
      reasoning: '“command ID당 inventory credit은 최대 한 번, 승인된 command는 결국 관측 가능” 같은 불변식과 모든 failure point를 먼저 열거한다.',
      build: 'idempotency record와 inventory mutation을 한 transaction에 두고 outbox event를 재전송하며 consumer도 event ID로 dedup한다.',
      verify: '각 write 전후 kill, duplicate delivery, reorder, DB failover를 fault injection해 불변식과 복구 수렴을 검사한다.',
      trade: '상태·storage·latency가 늘고 완전한 exactly-once 전송 대신 적어도 한 번 전달 위에 idempotent effect를 만든다.',
      core: '시니어 시스템 판단은 도구 이름을 고르는 일이 아니라 실패해도 지켜야 할 불변식과 그 증거를 먼저 정의하는 일이다.'
    }
  );
})();
