(function () {
  'use strict';
  window.CSInterviewData.questions.push(
    {
      id: 51, category: 'F',
      question: '오픈월드에서 2KB짜리 설정 파일 수만 개를 읽자 로딩이 느리다. 총 바이트는 작은데 왜 큰 pack 파일 하나보다 불리한가?',
      scenario: '파일마다 open, 경로 탐색, 권한 확인, metadata lookup이 반복되고 HDD에서는 seek가, SSD에서도 작은 I/O와 queue 제출 비용이 누적된다.',
      concepts: ['metadata I/O', 'seek', 'pack file', 'table of contents'],
      labLabel: '같은 데이터량을 파일 수와 pack 배치만 바꿔 로딩 경로 비교하기',
      boundary: '전송해야 할 payload 바이트와 그 payload를 찾고 I/O를 제출하는 고정 비용을 분리한다.',
      naive: '압축하지 않은 총용량이 같으면 디스크 읽기 시간도 거의 같다고 가정한다.',
      failure: '작은 파일마다 디렉터리 탐색과 handle 생성이 반복되고 read-ahead가 끊긴다. HDD seek뿐 아니라 SSD도 작은 요청의 CPU·커널 비용을 받는다.',
      reasoning: 'asset ID에서 연속 offset으로 바로 가는 TOC를 만들면 경로 탐색을 한 번으로 줄이고 인접 payload를 큰 요청으로 합칠 수 있다.',
      build: 'immutable pack, versioned TOC, block 정렬, 압축 chunk index를 둔다. 개발 중 증분 갱신은 overlay pack으로 처리하고 최종 빌드에서 병합한다.',
      verify: 'cold cache에서 open 수, I/O request 수, 평균 request 크기, queue depth, 실제 읽은 바이트와 wall time을 함께 측정한다.',
      trade: 'pack은 작은 patch에도 큰 파일을 다시 만들 수 있고 손상 영향 범위가 커진다. chunk hash와 overlay로 갱신 단위를 제한한다.',
      core: '저장장치 성능은 바이트 수만이 아니라 그 바이트까지 가는 요청의 개수·위치·연속성으로 결정된다.'
    },
    {
      id: 52, category: 'F',
      question: '“저장 완료” UI가 뜬 직후 전원을 뽑았더니 세이브가 사라졌다. write가 성공했는데 무엇이 아직 완료되지 않은 것인가?',
      scenario: '게임은 fwrite 반환 직후 성공 토스트를 띄웠지만 데이터는 프로세스 buffer와 OS page cache를 지나 장치의 volatile cache에 머물 수 있다.',
      concepts: ['buffered I/O', 'page cache', 'fsync', 'durability'],
      labLabel: '세이브가 RAM에서 장치까지 내려가는 계층을 직접 진행시키기',
      boundary: 'API가 bytes를 받아들였다는 성공, 다른 reader가 볼 수 있다는 가시성, 전원 손실 뒤에도 남는 내구성을 구분한다.',
      naive: 'write 호출이 요청한 바이트 수를 반환하면 물리 저장장치에 기록됐다고 간주한다.',
      failure: '사용자 공간 buffer나 page cache의 dirty page는 지연 기록될 수 있다. rename까지 했어도 directory entry 자체가 durable하지 않을 수 있다.',
      reasoning: '성공 계약이 전원 손실 내구성이라면 file data flush와 metadata 순서까지 플랫폼별 보장을 확인해야 한다.',
      build: 'temp에 전체 기록, checksum, file flush, atomic rename, 필요한 플랫폼에서 parent directory flush 순서로 commit한다.',
      verify: '각 단계에서 프로세스 kill과 강제 전원 손실을 주입하고 재시작 복구 결과를 구분해 기록한다.',
      trade: '매 저장마다 강한 flush는 latency spike와 장치 수명을 늘린다. checkpoint 간격과 중요 이벤트 journal을 조합한다.',
      core: 'write 성공은 전달 계층 하나의 수락일 뿐이며, 제품이 약속하는 durable 지점을 명시해야 한다.'
    },
    {
      id: 53, category: 'F',
      question: '세이브 파일의 앞 절반은 새 데이터, 뒤 절반은 옛 데이터다. 단일 파일 write인데 어떻게 이런 상태가 생기며 어떻게 복구할까?',
      scenario: '큰 세이브를 제자리 덮어쓰던 중 crash가 발생했고 sector·filesystem write 단위보다 큰 논리 record가 부분 반영됐다.',
      concepts: ['torn write', 'checksum', 'journal', 'copy-on-write'],
      labLabel: '세이브 block을 한 칸씩 기록하다 crash시키고 복구 전략 비교하기',
      boundary: '논리 record의 원자성과 저장장치가 보장하는 물리 write 단위를 구분한다.',
      naive: '한 번의 write 호출로 넘긴 buffer는 파일에도 전부 또는 전혀 기록되지 않는다고 생각한다.',
      failure: '큰 write는 여러 block으로 분해되며 crash 시 prefix만 새 값일 수 있다. 정상적으로 parse돼도 서로 다른 epoch가 섞인 의미적 손상일 수 있다.',
      reasoning: '완성본을 기존 good copy와 분리해 만들고 checksum·generation·commit marker로 어느 버전이 완결됐는지 판별해야 한다.',
      build: 'A/B slot 또는 append journal에 header, payload, checksum을 기록하고 마지막에 작은 commit record를 durable하게 쓴다.',
      verify: '모든 block 경계에서 crash를 주입해 부팅 시 반드시 이전 또는 새 완성본만 선택하는지 검사한다.',
      trade: '두 배 공간과 추가 write가 필요하지만 제자리 갱신보다 복구 계약이 단순하다. 대용량은 page 단위 COW를 고려한다.',
      core: '복구 가능한 저장은 정상 경로의 write가 아니라 모든 중단 지점에서 선택 가능한 완성본을 남기는 설계다.'
    },
    {
      id: 54, category: 'F',
      question: '패치가 실행 파일, asset pack, manifest 세 개를 바꾸다 중간에 끊겼다. 다음 실행에서 서로 다른 버전이 섞이지 않게 하려면?',
      scenario: '파일별 rename은 atomic해도 세 파일 전체의 교체는 하나의 filesystem transaction이 아니다.',
      concepts: ['atomic publish', 'manifest', 'content-addressing', 'rollback'],
      labLabel: '패치 파일을 순서대로 배치하고 manifest 전환 시점 찾기',
      boundary: '각 파일의 원자적 교체와 여러 파일로 이루어진 버전 집합의 원자적 공개를 구분한다.',
      naive: '파일 세 개를 차례로 rename하고 실패하면 다시 다운로드하면 된다고 본다.',
      failure: '두 번째 rename 뒤 crash하면 old manifest가 new asset을 가리키거나 new executable이 old schema를 읽는 혼합 상태가 남는다.',
      reasoning: 'immutable version directory를 완성한 뒤 단 하나의 작은 manifest pointer만 마지막에 바꾸면 공개의 linearization point가 하나가 된다.',
      build: 'hash 이름으로 blob을 검증·배치하고 version manifest를 flush한 다음 current pointer를 atomic replace한다. 이전 manifest는 rollback용으로 유지한다.',
      verify: 'download, verify, rename, pointer swap 모든 경계에서 kill하고 재실행해 old 또는 new 집합만 선택되는지 확인한다.',
      trade: '디스크 공간이 더 들고 garbage collection이 필요하지만 patch resume와 rollback이 명확해진다.',
      core: '여러 파일의 배포 원자성은 파일을 동시에 바꾸는 것이 아니라 완성된 집합을 가리키는 한 포인터를 바꾸어 만든다.'
    },
    {
      id: 55, category: 'F',
      question: 'NVMe인데도 4KB asset을 하나 읽고 기다리는 코드는 느리다. 빠른 장치에서 queue depth가 왜 중요한가?',
      scenario: '각 read를 제출한 직후 future.get으로 막아 장치에는 항상 요청 하나만 존재한다. 장치 내부 채널과 controller가 병렬로 일할 기회가 없다.',
      concepts: ['queue depth', 'latency hiding', 'IOPS', 'batching'],
      labLabel: 'I/O 제출 창 크기를 바꿔 장치 lane 활용률과 완료 시간 보기',
      boundary: '한 요청의 latency와 여러 요청을 겹쳐 얻는 throughput을 구분한다.',
      naive: 'NVMe 한 건 latency가 짧으므로 작은 read를 직렬로 해도 충분하다고 생각한다.',
      failure: 'CPU가 완료를 기다리는 동안 다음 요청을 제출하지 않아 controller queue가 비고 내부 병렬성이 놀게 된다.',
      reasoning: '독립 요청을 미리 제출해 적절한 queue depth를 유지하면 한 요청의 대기 시간 뒤에 다른 완료가 이어진다.',
      build: 'bounded async window와 completion queue를 두고 priority·cancellation을 보존한다. 인접 요청은 coalesce한다.',
      verify: 'QD별 p50/p99 latency, IOPS, CPU submit 비용, 읽기 증폭을 실제 target 장치에서 측정한다.',
      trade: '과도한 QD는 중요 요청을 뒤에 가두고 tail latency와 메모리 사용을 늘린다. 처리량 최대가 게임 체감 최적점은 아니다.',
      core: '비동기 I/O의 목적은 호출 형태가 아니라 장치가 처리할 독립 작업을 적절히 앞에 공급하는 것이다.'
    },
    {
      id: 56, category: 'F',
      question: '압축 pack 끝의 한 asset만 필요한데 앞에서부터 모두 풀고 있다. 압축률을 유지하면서 random access를 어떻게 만들까?',
      scenario: 'pack 전체가 하나의 압축 stream이라 후반 asset의 시작점을 알더라도 decoder state를 복원하려면 앞 데이터를 처리해야 한다.',
      concepts: ['compression blocks', 'random access', 'index', 'read amplification'],
      labLabel: '압축 chunk 크기를 바꿔 index 크기와 읽기 증폭 비교하기',
      boundary: '논리 asset 경계, 압축 decoder의 독립 시작 경계, 저장장치 I/O 정렬 경계를 나눠 본다.',
      naive: 'TOC에 asset offset만 저장하면 압축 파일에서도 바로 seek할 수 있다고 본다.',
      failure: '한 stream의 중간 compressed offset은 필요한 dictionary state가 없어 독립 해제가 불가능하다.',
      reasoning: '독립 압축 block과 index를 만들면 목표 asset이 겹치는 block만 읽고 해제할 수 있다.',
      build: 'asset locality에 맞춰 chunk를 묶고 각 chunk의 compressed offset, size, hash를 TOC에 둔다. 대형 asset은 subchunk한다.',
      verify: '랜덤 workload에서 실제 요청 bytes/사용 bytes 비율, decompress CPU, index RAM, sequential throughput을 함께 잰다.',
      trade: '작은 chunk는 random access가 좋지만 압축률과 index 비용이 나빠지고 큰 chunk는 그 반대다.',
      core: '압축 random access는 파일 offset 문제가 아니라 decoder 상태를 독립적으로 다시 시작할 수 있는 경계를 설계하는 문제다.'
    },
    {
      id: 57, category: 'F',
      question: '씬을 나갔는데 이전 씬의 비동기 texture read가 계속 완료되어 새 씬 메모리를 밀어낸다. 취소는 어디까지 책임져야 하나?',
      scenario: 'OS I/O는 이미 장치에 제출돼 물리적으로 멈추지 않을 수 있고 callback은 scene 객체가 파괴된 뒤 도착할 수 있다.',
      concepts: ['cancellation', 'completion ownership', 'generation', 'resource budget'],
      labLabel: '씬 전환 뒤 요청의 제출·완료·commit 단계를 따라 취소 효과 확인하기',
      boundary: '요청 제출 취소, 장치 작업 중단, 완료 callback 억제, 결과 commit 거부를 서로 다른 보장으로 본다.',
      naive: 'cancel 함수를 호출하면 장치 read도 즉시 사라지고 callback도 오지 않는다고 가정한다.',
      failure: '이미 완료 queue로 이동한 callback이 파괴된 owner를 만지거나, commit은 막아도 큰 buffer가 끝까지 살아 메모리 압박을 만든다.',
      reasoning: '취소 token은 각 pipeline 단계가 더 이상 가치 없는 작업을 빨리 버리게 하는 협력 계약이며 마지막 commit gate는 반드시 owner generation을 확인해야 한다.',
      build: 'scene epoch를 request에 넣고 queue 전·I/O 후·decompress 전·upload 전마다 확인한다. callback은 안전한 completion owner로 반환한다.',
      verify: '모든 단계에서 scene unload를 주입해 UAF, GPU upload, resident byte, callback 잔류가 사라지는지 검사한다.',
      trade: '검사와 상태 관리 비용이 들고 이미 수행한 I/O는 회수하지 못할 수 있다. 그래도 downstream 낭비와 안전 문제를 제한한다.',
      core: '취소는 시간을 되돌리는 기능이 아니라 오래된 작업이 다음 부작용 경계를 넘지 못하게 하는 프로토콜이다.'
    },
    {
      id: 58, category: 'F',
      question: '플레이어 앞 지형과 멀리 있는 speculative texture가 같은 I/O queue에 있다. 중요한 요청의 p99를 어떻게 지킬까?',
      scenario: '낮은 우선순위 streaming이 queue depth를 모두 채워 뒤늦게 들어온 충돌 지형 read가 장치까지 제출되지 못한다.',
      concepts: ['priority inversion', 'backpressure', 'admission control', 'deadline'],
      labLabel: 'I/O queue를 speculative 작업으로 채우고 긴급 요청이 지나갈 통로 만들기',
      boundary: '애플리케이션 queue의 우선순위와 이미 장치 queue에 제출된 요청의 취소·재정렬 한계를 구분한다.',
      naive: '긴급 요청에 높은 priority 값만 붙이면 언제나 먼저 끝난다고 생각한다.',
      failure: '장치 queue가 낮은 우선순위 요청으로 가득 차면 높은 요청은 제출조차 못 하거나 깊은 queue 뒤에 갇힌다.',
      reasoning: '낮은 우선순위 작업의 admission을 제한하고 긴급 슬롯을 예약해야 우선순위가 실제 자원 배분으로 이어진다.',
      build: 'class별 queue와 token budget, reserved QD, deadline promotion을 두고 speculative producer에는 backpressure를 건다.',
      verify: '최악의 streaming 부하에서 critical p50/p99, starvation, 장치 utilization과 취소 낭비를 측정한다.',
      trade: '예약 용량은 긴급 요청이 없을 때 utilization을 낮출 수 있다. work-conserving borrow와 회수 규칙이 필요하다.',
      core: '우선순위는 숫자가 아니라 제한된 제출 자리와 처리 시간을 누가 먼저 차지하는지에 대한 정책이다.'
    },
    {
      id: 59, category: 'F',
      question: 'SSD 읽기는 끝났는데 texture가 한참 뒤 나타난다. I/O, 압축 해제, GPU upload 중 병목을 어떻게 분리할까?',
      scenario: '한 stage가 느리면 앞 queue가 차고 뒤 stage는 굶는다. 전체 로딩 시간 하나만 보면 어느 자원이 막혔는지 알 수 없다.',
      concepts: ['pipeline', 'Little’s Law', 'stage utilization', 'buffering'],
      labLabel: '세 단계 처리 시간을 조절해 queue가 어디에 쌓이는지 관찰하기',
      boundary: '요청 end-to-end latency와 각 stage의 service time·wait time을 구분한다.',
      naive: 'asset loading이 느리면 더 빠른 SSD나 더 많은 worker 중 하나를 감으로 추가한다.',
      failure: 'decompress가 병목인데 I/O QD를 늘리면 compressed buffer만 쌓여 메모리와 tail latency가 악화된다.',
      reasoning: '각 stage의 arrival, start, finish를 추적하고 가장 느린 지속 처리율 앞에 queue가 성장하는지 본다.',
      build: 'bounded stage queue와 독립 executor를 두고 telemetry로 worker 수와 batch 크기를 조절한다. GPU frame budget도 stage capacity로 취급한다.',
      verify: 'stage별 utilization, queue length, wait/service histogram, bytes in flight를 시간축으로 기록한다.',
      trade: 'buffer를 늘리면 짧은 burst는 흡수하지만 지속 병목은 숨기며 메모리만 쓴다. capacity는 측정 기반으로 제한한다.',
      core: 'pipeline 최적화는 전체 시간을 한 숫자로 보는 것이 아니라 일이 기다리기 시작한 stage를 찾는 과정이다.'
    },
    {
      id: 60, category: 'F',
      question: '전투 중 replay·screenshot·log 저장이 몰리자 프레임이 멎는다. 생산 속도가 저장 속도를 넘을 때 무엇을 버릴 것인가?',
      scenario: '무제한 queue는 RAM을 먹고, queue가 찼을 때 game thread가 block하면 hitch가 생긴다. 모든 데이터의 손실 비용은 같지 않다.',
      concepts: ['bounded queue', 'backpressure', 'drop policy', 'quality degradation'],
      labLabel: '생산량과 저장량을 바꿔 queue 포화 뒤의 정책별 결과 비교하기',
      boundary: '반드시 보존할 데이터, 최신 것만 필요한 데이터, 품질을 낮춰도 되는 데이터를 분류한다.',
      naive: '비동기 thread에 넘기면 game thread와 무관하므로 queue는 무제한이어도 된다고 생각한다.',
      failure: 'consumer보다 producer가 지속적으로 빠르면 backlog는 끝없이 증가한다. bounded queue의 block 정책은 결국 producer인 game thread를 멈춘다.',
      reasoning: '유한 buffer에서 overload는 피할 수 없으므로 데이터 종류별로 drop-oldest, drop-newest, sampling, 품질 축소, producer throttle을 명시해야 한다.',
      build: 'critical save는 별도 journal, replay는 시간 window ring, screenshot은 최신 요청 하나, log는 level sampling으로 나눈다.',
      verify: '지속 overload와 burst에서 game-thread block time, queue age, drop 수, 복구 가능성과 메모리 상한을 확인한다.',
      trade: '손실 정책은 관측성과 사용자 기대를 훼손할 수 있다. 숨기지 말고 metric과 UI 상태로 드러내야 한다.',
      core: '비동기는 용량을 만들지 않는다. 생산률이 소비률을 넘으면 기다림·메모리·손실 중 무엇을 지불할지 선택해야 한다.'
    }
  );
})();
