(function(){
  'use strict';
  const q=[
    {
      id:11,category:'B',
      question:'몬스터 1,000마리의 상태 분기를 없앴는데 오히려 AI tick이 느려졌다. 분기는 정말 비싼가?',
      scenario:'Alive·Stunned·Dead 상태별 `if`를 수학식과 mask 연산으로 바꿨다. branch 수는 줄었지만 모든 몬스터가 불필요한 경로 계산까지 수행해 프레임 시간이 늘었다.',
      concepts:['branch prediction','misprediction','speculation','branchless'],
      labLabel:'몬스터 상태 분포를 바꿔 분기와 mask 비용 비교하기',
      boundary:'분기 명령 수가 아니라 실제 상태 분포의 예측 가능성과 각 경로의 작업량을 본다. 무작위 데이터인지, 상태별로 정렬돼 긴 run을 이루는지도 결과를 바꾼다.',
      naive:'분기 하나는 pipeline을 깨므로 조건문을 모두 제거하면 빨라진다고 가정한다.',
      failure:'예측 가능한 분기는 거의 공짜에 가깝지만 branchless 코드는 선택되지 않은 경로도 계산한다. pathfinding처럼 한 경로가 비싸면 몇 번의 misprediction보다 낭비가 훨씬 크다.',
      reasoning:'CPU는 이전 패턴으로 다음 분기를 추측해 명령을 미리 실행한다. 틀리면 speculative work를 버리고 pipeline을 다시 채운다. 비용은 분기 존재가 아니라 오예측률×복구 비용과 branchless 추가 연산의 비교다.',
      build:'상태별 entity를 batch로 묶어 분기를 예측 가능하게 만들고 비싼 작업은 실제 대상만 job으로 생성한다. 단순 clamp·min처럼 양쪽 계산이 싼 곳에서만 branchless를 고려한다.',
      verify:'branch instruction·mispredict counter, retired instruction, AI별 작업 수를 함께 측정한다. 균일·90/10·무작위·상태 정렬 데이터로 benchmark해 실제 콘텐츠 분포와 비교한다.',
      trade:'상태별 재배치는 cache locality를 높이지만 entity 이동과 디버깅 복잡도를 만든다. 작은 데이터에서는 단순한 분기가 유지보수와 성능 모두 더 나을 수 있다.',
      core:'분기가 비싼 것이 아니라 틀린 예측과 불필요하게 실행한 일이 비싸다.'
    },
    {
      id:12,category:'B',
      question:'같은 100만 번의 탐색인데 연속한 타일은 빠르고 무작위 타일은 수십 배 느리다. CPU는 무엇을 기다릴까?',
      scenario:'내비게이션 heatmap을 배열 앞에서부터 계산하면 빠르지만 랜덤 waypoint 순서로 조회하면 ALU 사용률이 낮은데도 실행 시간이 급증한다.',
      concepts:['cache hierarchy','cache line','spatial locality','memory latency'],
      labLabel:'연속·stride·무작위 접근의 cache line 이동 관찰하기',
      boundary:'알고리즘의 조회 횟수와 실제로 가져오는 cache line 수를 분리한다. working set이 어느 cache에 들어가는지와 한 번 가져온 64바이트에서 몇 값을 쓰는지 확인한다.',
      naive:'배열 인덱스 접근은 모두 O(1)이므로 100만 번이면 순서와 관계없이 비슷하다고 본다.',
      failure:'cache miss는 수백 cycle 동안 메모리를 기다리게 한다. 무작위 접근은 한 line의 값 하나만 사용하고 다음 위치를 예측하기 어려워 hardware prefetcher도 숨기지 못한다.',
      reasoning:'CPU 성능은 연산 수뿐 아니라 데이터를 제때 공급할 수 있는가에 달려 있다. 순차 접근은 line 안의 여러 원소를 재사용하고 다음 line을 미리 가져오지만 pointer chasing과 random index는 지연을 직렬화한다.',
      build:'계산 순서를 tile·chunk 단위로 재배열하고 함께 쓰는 데이터를 연속 배치한다. 무작위 요청은 정렬·batch하거나 독립 요청을 여러 개 발행해 memory-level parallelism을 확보한다.',
      verify:'L1/L2/LLC miss, memory bandwidth, cycles stalled on memory를 측정한다. working set과 stride를 sweep해 cache 크기 경계에서 지연이 계단식으로 변하는지 본다.',
      trade:'요청 정렬은 locality를 높이지만 원래 순서 보존과 대기 시간이 필요하다. 실시간 우선순위가 locality보다 중요한 작업은 작은 hot cache를 별도로 둘 수 있다.',
      core:'O(1) 접근도 데이터가 CPU 가까이에 없으면 수백 cycle짜리 대기가 된다.'
    },
    {
      id:13,category:'B',
      question:'물리 worker들이 서로 다른 카운터만 올리는데 코어를 늘릴수록 느려진다. 누가 같은 데이터를 건드리는가?',
      scenario:'각 worker는 자기 충돌 횟수를 `atomic<uint64_t>`에 기록한다. 변수 주소는 서로 다르지만 8코어부터 cache coherence traffic이 급증하고 처리량이 떨어진다.',
      concepts:['false sharing','cache coherence','cache line ownership','per-thread aggregation'],
      labLabel:'카운터 간격을 바꿔 cache line ping-pong 재현하기',
      boundary:'소스 코드의 변수 단위가 아니라 하드웨어가 일관성을 관리하는 cache line 단위로 공유를 본다. 읽기 공유와 여러 코어의 쓰기 공유도 구분한다.',
      naive:'스레드마다 별도 atomic 변수를 줬으므로 lock 경합이 없다고 판단한다.',
      failure:'서로 다른 카운터가 같은 line에 있으면 한 코어의 쓰기가 다른 코어 cache의 line 전체를 무효화한다. 소유권이 코어 사이를 왕복하며 실제 값 충돌 없이도 직렬화된다.',
      reasoning:'coherence protocol은 바이트가 아니라 line의 소유 상태를 추적한다. 독립적인 write-hot 데이터는 line까지 분리해야 하며 atomic 여부는 false sharing을 없애지 않는다.',
      build:'worker 통계를 cache-line aligned 구조로 분리하거나 완전히 thread-local에 누적한 뒤 프레임 말에 한 번 reduce한다. read-mostly 데이터와 write-hot 카운터도 구조체에서 분리한다.',
      verify:'cache-to-cache transfer, HITM, coherence stall과 scaling curve를 본다. 카운터 간격을 8→64→128바이트로 바꿔 처리량 변화가 line 경계와 일치하는지 확인한다.',
      trade:'padding은 메모리를 늘리고 많은 카운터를 순회할 때 locality를 낮춘다. hot write 경로만 분리하고 cold 통계는 조밀하게 유지해야 한다.',
      core:'동시성의 공유 단위는 변수가 아니라 하드웨어 cache line일 수 있다.'
    },
    {
      id:14,category:'B',
      question:'파티클 계산을 SIMD 8개씩 처리했는데 FPS가 거의 오르지 않는다. 벡터 연산은 어디에서 멈췄을까?',
      scenario:'scalar update를 AVX vector code로 바꿔 산술 명령 수는 크게 줄었다. profiler에서는 CPU 사용률이 높지만 particle 수를 늘릴수록 메모리 bandwidth만 포화된다.',
      concepts:['SIMD','arithmetic intensity','memory bandwidth','roofline'],
      labLabel:'연산량과 대역폭 한계를 바꿔 SIMD의 실제 상한 보기',
      boundary:'한 원소당 읽고 쓰는 바이트와 수행하는 연산 수를 계산한다. compute-bound인지 bandwidth-bound인지에 따라 SIMD의 기대 효과가 달라진다.',
      naive:'8-wide SIMD면 같은 시간에 8개를 처리하므로 8배 빨라질 것으로 예상한다.',
      failure:'데이터를 메모리에서 가져오는 속도가 이미 상한이면 ALU를 넓혀도 공급량은 늘지 않는다. gather·scatter와 AoS shuffle 비용이 vector 이득을 소비할 수도 있다.',
      reasoning:'성능 상한은 계산 peak와 memory bandwidth 중 낮은 쪽이다. arithmetic intensity가 낮은 kernel은 roofline의 bandwidth 구간에 있으므로 압축·재사용·배치가 먼저다.',
      build:'position·velocity 등 hot field를 SoA로 배치하고 여러 단계 연산을 fuse해 한 번 읽은 데이터를 register에서 재사용한다. 불필요한 field write와 정밀도를 줄인 뒤 SIMD를 적용한다.',
      verify:'IPC, vector instruction 비율, load/store bytes, bandwidth와 cache miss를 측정한다. 데이터가 cache에 들어가는 작은 규모와 DRAM 규모를 나눠 속도 향상을 비교한다.',
      trade:'SoA와 kernel fusion은 시스템 간 데이터 접근을 어렵게 하고 부분 업데이트 비용을 바꾼다. particle처럼 대량 균일 데이터에는 유리하지만 복잡한 gameplay 객체 전체에 강제하면 안 된다.',
      core:'SIMD는 계산 폭을 넓힐 뿐이며 데이터를 공급하는 통로까지 넓혀주지는 않는다.'
    },
    {
      id:15,category:'B',
      question:'컴포넌트를 잘게 나눴더니 기능은 깔끔해졌지만 update 호출만으로 프레임이 무너진다. 호출 비용이 원인일까?',
      scenario:'수만 entity가 여러 virtual component의 `Update()`를 호출한다. 함수 하나는 작지만 구현 주소가 제각각이고 실행 코드가 cache에 머물지 못한다.',
      concepts:['indirect branch','instruction cache','BTB','code locality'],
      labLabel:'컴포넌트 순서를 섞고 묶으며 명령 흐름 관찰하기',
      boundary:'virtual call 자체의 몇 cycle과 호출 뒤 실행할 코드가 instruction cache에 있는지를 나눈다. 구현 종류 수, 호출 순서, 함수 크기가 핵심 입력이다.',
      naive:'가상 함수의 vtable lookup 하나가 느리므로 `switch` 또는 CRTP로 바꾸면 해결된다고 본다.',
      failure:'간접 분기 target이 계속 바뀌면 branch target predictor가 실패하고 서로 다른 구현 코드가 I-cache를 밀어낸다. 문법만 정적 호출로 바꿔도 호출 순서가 무작위면 locality 문제는 남는다.',
      reasoning:'CPU는 데이터뿐 아니라 다음에 실행할 명령도 cache와 predictor에서 가져온다. 같은 타입을 연속 처리하면 target과 코드가 재사용되지만 entity별 heterogeneous 순회는 frontend를 굶긴다.',
      build:'update phase별·component type별로 dense collection을 만들고 같은 코드를 batch 실행한다. hot update를 작은 kernel로 유지하고 드문 기능은 cold path로 분리한다.',
      verify:'I-cache miss, iTLB miss, indirect branch mispredict와 frontend stall을 측정한다. 호출 방식을 바꾸기 전 entity-order와 type-batch만 바꿔 원인 기여도를 분리한다.',
      trade:'type별 batch는 객체 단위 흐름을 읽기 어렵게 하고 구조 변경 비용이 있다. 개수가 적은 고수준 객체는 다형성이 더 명료하며 hot 대량 루프만 재배치하는 것이 현실적이다.',
      core:'작은 함수 호출 수보다 CPU가 다음 실행 코드와 분기 대상을 예측할 수 있는지가 중요하다.'
    },
    {
      id:16,category:'B',
      question:'오픈월드 스트리밍에 prefetch를 넣었더니 메모리 stall이 더 늘었다. 미리 가져오면 왜 손해일까?',
      scenario:'다음 terrain chunk를 software prefetch하도록 했지만 카메라가 방향을 바꾸면 쓰지 않을 데이터가 cache를 채우고 현재 chunk의 hot data를 밀어낸다.',
      concepts:['hardware prefetch','software prefetch','lead distance','cache pollution'],
      labLabel:'카메라 방향과 prefetch 거리를 바꿔 적중·오염 균형 찾기',
      boundary:'접근 패턴을 hardware prefetcher가 이미 처리하는지, 미래 주소를 얼마나 정확히 알고 얼마나 뒤에 사용할지 확인한다. prefetch는 메모리 용량이 아니라 제한된 cache 공간을 사용한다.',
      naive:'필요할 가능성이 있는 chunk를 최대한 일찍 모두 prefetch한다.',
      failure:'너무 늦으면 demand miss를 숨기지 못하고 너무 이르면 사용 전에 eviction된다. 잘못 예측한 데이터는 bandwidth와 cache를 소비해 현재 작업까지 느리게 한다.',
      reasoning:'좋은 prefetch는 latency만큼 앞서 있으면서 사용 확률이 높고 다른 hot line을 밀어내지 않아야 한다. 정확도·적시성·coverage를 함께 봐야 한다.',
      build:'카메라 속도와 chunk 처리 시간을 이용해 제한된 lookahead를 계산하고 방향 확률이 낮으면 낮은 cache priority 또는 비동기 I/O 힌트만 준다. 순차 배열은 hardware prefetcher에 맡긴다.',
      verify:'prefetch issued/useful/late, bandwidth, LLC occupancy와 eviction을 측정한다. 급회전·순간이동·정속 이동 scenario별로 hit와 pollution을 분리한다.',
      trade:'동적 예측은 복잡하고 플랫폼마다 prefetch 명령 효과가 다르다. 레이아웃을 순차화하는 근본 개선이 가능하면 수동 힌트보다 먼저 적용한다.',
      core:'prefetch는 공짜 선행 로드가 아니라 미래 확률을 걸고 cache와 bandwidth를 미리 소비하는 선택이다.'
    },
    {
      id:17,category:'B',
      question:'NPC 객체 하나에 모든 정보를 모았더니 이동 업데이트가 메모리를 계속 낭비한다. 데이터를 어떻게 찢을까?',
      scenario:'NPC 구조체에는 transform, AI tree, inventory, dialogue, cosmetic 데이터가 함께 있다. 이동 시스템은 position과 velocity만 쓰지만 NPC마다 여러 cache line을 가져온다.',
      concepts:['AoS','SoA','hot/cold split','data-oriented design'],
      labLabel:'NPC 배치를 AoS·SoA로 바꿔 가져온 바이트 대비 사용량 보기',
      boundary:'“객체가 무엇인가”보다 각 시스템이 같은 시간에 어떤 field를 함께 쓰는지 조사한다. 읽기 빈도와 함께 갱신되는 field 집합이 물리 배치를 결정한다.',
      naive:'코드 응집도를 위해 NPC의 모든 상태를 하나의 큰 구조체에 둔다.',
      failure:'cache는 필요한 멤버만 가져오지 않고 주변 line 전체를 가져온다. hot loop가 inventory와 문자열을 함께 운반하고 다음 NPC의 hot field가 멀어 prefetch 효율도 낮다.',
      reasoning:'AoS는 개별 객체의 여러 속성을 함께 볼 때 좋고 SoA는 동일 속성을 대량 처리할 때 좋다. 실제 엔진은 hot component는 dense SoA, 객체 identity와 cold data는 별도 저장하는 혼합형이 된다.',
      build:'transform·velocity를 연속 component array로 이동하고 AI·inventory·cosmetic은 handle로 연결한다. phase별 query가 필요한 component 조합을 chunk 단위로 제공하도록 archetype 또는 sparse-set을 구성한다.',
      verify:'업데이트당 useful bytes/cache-line bytes 비율, cache miss, bandwidth를 측정한다. entity 추가·삭제와 여러 component 조합 query 비용도 함께 benchmark한다.',
      trade:'SoA는 객체 하나를 디버깅하거나 직렬화할 때 여러 저장소를 따라가야 한다. 모든 시스템을 한 레이아웃에 맞추지 말고 가장 비싼 access pattern을 우선한다.',
      core:'데이터의 물리적 이웃은 클래스 관계가 아니라 함께 계산되는 시간적 관계가 정한다.'
    },
    {
      id:18,category:'B',
      question:'월드 데이터가 특정 크기를 넘는 순간 탐색 시간이 계단처럼 뛴다. cache miss만 보면 충분할까?',
      scenario:'큰 sparse voxel 배열을 순회할 때 데이터가 수 GB를 넘자 LLC miss 증가보다 더 큰 지연이 생겼다. huge page를 사용하면 코드는 그대로인데 성능이 회복된다.',
      concepts:['virtual address translation','TLB','page walk','huge page'],
      labLabel:'페이지 크기와 stride를 바꿔 TLB 도달 범위 계산하기',
      boundary:'데이터 line을 찾는 cache와 가상 주소를 물리 주소로 번역하는 TLB를 분리한다. 접근하는 page 수와 한 page 안에서의 재사용을 본다.',
      naive:'모든 지연을 data cache miss로 보고 prefetch와 cache 크기만 조정한다.',
      failure:'각 load는 주소 번역도 필요하다. working set의 page 수가 TLB entry를 넘고 접근이 sparse하면 page table walk가 반복되어 cache hit인 데이터도 늦게 도착할 수 있다.',
      reasoning:'TLB reach는 entry 수×page 크기다. huge page는 같은 entry로 더 넓은 주소를 덮어 translation miss를 줄이지만 내부 단편화와 할당 제약을 만든다.',
      build:'연속 arena와 page-local chunk 배치로 동시 활성 page 수를 줄인다. 장수명 대규모 데이터에는 OS 지원을 확인해 huge page를 선택적으로 사용하고 small allocation과 섞지 않는다.',
      verify:'dTLB miss, page walk cycles, minor fault를 측정한다. page 수와 stride를 독립적으로 sweep하고 4KB·2MB page에서 변곡점을 비교한다.',
      trade:'huge page는 메모리 낭비, 초기화 지연, 권한·플랫폼 제약이 있다. 나쁜 무작위 레이아웃을 숨기는 만능 해결책이 아니라 안정된 큰 working set에 제한해야 한다.',
      core:'메모리 접근은 데이터를 찾는 일과 그 주소를 번역하는 두 개의 cache 문제다.'
    },
    {
      id:19,category:'B',
      question:'게임 스레드가 코어 하나를 100% 쓰는데 실제 완료 명령은 적다. CPU는 바쁜가, 기다리는가?',
      scenario:'task manager는 game thread 100%를 보여주지만 tick 처리량은 낮다. clock을 올려도 개선이 작고 profiler의 가장 큰 함수도 명확하지 않다.',
      concepts:['IPC','pipeline stall','frontend/backend bound','top-down analysis'],
      labLabel:'명령 공급·메모리·분기 병목을 섞어 CPU slot 분해하기',
      boundary:'스케줄러가 코어를 점유했다는 사실과 CPU 실행 unit을 유용하게 사용했다는 사실을 구분한다. elapsed time·cycles·retired work를 함께 봐야 한다.',
      naive:'CPU 사용률 100%이므로 계산량이 너무 많다고 보고 함수 몇 개의 산술을 줄인다.',
      failure:'cache miss 대기, 잘못된 분기, instruction 공급 부족도 스레드를 runnable 상태로 유지한다. 사용률은 높아도 pipeline slot 대부분이 stall일 수 있다.',
      reasoning:'top-down 방식은 slot을 retiring, bad speculation, frontend bound, backend bound로 나눈다. backend는 다시 core execution과 memory bound로 좁혀 다음 실험을 정한다.',
      build:'먼저 hardware counter로 병목 계층을 분류한 뒤 원인에 맞게 데이터 배치·batch·분기·코드 크기를 바꾼다. 최적화 전후 동일 gameplay work가 완료됐는지도 확인한다.',
      verify:'IPC, cycles, instructions retired, frontend/backend stall, branch miss, cache miss와 tick당 작업 수를 한 run ID로 수집한다. 단일 함수 시간만으로 결론내지 않는다.',
      trade:'counter 해석은 CPU 세대와 플랫폼에 따라 다르고 sampling 자체에도 비용이 있다. 깊은 계측은 재현 가능한 대표 구간에 집중한다.',
      core:'CPU 사용률은 점유율이고 처리량은 유용한 완료량이다. 둘 사이를 pipeline stall이 설명한다.'
    },
    {
      id:20,category:'B',
      question:'가장 느린 애니메이션 함수가 2배 빨라졌는데 전체 프레임은 3%만 줄었다. 다음 최적화는 어디인가?',
      scenario:'profiler 상위 함수 하나가 2ms를 차지해 집중 최적화했다. 함수는 1ms가 됐지만 16.6ms 프레임 전체에서 개선은 기대보다 작고 다른 병목이 바로 올라왔다.',
      concepts:['Amdahl 법칙','critical path','parallel slack','bottleneck migration'],
      labLabel:'함수 비중과 개선 배율을 바꿔 전체 프레임 상한 계산하기',
      boundary:'함수의 자체 시간과 프레임 critical path 기여도를 구분한다. worker에서 실행돼 다른 작업과 겹치는지, 메인 스레드가 기다리는 구간인지도 확인한다.',
      naive:'profiler에서 가장 큰 함수를 가능한 한 많이 빠르게 만든다.',
      failure:'전체 중 작은 비율만 개선하면 무한히 빠르게 해도 나머지 시간이 하한이다. 병렬 worker의 self time은 줄어도 critical path가 아니면 프레임 완료 시각이 바뀌지 않는다.',
      reasoning:'Amdahl의 법칙은 개선 가능한 비율이 전체 speedup을 제한한다고 말한다. 프레임에서는 task dependency와 overlap까지 포함한 critical path가 실제 직렬 비율이다.',
      build:'frame timeline과 dependency graph에서 완료 시각을 미는 작업을 찾는다. 작은 micro-optimization보다 sync point 제거·작업 겹치기·빈도 낮추기를 포함해 critical path 자체를 재구성한다.',
      verify:'전후 frame total, critical path, task slack, p50·p95·p99를 비교한다. 기능 결과와 작업량이 같은지도 검증해 일을 생략한 가짜 개선을 막는다.',
      trade:'큰 구조 변경은 위험이 높고 마감 직전에는 1ms 확정 개선이 더 가치 있을 수 있다. 최적화 상한과 구현 위험을 함께 제시해 선택한다.',
      core:'가장 오래 실행된 코드가 아니라 프레임 완료 시각을 실제로 늦추는 경로를 최적화해야 한다.'
    }
  ];
  window.CSInterviewData.questions.push(...q);
})();
