(function () {
  'use strict';
  window.CSInterviewData.questions.push(
    {
      id: 71, category: 'H',
      question: '매 frame 모든 projectile을 순회하는데 삽입·삭제가 빠른 linked list가 contiguous vector보다 느리다. Big-O가 같은 순회에서 무엇이 빠졌나?',
      scenario: 'list node는 heap 곳곳에 흩어져 pointer를 따라가고 vector는 인접 projectile을 cache line과 hardware prefetch로 가져온다.',
      concepts: ['data locality', 'pointer chasing', 'cache line', 'amortized complexity'],
      labLabel: '같은 projectile 수를 vector와 list에 배치해 cache-line 이동 비교하기',
      boundary: '연산 횟수를 세는 점근 복잡도와 각 메모리 접근의 실제 지연·예측 가능성을 구분한다.',
      naive: '둘 다 O(n) 순회이고 list는 erase O(1)이므로 list가 더 적합하다고 결론낸다.',
      failure: 'node마다 cache miss와 allocator metadata를 지불하며 next pointer가 와야 다음 주소를 알아 prefetch가 어렵다.',
      reasoning: 'frame마다 전체를 읽는 빈도가 mutation보다 훨씬 크면 dense storage의 순회 locality가 erase 이동 비용을 압도한다.',
      build: 'swap-remove 가능한 dense vector와 stable ID→index indirection을 사용하고 순서가 필요하면 tombstone·batch compaction을 고려한다.',
      verify: 'wall time뿐 아니라 LLC miss, bytes/entity, allocator 호출, 실제 spawn/despawn 비율로 비교한다.',
      trade: 'dense vector는 주소 안정성과 순서를 잃을 수 있다. handle과 generation으로 외부 참조를 분리한다.',
      core: '자료구조 선택은 연산의 Big-O 표가 아니라 게임 workload에서 가장 자주 건드리는 bytes의 배치로 결정된다.'
    },
    {
      id: 72, category: 'H',
      question: '플레이어 ID hash map 조회가 평소엔 빠른데 특정 입력에서 frame 전체를 먹는다. 평균 O(1) 뒤에 어떤 조건이 숨어 있는가?',
      scenario: '낮은 품질 hash와 공격자가 고른 ID가 같은 bucket에 몰리고 rehash가 한 frame에 실행된다.',
      concepts: ['hash collision', 'load factor', 'rehash', 'adversarial input'],
      labLabel: 'ID 분포와 load factor를 바꿔 bucket chain과 rehash spike 만들기',
      boundary: '균일한 hash 가정의 기대 복잡도, 최악 복잡도, resize의 amortized 비용을 나눈다.',
      naive: 'unordered_map은 항상 배열 index처럼 O(1)이므로 입력 분포를 보지 않는다.',
      failure: 'collision chain이 길어지면 조회가 O(n)에 가까워지고 capacity를 넘는 순간 전체 element 이동이 한 tick에 몰린다.',
      reasoning: '신뢰할 수 없는 key에는 강한 seeded hash와 capacity budget을 두고 실시간 경로에서는 reserve·incremental rehash를 고려한다.',
      build: '최대 player 수로 reserve하고 bucket probe histogram·load factor를 노출한다. key가 dense하면 flat array나 sorted vector도 검토한다.',
      verify: '균일·순차·충돌·공격 입력에서 p99 probe와 rehash 시간을 측정한다.',
      trade: '낮은 load factor는 메모리를 쓰고 강한 hash는 CPU를 쓴다. 공격면과 frame budget에 맞춘다.',
      core: '평균 O(1)은 hash 분포와 resize 비용이 통제된다는 가정이며 실시간 시스템은 그 가정을 측정하고 제한해야 한다.'
    },
    {
      id: 73, category: 'H',
      question: 'A* open set에서 더 짧은 경로를 찾을 때 priority_queue의 기존 항목을 수정할 수 없다. 삭제를 찾느라 O(n)을 쓰지 않고 어떻게 처리할까?',
      scenario: '같은 node가 여러 f-score로 heap에 들어가고 pop 시점에 최신 거리인지 검증하지 않으면 오래된 경로를 확정한다.',
      concepts: ['binary heap', 'decrease-key', 'lazy deletion', 'invariant'],
      labLabel: '같은 node의 새 거리와 stale heap entry를 넣고 pop 검증하기',
      boundary: 'heap top 최소값 invariant와 특정 element를 찾는 기능이 기본 priority_queue에 없다는 사실을 구분한다.',
      naive: 'heap 배열을 선형 탐색해 기존 node를 찾아 수정한 뒤 매번 전체 heap을 다시 만든다.',
      failure: '검색 O(n)이 탐색 전체를 지배하거나 stale entry를 그대로 확정해 잘못된 경로를 만든다.',
      reasoning: '새 `(distance,node)`를 push하고 pop한 distance가 현재 best와 다르면 버리면 heap invariant를 유지하며 lazy decrease-key가 된다.',
      build: 'best-distance array/map과 parent를 별도 보유하고 duplicate ratio가 높으면 indexed heap으로 교체한다.',
      verify: '모든 edge relaxation 뒤 heap property, pop된 유효 거리의 단조성, stale 비율과 peak memory를 검사한다.',
      trade: 'lazy 방식은 구현이 단순하지만 duplicate memory와 pop 비용이 늘 수 있다. graph 특성에 따라 indexed heap과 비교한다.',
      core: '자료구조가 직접 제공하지 않는 연산은 불변식을 보존하는 다른 표현으로 바꾸고 추가 비용을 측정해야 한다.'
    },
    {
      id: 74, category: 'H',
      question: '근접 충돌 broad phase의 uniform grid cell을 작게 하면 빨라질까? 거대한 boss와 작은 탄환이 섞일 때 어떤 비용이 교차하는가?',
      scenario: '작은 cell은 탄환 후보를 줄이지만 큰 object가 많은 cell에 중복 등록되고 이동 때 갱신 비용이 커진다.',
      concepts: ['spatial hashing', 'cell size', 'broad phase', 'duplication'],
      labLabel: 'cell 크기와 object 크기를 바꿔 후보 pair와 중복 등록 수 비교하기',
      boundary: '실제 충돌 narrow phase 비용과 broad phase가 만드는 후보·index 갱신 비용을 구분한다.',
      naive: 'cell이 작을수록 같은 cell의 object가 줄어 무조건 좋다고 본다.',
      failure: '큰 object가 수십 cell에 들어가 duplicate pair 제거와 insert/update가 폭증한다. 너무 큰 cell은 후보 pair가 제곱으로 늘어난다.',
      reasoning: 'object 크기 분포와 query 반경에 맞춘 cell size를 선택하고 크기 차이가 크면 loose grid·계층 구조를 섞는다.',
      build: 'small dynamic은 fine grid, giant는 별도 BVH/list에 두고 query 결과에서 stable pair key로 중복 제거한다.',
      verify: '분포별 cell touches, candidate/true-hit 비율, update cost와 p99 frame을 기록한다.',
      trade: '계층 구조는 구현·메모리·동기화가 복잡해진다. 실제 크기 분포가 단순하면 uniform grid가 더 낫다.',
      core: '공간 분할의 해상도는 후보 수와 index 중복·갱신 비용을 서로 바꾸는 파라미터다.'
    },
    {
      id: 75, category: 'H',
      question: '이동 칸 수가 가장 적은 경로가 늪 때문에 가장 느리다. BFS, Dijkstra, A* 중 무엇을 선택하고 heuristic은 어떤 계약을 지켜야 하나?',
      scenario: '지형마다 이동 비용이 다르고 목표까지의 직선거리를 과대평가하는 heuristic을 쓰면 최적 경로 보장이 깨질 수 있다.',
      concepts: ['BFS', 'Dijkstra', 'A*', 'admissible heuristic'],
      labLabel: '지형 비용과 heuristic 배율을 바꿔 확장 node와 선택 경로 비교하기',
      boundary: 'edge 수 최소와 weight 합 최소를 구분하고, 빠른 탐색과 최적성 보장을 분리한다.',
      naive: 'grid이므로 BFS를 쓰거나 heuristic을 크게 할수록 A*가 더 좋아진다고 생각한다.',
      failure: 'BFS는 weight를 무시하고 과대 heuristic은 아직 싼 경로를 탐색하기 전에 비싼 직선 경로를 확정할 수 있다.',
      reasoning: 'nonnegative weight면 Dijkstra가 기준이고 admissible·consistent heuristic을 더하면 A*가 최적성을 보존하며 탐색을 줄인다.',
      build: '최소 terrain cost를 곱한 Manhattan/Euclidean heuristic을 사용하고 의도적 근사면 weighted A*의 품질 한계를 명시한다.',
      verify: '작은 map은 exhaustive 기준 해와 cost를 비교하고 random map에서 expanded node·path cost 분포를 본다.',
      trade: '강한 admissible heuristic 계산 자체가 비쌀 수 있고 dynamic cost에서는 재탐색 알고리즘이 필요하다.',
      core: '경로 알고리즘 선택은 그래프의 weight 계약과 허용 가능한 최적성·탐색 비용에서 출발한다.'
    },
    {
      id: 76, category: 'H',
      question: '섬 연결 여부를 union-find로 빠르게 답했는데 다리가 파괴되자 여전히 연결됐다고 나온다. 무엇을 되돌릴 수 없는 구조인가?',
      scenario: 'union은 component를 합치지만 일반적인 DSU는 어떤 edge 때문에 합쳐졌는지 보존하지 않아 online delete를 처리하지 못한다.',
      concepts: ['disjoint set union', 'path compression', 'dynamic connectivity', 'offline algorithm'],
      labLabel: '다리를 추가·파괴하며 DSU의 merge 전용 성질 확인하기',
      boundary: 'edge 추가만 있는 incremental connectivity와 삭제까지 있는 fully dynamic 문제를 구분한다.',
      naive: '다리를 지울 때 해당 두 node의 parent pointer만 원래대로 돌리면 된다고 생각한다.',
      failure: 'path compression으로 여러 경로가 납작해지고 다른 edge가 우회 연결을 제공할 수도 있어 한 pointer로 분리할 수 없다.',
      reasoning: '삭제 빈도와 query 패턴에 따라 삭제 후 BFS rebuild, rollback DSU를 쓴 offline 시간 분할, 동적 트리 구조를 선택한다.',
      build: '게임에서 파괴가 드물면 dirty component만 flood fill해 새 ID를 부여하고 추가는 DSU로 처리하는 hybrid가 단순하다.',
      verify: 'random add/delete sequence를 매번 BFS ground truth와 비교하고 rebuild 범위·latency를 측정한다.',
      trade: '고급 fully dynamic 구조는 이론적 성능 대신 구현·상수·디버깅 비용이 크다.',
      core: '빠른 연산 하나가 반대 연산도 지원한다는 뜻은 아니며 mutation 종류가 자료구조의 핵심 계약이다.'
    },
    {
      id: 77, category: 'H',
      question: '네트워크 replay ring buffer가 counter wrap 근처에서 empty와 full을 혼동한다. head와 tail의 나머지만 저장하면 어떤 정보가 사라지는가?',
      scenario: '둘 다 index 3이어도 한 번도 쓰지 않은 empty와 capacity만큼 앞선 full이 같은 물리 위치를 가진다.',
      concepts: ['ring buffer', 'monotonic counter', 'wraparound', 'power of two'],
      labLabel: 'head·tail을 원형으로 이동해 같은 index의 empty/full 상태 구분하기',
      boundary: '물리 array index와 생산·소비 진행량을 나타내는 논리 sequence를 구분한다.',
      naive: '`head == tail`이면 항상 empty이고 `% capacity` index 두 개만으로 충분하다고 본다.',
      failure: '한 바퀴 차이 정보가 사라져 full과 empty가 동일하게 보이고 counter overflow 비교도 signed 방식이면 깨진다.',
      reasoning: '넓은 unsigned monotonic counter 차이로 size를 계산하고 실제 slot 접근 때만 mask를 적용한다.',
      build: 'power-of-two capacity, `index = seq & (capacity-1)`, `size = writeSeq-readSeq` 불변식을 둔다.',
      verify: '여러 wrap을 작은 counter로 강제해 empty/full/overwrite 정책과 producer-consumer 순서를 property test한다.',
      trade: '한 slot을 비워 구분하는 단순 설계는 capacity 하나를 잃지만 계약이 쉬울 수 있다.',
      core: 'ring의 index는 위치만 말하고 세대는 말하지 않으므로 진행량이나 별도 상태로 한 바퀴 정보를 보존해야 한다.'
    },
    {
      id: 78, category: 'H',
      question: '동일 priority 이벤트를 sort했더니 플랫폼마다 적용 순서가 달라 replay hash가 갈린다. “정렬됨”에 무엇이 부족한가?',
      scenario: 'comparator가 priority만 비교해 동등한 원소가 많고 unstable sort는 그들의 입력 순서를 보존할 의무가 없다.',
      concepts: ['strict weak ordering', 'stable sort', 'tie-breaker', 'determinism'],
      labLabel: '동일 priority 이벤트를 섞고 stable sort와 명시적 tie-break 비교하기',
      boundary: 'key에 따른 부분적 순서와 모든 실행에서 하나로 결정되는 total order를 구분한다.',
      naive: 'sort를 호출했으므로 같은 priority 안에서도 원래 또는 ID 순서가 자동 보장된다고 생각한다.',
      failure: '동등 element의 순서는 알고리즘·메모리 배치에 따라 바뀌고 comparator가 비추이적이면 sort 자체의 전제가 깨진다.',
      reasoning: '의미상 입력 순서를 보존해야 하면 stable sort를, 네트워크·replay 결정성이 필요하면 sequence/ID tie-break를 명시한다.',
      build: '`(priority, sourceTick, eventSeq)` lexicographic key를 만들고 comparator property를 테스트한다.',
      verify: '입력 permutation과 플랫폼을 바꿔 output key·simulation hash가 동일한지 확인한다.',
      trade: 'stable sort는 추가 memory나 다른 상수를 쓰며 total key는 디자인상 순서를 고정한다.',
      core: '결정적 정렬에는 “누가 앞인가”뿐 아니라 동등한 두 항목을 어떻게 처리할지까지 규칙으로 포함해야 한다.'
    },
    {
      id: 79, category: 'H',
      question: 'texture LRU cache를 순차 스캔 한 번 했더니 자주 쓰던 UI texture가 전부 쫓겨났다. 최근 사용이 곧 미래 가치인가?',
      scenario: '거대한 cutscene asset stream이 각 block을 한 번씩 touch하며 cache를 채워 hot working set을 scan pollution으로 밀어낸다.',
      concepts: ['LRU', 'cache pollution', 'working set', 'admission policy'],
      labLabel: 'hot 반복 접근 뒤 일회성 scan을 흘려 LRU와 보호 admission 비교하기',
      boundary: 'eviction 정책과 새 항목을 cache에 들일지 결정하는 admission 정책을 구분한다.',
      naive: '가장 오래 안 쓴 항목을 버리는 LRU가 모든 locality에 자연스럽게 최적이라고 생각한다.',
      failure: 'capacity보다 큰 one-pass scan은 매 접근마다 기존 hot item을 버리고 scan item도 다시 쓰이지 않는다.',
      reasoning: '재사용 이력·빈도 또는 request class를 활용해 한 번 본 큰 stream이 protected hot set에 들어오지 못하게 한다.',
      build: 'probation/protected 두 segment, TinyLFU류 frequency sketch, streaming hint를 workload에 맞춰 사용한다.',
      verify: 'hot-loop+scan 혼합 trace에서 hit rate뿐 아니라 critical miss latency와 metadata 비용을 비교한다.',
      trade: '복잡한 admission은 metadata와 tuning 비용이 들며 workload 변화에 오판할 수 있다.',
      core: 'cache는 공간보다 미래 재사용 가능성을 배분하는 정책이며 recency 하나가 모든 게임 workload를 표현하지는 못한다.'
    },
    {
      id: 80, category: 'H',
      question: '매 frame 수십만 거리에서 가장 가까운 20개만 필요한데 전체 sort를 한다. 결과 전체가 필요하지 않을 때 어떻게 비용을 줄일까?',
      scenario: 'N개를 O(N log N)으로 정렬하지만 실제 소비자는 top K만 읽고 동점 규칙과 갱신 빈도도 따로 존재한다.',
      concepts: ['top-k', 'heap', 'selection', 'partial sort'],
      labLabel: 'N과 K를 바꿔 full sort·K heap·quickselect 작업량 비교하기',
      boundary: '모든 원소의 순서가 필요한지, K개 집합만 필요한지, K개 내부도 정렬돼야 하는지 구분한다.',
      naive: '표준 sort가 빠르고 단순하므로 데이터 크기와 K에 관계없이 항상 전체를 정렬한다.',
      failure: '버릴 N-K 원소 사이의 순서까지 계산해 CPU와 memory traffic을 소비한다.',
      reasoning: 'streaming 입력과 작은 K면 max-heap K개, 한 번의 배열이면 nth_element/quickselect 뒤 K만 정렬하는 방식을 비교한다.',
      build: '거리와 stable entity ID를 key로 두고 K·N·데이터 재사용에 따라 알고리즘을 선택한다.',
      verify: '비교 횟수, cache miss, allocation, worst-case input, 결과의 exact top-K·tie order를 검사한다.',
      trade: 'quickselect는 평균 선형이지만 최악과 입력 변형이 있고 heap은 K가 커질수록 log K 비용이 증가한다.',
      core: '필요한 출력 정보량을 먼저 줄이면 더 좋은 자료구조와 알고리즘 복잡도를 선택할 수 있다.'
    }
  );
})();
