(function(){
  'use strict';
  const categories=[
    {id:'A',short:'데이터',name:'데이터 표현과 결정성',range:'Q1–Q10'},
    {id:'B',short:'CPU',name:'CPU와 마이크로아키텍처',range:'Q11–Q20'},
    {id:'C',short:'메모리',name:'메모리와 가상 주소 공간',range:'Q21–Q30'},
    {id:'D',short:'운영체제',name:'프로세스·스레드·스케줄링',range:'Q31–Q40'},
    {id:'E',short:'동시성',name:'동시성과 병렬 게임 시스템',range:'Q41–Q50'},
    {id:'F',short:'I/O',name:'파일·저장장치·비동기 I/O',range:'Q51–Q60'},
    {id:'G',short:'도구체인',name:'컴파일러·링커·ABI',range:'Q61–Q70'},
    {id:'H',short:'알고리즘',name:'자료구조와 알고리즘의 실제 비용',range:'Q71–Q80'},
    {id:'I',short:'성능',name:'디버깅·프로파일링·성능 추론',range:'Q81–Q90'},
    {id:'J',short:'시스템 판단',name:'신뢰성·보안·시스템적 판단',range:'Q91–Q100'}
  ];
  const questions=[
    {
      id:1,category:'A',
      question:'상점의 골드가 커질수록 1골드 단위 결제가 사라진다. 숫자를 어떻게 표현해야 할까?',
      scenario:'초기에는 정상인 상점이 수억 골드를 가진 테스트 계정에서 이상해졌다. 100,000,000골드에 1골드를 더해도 UI와 서버 값이 바뀌지 않고, 할인 계산 순서에 따라 최종 가격도 달라진다.',
      concepts:['IEEE 754','유효 자릿수','고정소수점','overflow'],
      labLabel:'골드 원장을 직접 올려 정밀도 경계 찾기',
      boundary:'화폐에서 필요한 것은 넓은 범위, 정확한 최소 단위, 결정적인 반올림이다. 시각 효과의 연속값과 달리 1골드가 사라지거나 생성되는 오차는 허용할 수 없다. 최대 보유량·가격 계산 중간값·DB와 패킷 범위를 먼저 정한다.',
      naive:'모든 수치 시스템을 통일하기 쉽다는 이유로 골드도 32비트 float에 넣고, 화면에 표시할 때 정수로 반올림한다.',
      failure:'float는 값이 커질수록 인접한 표현 가능 수의 간격이 넓어진다. 어느 순간 1을 더해도 같은 비트 패턴이며, 곱셈과 나눗셈 순서가 달라지면 클라이언트·서버·로그의 결과가 갈라진다.',
      reasoning:'IEEE 754의 가수 비트 수가 상대 정밀도를 정한다. float는 약 2²⁴까지 모든 정수를 정확히 표현하지만 그 이후에는 2, 4, 8 단위로 건너뛴다. 화폐 문제는 “오차를 줄인다”가 아니라 “허용되지 않는 상태를 표현하지 못하게 한다”로 바꿔야 한다.',
      build:'최소 단위를 정수로 저장하고 계산은 overflow 여유가 있는 64비트에서 수행한다. 비율은 분자·분모 또는 명시적인 basis point로 표현하고 반올림 방향을 계약에 넣는다. 차감은 서버의 원자적 명령으로 처리하며 표시 문자열만 별도로 포맷한다.',
      verify:'경계값 0, 최대 보유량, 최대 가격×최대 수량, 할인 연쇄, 음수 차단을 property test한다. 동일 거래를 모든 지원 플랫폼에서 실행해 비트 단위 결과가 같은지 확인하고 overflow에는 조용한 wrap 대신 명시적 실패를 요구한다.',
      trade:'정수 표현도 단위와 최대 범위를 잘못 고르면 migration이 필요하다. 소수 화폐가 필요한 경제라면 최소 단위를 더 잘게 잡되 중간 계산 범위와 저장 비용을 함께 늘려야 한다.',
      core:'게임 화폐는 가까운 값이면 되는 측정치가 아니라 정확히 보존되어야 하는 불변식이다.'
    },
    {
      id:2,category:'A',
      question:'같은 리플레이를 PC와 콘솔에서 재생했는데 3분 뒤 차량 위치가 갈라진다. 무엇을 고정해야 할까?',
      scenario:'입력과 초기 위치, 랜덤 seed까지 저장한 레이싱 리플레이가 PC에서는 완주하지만 콘솔에서는 벽에 충돌한다. 처음 수백 프레임은 같고 오차는 아주 작게 시작해 접촉 이후 급격히 커진다.',
      concepts:['부동소수점 결정성','연산 순서','FMA','오차 증폭'],
      labLabel:'두 플랫폼의 물리 시간을 나란히 진행해 발산 관찰하기',
      boundary:'목표가 화면상 비슷한 재생인지, 서버 판정 검증처럼 비트 단위로 같은 시뮬레이션인지 구분한다. 결정성의 범위가 동일 빌드·동일 CPU인지, 서로 다른 플랫폼까지인지 먼저 정해야 한다.',
      naive:'입력과 seed가 같으면 계산도 같을 것이라 보고 매 프레임 동일한 float 물리를 실행한다.',
      failure:'컴파일러의 연산 재배치, FMA 사용, 중간 정밀도, denormal 처리 차이가 작은 오차를 만든다. 충돌과 분기처럼 임계값을 넘는 순간 서로 다른 코드 경로로 들어가며 이후 상태는 완전히 갈라진다.',
      reasoning:'부동소수점 덧셈은 결합법칙을 만족하지 않는다. 결정성은 자료형 하나가 아니라 빌드 옵션, 명령어 집합, 업데이트 순서, 컨테이너 순회 순서와 물리 알고리즘 전체의 계약이다.',
      build:'판정 리플레이라면 고정소수점 또는 검증된 결정적 수학 계층을 사용하고 entity 처리 순서와 reduction 순서를 고정한다. 플랫폼 결정성을 보장하기 어렵다면 일정 간격의 권위 snapshot과 event를 저장하는 결과 재생 방식을 선택한다.',
      verify:'매 tick 핵심 상태를 정규화해 hash로 비교하고 최초 불일치 tick을 자동 이분 탐색한다. 서로 다른 CPU·컴파일러·최적화 옵션의 CI에서 장시간 simulation corpus를 실행한다.',
      trade:'완전한 결정성은 SIMD 최적화와 외부 물리 라이브러리 선택을 제한한다. 영상용 리플레이와 판정용 리플레이의 요구를 분리하면 모든 시스템에 가장 비싼 제약을 강요하지 않아도 된다.',
      core:'같은 입력은 결정성의 시작일 뿐이며, 같은 연산 순서와 수학 계약이 있어야 같은 세계가 된다.'
    },
    {
      id:3,category:'A',
      question:'캐릭터 구조체를 그대로 저장했더니 패치 뒤 직업과 레벨이 뒤섞였다. 저장 파일은 무엇을 믿어야 할까?',
      scenario:'개발 중에는 `fwrite(&player, sizeof(player), 1, file)`로 빠르게 세이브했다. 멤버 하나를 추가하고 컴파일러 옵션을 바꾼 뒤 예전 파일을 읽자 레벨이 0이 되고 다음 필드부터 값이 밀렸다.',
      concepts:['padding','alignment','endianness','schema version'],
      labLabel:'메모리 바이트와 명시적 스키마를 직접 비교하기',
      boundary:'프로세스 내부 배치와 장기간 보존할 데이터 계약은 수명이 다르다. 어떤 빌드·플랫폼의 파일까지 읽어야 하는지와 필드의 필수·선택 여부부터 정한다.',
      naive:'구조체가 메모리에 이미 연속으로 있으니 그 바이트를 가장 빠른 저장 형식으로 사용한다.',
      failure:'컴파일러는 alignment를 위해 padding을 삽입하고 멤버 순서·pragma·ABI에 따라 크기가 달라진다. 포인터와 vtable 주소는 다음 실행에서 의미가 없고 endian이 다른 플랫폼은 다중 바이트 값을 거꾸로 읽는다.',
      reasoning:'메모리 표현은 현재 프로그램의 실행 계약이고 파일 포맷은 시간과 플랫폼을 건너는 외부 계약이다. 둘을 결합하면 내부 리팩터링이 곧 데이터 파괴가 된다.',
      build:'필드 ID·형식·길이와 schema version을 가진 명시적 직렬화를 사용한다. 알 수 없는 선택 필드는 건너뛰고 필수 필드 누락은 명확히 실패시킨다. migration은 이전 버전을 현재 모델로 단계적으로 올리고 원본을 백업한 뒤 원자적으로 교체한다.',
      verify:'모든 과거 fixture를 최신 코드로 읽는 golden test를 유지한다. 저장 중 강제 종료, 잘린 파일, 잘못된 길이, 다른 endian 입력을 fuzzing하고 round-trip 뒤 의미 값이 같은지 확인한다.',
      trade:'명시적 형식은 코드와 메타데이터가 늘지만 내부 레이아웃을 자유롭게 바꿀 수 있다. 극한의 로딩 성능이 필요하면 검증된 고정 포맷을 쓰되 버전별 reader를 유지해야 한다.',
      core:'구조체의 메모리 모양은 저장 계약이 아니다. 외부 데이터는 이름과 버전을 가진 스키마로 보존한다.'
    },
    {
      id:4,category:'A',
      question:'닉네임을 8글자로 잘랐는데 이모지 절반이 깨져 네모로 보인다. “한 글자”는 무엇일까?',
      scenario:'UI는 UTF-8 닉네임을 8바이트에서 잘라 말줄임표를 붙인다. 한글은 중간에서 깨지고, 가족 이모지는 여러 조각으로 분해되며, 악센트 문자는 같은 모양인데도 길이 제한 결과가 다르다.',
      concepts:['UTF-8','code point','grapheme cluster','normalization'],
      labLabel:'바이트·코드 포인트·보이는 글자 단위로 직접 자르기',
      boundary:'제한의 목적이 저장 바이트 예산인지, 화면 폭인지, 사용자가 인식하는 글자 수인지 구분한다. 세 기준은 같은 숫자를 사용할 수 없다.',
      naive:'문자열 배열의 길이를 글자 수로 보고 원하는 위치에 null 또는 substring 경계를 둔다.',
      failure:'UTF-8은 한 code point가 1~4바이트이며 보이는 한 글자가 여러 code point의 조합일 수 있다. 바이트 중간 절단은 유효하지 않은 인코딩을 만들고 code point 절단도 결합 문자와 ZWJ 이모지를 분리한다.',
      reasoning:'바이트는 저장 단위, code point는 유니코드 의미 단위, grapheme cluster는 사용자가 보는 편집 단위다. 렌더 폭은 다시 글꼴 shaping 결과이므로 별도로 측정해야 한다.',
      build:'입력은 유효한 UTF-8인지 검증하고 제품 정책에 맞게 normalization한다. 사용자 글자 제한은 grapheme iterator로, 패킷 제한은 최종 UTF-8 바이트로 검사한다. UI 말줄임은 shaping된 폭을 기준으로 cluster 경계에서 수행한다.',
      verify:'한글, 결합 악센트, 피부색 이모지, 가족 ZWJ, 국기, RTL 문자열 corpus를 둔다. 절단 결과가 항상 유효한 UTF-8이고 원본 cluster를 쪼개지 않는지 property test한다.',
      trade:'완전한 유니코드 처리는 라이브러리와 데이터 테이블 비용이 있다. 닉네임 정책을 제한할 수는 있지만 저장·표시 계층이 서로 다른 단위를 쓴다는 사실은 사라지지 않는다.',
      core:'문자열 길이라는 하나의 숫자는 없다. 저장·의미·표시 목적마다 올바른 단위를 선택해야 한다.'
    },
    {
      id:5,category:'A',
      question:'49일 동안 켜둔 서버에서 쿨다운이 갑자기 즉시 끝난다. 시간이 한 바퀴 돌아도 안전하려면?',
      scenario:'밀리초 tick을 32비트 unsigned로 저장한 테스트 서버가 장기 실행 뒤 wrap됐다. `now >= expire` 비교가 모든 타이머를 만료로 판정하거나 반대로 영원히 기다리게 만든다.',
      concepts:['integer wrap-around','modular arithmetic','monotonic clock','half-range'],
      labLabel:'원형 시계의 wrap 경계를 넘겨 만료 비교하기',
      boundary:'벽시계 시각과 경과 시간 측정을 분리한다. 쿨다운에는 사용자가 바꿀 수 있는 날짜가 아니라 단조 증가 clock이 필요하며 최대 비교 구간도 자료형 범위보다 작아야 한다.',
      naive:'현재 tick과 만료 tick을 일반 정수처럼 크기 비교한다.',
      failure:'고정 폭 unsigned 값은 최대값 다음에 0으로 돌아간다. wrap 직전의 만료 시각은 숫자로 크고 wrap 직후의 현재 시각은 작지만 실제 시간 순서는 반대다.',
      reasoning:'두 시각의 차이를 같은 폭의 unsigned로 계산하면 모듈러 공간에서 경과량을 얻을 수 있다. 단, 비교하려는 간격이 전체 범위의 절반보다 작다는 계약이 있어야 앞과 뒤를 구분한다.',
      build:'경과 시간은 monotonic clock을 사용하고 `int32(now - deadline) >= 0` 같은 wrap-safe helper를 한곳에 둔다. 장기 영속 만료는 충분히 넓은 정수의 절대 시각으로 저장하고 런타임 tick과 변환 경계를 분리한다.',
      verify:'wrap 직전·직후, 정확히 deadline, 최대 허용 duration, 절반 범위 경계와 clock reset을 가상 clock으로 테스트한다. 실제 49일을 기다리지 말고 tick을 주입 가능한 의존성으로 만든다.',
      trade:'64비트 tick은 실용적으로 wrap를 제거하지만 serialization 크기와 원자 연산 지원을 확인해야 한다. 폭을 넓혀도 벽시계 점프와 monotonic clock 선택 문제는 별개다.',
      core:'시간 비교는 숫자의 대소가 아니라 정의된 clock에서의 방향과 경과량을 판단하는 일이다.'
    },
    {
      id:6,category:'A',
      question:'어두운 동굴의 안개 농도를 8비트로 압축했더니 계단 무늬가 생긴다. 몇 비트가 충분할까?',
      scenario:'네트워크와 메모리를 줄이려고 조명·안개 파라미터를 0~255 정수로 양자화했다. 밝은 야외에서는 괜찮지만 어두운 영역의 완만한 그라데이션에서 띠가 눈에 띈다.',
      concepts:['quantization','dynamic range','perceptual encoding','dithering'],
      labLabel:'비트 수와 감마를 바꿔 밴딩 경계 관찰하기',
      boundary:'정확도는 값의 수가 아니라 사용자가 구분할 수 있는 오차와 후속 계산의 민감도로 정한다. 저장용·네트워크용·렌더 중간값에 같은 정밀도를 강제할 필요도 없다.',
      naive:'최솟값과 최댓값 사이를 동일 간격으로 256단계에 매핑한다.',
      failure:'인간의 밝기 지각은 선형이 아니며 어두운 구간의 작은 차이에 민감하다. 선형 양자화는 중요하지 않은 밝은 구간에 많은 코드를 쓰고 어두운 구간에는 부족한 단계를 남긴다.',
      reasoning:'양자화 오차의 허용 범위는 신호 분포와 지각 함수에 따라 달라진다. 비선형 인코딩은 코드 공간을 중요한 범위에 더 배분하고 dithering은 공간·시간적으로 오차를 분산해 구조적인 band를 감춘다.',
      build:'실측 분포와 perceptual error metric으로 bit 수를 선택한다. 전송은 감마 또는 로그 공간으로 양자화하고 shader 계산 전 선형 공간으로 복원한다. 필요한 경우 blue-noise dithering을 적용하되 판정 데이터에는 사용하지 않는다.',
      verify:'대표 장면과 최악의 완만한 gradient에서 원본 대비 오차 heatmap과 사용자 식별 한계를 측정한다. 압축률뿐 아니라 temporal flicker와 플랫폼별 색상 경로도 비교한다.',
      trade:'비선형 압축은 encoder·decoder 계약과 디버깅 비용을 늘린다. 한두 비트를 늘리는 대역폭 비용이 작다면 복잡한 보정보다 단순한 고정 정밀도가 더 안전할 수 있다.',
      core:'필요한 비트 수는 값의 범위가 아니라 그 값이 사용되는 곳에서 허용할 수 있는 오차가 결정한다.'
    },
    {
      id:7,category:'A',
      question:'같은 seed로 시작했는데 전리품 리플레이가 중간부터 달라진다. 난수는 무엇까지 기록해야 할까?',
      scenario:'전투 재현을 위해 match seed 하나만 로그에 남겼다. 디버그 빌드에서 시각 효과가 난수를 한 번 더 소비하자 이후 치명타와 전리품까지 전부 달라졌다.',
      concepts:['PRNG state','call-order coupling','stream splitting','replay'],
      labLabel:'난수 소비 순서를 바꿔 결과 연쇄가 무너지는 모습 보기',
      boundary:'난수의 목적을 판정, 콘텐츠 생성, 시각 효과, 보안 토큰으로 나눈다. 재현이 필요한 결정적 난수와 예측되면 안 되는 보안 난수는 같은 생성기를 공유할 수 없다.',
      naive:'경기 시작 seed 하나로 전역 RNG를 만들고 모든 시스템이 필요할 때 호출한다.',
      failure:'PRNG는 호출 순서가 상태 전이 순서다. 무관한 시스템의 호출 하나가 뒤의 모든 값을 밀어내며 멀티스레드에서는 스케줄 순서까지 결과에 섞인다.',
      reasoning:'seed는 초기 상태만 복원한다. 재현하려면 어떤 stream이 몇 번째 값을 사용했는지 안정적이어야 한다. 시스템별 stream 분리나 사건 ID 기반의 stateless hash가 결합을 끊는다.',
      build:'판정 영역별로 명명된 RNG stream과 version을 두고 seed를 match ID·system ID에서 파생한다. entity별 사건은 안정된 key를 hash해 순서 의존성을 줄인다. 보안 값은 OS CSPRNG를 별도로 사용한다.',
      verify:'시각 효과 호출 추가, 작업 순서 변경, entity 삽입에도 판정 결과가 같은 metamorphic test를 만든다. replay에는 RNG algorithm version과 핵심 draw counter를 기록해 최초 발산을 찾는다.',
      trade:'stream을 지나치게 잘게 나누면 관리와 추적이 어렵고 설계자가 상관관계를 놓칠 수 있다. 전역 stream은 단순하지만 작은 변경의 영향 반경이 전체 simulation이 된다.',
      core:'결정적 난수의 계약은 같은 seed가 아니라 같은 목적의 소비가 다른 시스템 변화와 격리되는 것이다.'
    },
    {
      id:8,category:'A',
      question:'죽은 몬스터 자리에 새 몬스터가 생성되자 오래된 투사체가 새 몬스터를 맞힌다. 포인터 대신 무엇을 들고 있어야 할까?',
      scenario:'엔티티 풀은 제거된 슬롯을 빠르게 재사용한다. 투사체가 저장한 대상 포인터의 주소는 여전히 유효하지만 그 주소의 객체는 이미 다른 몬스터다.',
      concepts:['handle','generation counter','stale reference','object pool'],
      labLabel:'슬롯을 회수·재사용하며 세대 검증 직접 실행하기',
      boundary:'메모리 주소가 유효한지와 게임 세계에서 동일한 논리 객체인지 구분한다. 비동기 작업과 지연 이벤트가 객체의 생명주기보다 오래 살아남을 수 있는지부터 확인한다.',
      naive:'풀 객체는 주소가 안정적이므로 raw pointer를 ID처럼 저장한다.',
      failure:'주소 안정성은 메모리 위치만 보장한다. 슬롯이 재사용되면 오래된 참조는 타입과 주소가 모두 정상인 새 객체를 가리켜 오류가 크래시가 아닌 잘못된 게임 판정으로 나타난다.',
      reasoning:'논리 identity에는 위치와 세대가 함께 필요하다. handle의 index로 슬롯을 찾고 generation이 현재 슬롯과 같을 때만 동일 객체로 인정하면 재사용을 탐지할 수 있다.',
      build:'`{index, generation}` handle을 공개 참조로 사용하고 destroy 때 generation을 증가시킨다. resolve는 alive bit와 generation을 검증하며 비동기 결과에는 요청 당시 handle을 그대로 포함한다.',
      verify:'destroy→reuse→late callback, generation wrap, 잘못된 index, 대량 churn을 테스트한다. stale handle 접근 횟수를 계측하고 개발 빌드에서는 호출 지점과 원래 entity ID를 기록한다.',
      trade:'handle lookup은 간접 참조 비용이 있으며 generation bit가 작으면 매우 긴 실행에서 wrap할 수 있다. 프레임 내부 hot loop는 검증된 직접 배열 접근을 사용하고 외부·비동기 경계에서는 handle을 강제할 수 있다.',
      core:'같은 주소는 같은 게임 객체가 아니다. 재사용 가능한 저장소에서는 위치와 생명주기 세대가 identity를 만든다.'
    },
    {
      id:9,category:'A',
      question:'오픈월드 원점에서 멀어질수록 캐릭터가 떨리고 카메라가 벽을 뚫는다. 세계 좌표를 어떻게 유지할까?',
      scenario:'월드 중심에서는 부드럽던 캐릭터가 수십 킬로미터 떨어지자 작은 움직임을 표현하지 못한다. 카메라와 물리 접촉점이 프레임마다 튀고 먼 오브젝트 변환도 흔들린다.',
      concepts:['floating-point spacing','floating origin','local coordinates','hierarchical space'],
      labLabel:'원점에서 거리를 늘려 표현 가능한 최소 간격 측정하기',
      boundary:'월드의 논리적 범위와 렌더·물리가 요구하는 로컬 정밀도를 나눈다. 모든 시스템이 하나의 거대한 float 좌표계를 공유해야 한다는 가정을 버린다.',
      naive:'모든 위치를 월드 원점 기준 float3 하나로 저장한다.',
      failure:'float의 상대 정밀도 때문에 절댓값이 커질수록 인접 표현 값의 간격도 커진다. 수 밀리미터 이동이 반올림되고 행렬 뺄셈에서 유효 자릿수가 사라진다.',
      reasoning:'정밀도가 필요한 계산은 값의 절댓크기가 작은 좌표계에서 해야 한다. 거대한 논리 위치는 고정된 cell과 cell 내부 offset으로 분해하거나 double로 보존하고 렌더·물리에는 관찰자 근처의 local float를 제공한다.',
      build:'월드를 정수 grid/cell과 local coordinate로 표현한다. 플레이어가 임계점을 넘으면 floating origin을 이동하고 scene node·physics broadphase·particle의 기준을 일관된 phase에서 갱신한다.',
      verify:'원점부터 최대 거리까지 최소 이동 단위, 카메라 jitter, 접촉 안정성을 자동 sweep한다. origin shift 프레임에 velocity·trail·audio 위치가 튀지 않는지도 캡처한다.',
      trade:'double은 구현이 단순하지만 GPU·물리·대역폭 비용이 커질 수 있다. cell 좌표는 정밀하지만 경계 교차와 서로 다른 cell 간 연산 규칙이 추가된다.',
      core:'큰 세계를 정확히 표현하는 방법은 모든 숫자를 크게 만드는 것이 아니라 계산마다 작은 지역 좌표계를 제공하는 것이다.'
    },
    {
      id:10,category:'A',
      question:'패킷에 필드 하나를 추가했더니 구버전 클라이언트가 이후 값을 전부 잘못 읽는다. 계약을 어떻게 진화시킬까?',
      scenario:'서버가 캐릭터 상태 패킷 중간에 `shield` 정수를 추가했다. 필드 순서를 고정 길이로 읽던 구버전은 shield를 speed로 해석하고 이후 바이트 경계까지 밀렸다.',
      concepts:['wire schema','length prefix','optional field','compatibility'],
      labLabel:'구버전·신버전 디코더로 같은 패킷을 번갈아 읽기',
      boundary:'점진 배포 중 어떤 버전 조합을 지원할지 정한다. 새 필드를 모르는 reader가 무시해도 되는지, 없을 때 기본값이 의미상 안전한지 구분한다.',
      naive:'송신자와 수신자를 항상 동시에 배포한다고 가정하고 구조체 필드 순서대로 값을 이어 붙인다.',
      failure:'현실에서는 플랫폼 심사와 롤백 때문에 여러 버전이 공존한다. 중간 삽입은 위치 기반 decoder의 모든 뒤 필드를 바꾸며 길이를 모르는 데이터는 건너뛸 수도 없다.',
      reasoning:'호환 가능한 wire format은 각 값의 경계를 reader가 알 수 있어야 한다. tag와 length, schema version 또는 capability가 있어야 모르는 값을 건너뛰고 필요한 계약만 협상할 수 있다.',
      build:'필드 ID·wire type·length를 가진 schema를 사용하거나 메시지 version별 명시적 decoder를 둔다. optional 필드는 안전한 기본값을 정의하고 파괴적 의미 변경은 새 field ID 또는 major protocol로 분리한다.',
      verify:'현재 writer×지원하는 모든 과거 reader의 compatibility matrix를 CI에서 실행한다. 알 수 없는 field, 순서 변경, 누락, 최대 길이와 malformed packet을 fuzzing한다.',
      trade:'tagged format은 몇 바이트와 분기 비용을 추가한다. 고빈도 hot packet은 capability로 고정 레이아웃 variant를 협상할 수 있지만 지원 기간과 제거 계획까지 운영해야 한다.',
      core:'프로토콜의 필드는 메모리 위치가 아니라 의미와 경계를 가진 장기 계약이다.'
    }
  ];
  window.CSInterviewData={categories,questions};
})();
