(function(){
'use strict';
let active=null;
const head=(k,t,d)=>`<div class="concept-head"><div><span>${k}</span><h3>${t}</h3><p>${d}</p></div><button data-econ-action="close">닫기</button></div>`;
const status=(l,m)=>`<div class="concept-status" aria-live="polite"><b data-econ-label>${l}</b><span data-econ-message>${m}</span></div>`;
const host=()=>active?document.querySelector(`[data-flow-host="${active.id}"]`):null;
const one=s=>host()?.querySelector(s)||null,all=s=>host()?[...host().querySelectorAll(s)]:[];
const text=(s,v)=>{const n=one(s);if(n)n.textContent=v},say=(l,m)=>{text('[data-econ-label]',l);text('[data-econ-message]',m)};
function q61(){return `<section class="concept-demo">${head('Q61 · revision reconciliation','아이템 사용 직후 끊기면 클라이언트 표시가 진실일까?','낡은 로컬 표시와 서버 inventory revision을 비교해 확정 상태로 수렴시키세요.')}<div class="econ-stage"><div class="reconcile-grid"><div class="inventory-view"><h4>Client · rev 17</h4><div class="item-slot is-ghost" data-client-item>POTION ×1<br>사용 표시 누락</div></div><div class="revision-arrow"><b>⇄</b><span data-rev-query>revision?</span></div><div class="inventory-view"><h4>Server · rev 18</h4><div class="item-slot is-empty">EMPTY<br>use U-31 committed</div></div></div></div><div class="concept-controls"><button class="primary" data-econ-action="reconcile">재접속 · revision 확인</button><button data-econ-action="reset">초기화</button></div>${status('표시 불일치','클라이언트 캐시를 믿고 복제 지급하지 말고 서버 revision과 결과 ID를 조회합니다.')}</section>`}
function reconcile(){one('[data-client-item]').className='item-slot is-empty';one('[data-client-item]').innerHTML='EMPTY<br>rev 18 적용';text('[data-rev-query]','17 → snapshot 18');say('서버 상태로 수렴','U-31이 이미 commit됐으므로 아이템을 되살리지 않고 rev 18 snapshot으로 로컬 캐시를 교체합니다.')}
function q62(){return `<section class="concept-demo">${head('Q62 · 구매 receipt idempotency','응답이 없어서 다시 산 검이 두 자루 지급될까?','같은 purchase ID를 여러 번 보내고 원장이 같은 receipt를 재생하는지 확인하세요.')}<div class="econ-stage"><div class="receipt-lab"><div class="shop-item">SWORD<br>1,000 GOLD</div><div class="receipt-ledger" data-receipt><div class="receipt-row">P-440 · no record</div></div></div></div><div class="concept-controls"><button class="primary" data-econ-action="buy">P-440 구매</button><button data-econ-action="retrybuy">응답 유실 · P-440 재요청</button><button data-econ-action="reset">초기화</button></div>${status('구매 전','가격 차감과 지급 결과를 purchase ID 하나에 묶습니다.')}</section>`}
function buy(retry){if(!active.bought){active.bought=true;one('[data-receipt]').innerHTML='<div class="receipt-row">P-440 · -1000 GOLD</div><div class="receipt-row">P-440 · item SWORD#882</div>';say('구매 commit','차감과 지급을 P-440 receipt로 영속화했습니다.')}else{one('[data-receipt]').innerHTML+='<div class="receipt-row is-hit">P-440 · replay SWORD#882 · no charge</div>';say('같은 receipt replay',retry?'재요청은 새 지급이 아니라 기존 SWORD#882 결과를 돌려줍니다.':'이미 처리한 ID이므로 추가 효과가 없습니다.')}}
function q63(){return `<section class="concept-demo">${head('Q63 · 원자적 교환','두 플레이어가 동시에 확정을 누르면 누가 먼저 소유권을 바꿀까?','양쪽 제안을 escrow에 잠그고 하나의 transaction에서 교환하세요.')}<div class="econ-stage"><div class="trade-table"><div class="trade-player" data-trader="A"><h4>PLAYER A</h4><div class="trade-offer">SWORD#11</div><button data-econ-action="ready" data-player="A">확정</button></div><div class="trade-lock" data-trade-lock>ESCROW<br>OPEN</div><div class="trade-player" data-trader="B"><h4>PLAYER B</h4><div class="trade-offer">GOLD 500</div><button data-econ-action="ready" data-player="B">확정</button></div></div></div>${status('두 제안 미확정','각 확정은 같은 trade revision을 갱신하고 둘 다 준비됐을 때 한 번만 commit합니다.')}</section>`}
function ready(p){active.ready.add(p);one(`[data-trader="${p}"] button`).disabled=true;one('[data-trade-lock]').classList.add('is-held');one('[data-trade-lock]').innerHTML=`ESCROW<br>${[...active.ready].join('+')} LOCKED`;if(active.ready.size===2){one('[data-trade-lock]').className='trade-lock is-commit';one('[data-trade-lock]').innerHTML='TRADE T-9<br>COMMITTED';all('.trade-player').forEach(n=>n.classList.add('is-swapped'));one('[data-trader="A"] .trade-offer').textContent='GOLD 500';one('[data-trader="B"] .trade-offer').textContent='SWORD#11';say('교환 commit','두 소유권 변경은 T-9 하나에서 함께 성공해 중간 상태가 보이지 않습니다.')}else say(`${p} 제안 잠금`,'다른 쪽 확정을 기다리며 아이템은 이동·사용할 수 없습니다.')}
function q64(){return `<section class="concept-demo">${head('Q64 · capacity precondition','교환 도중 가방이 차면 절반만 이동해도 될까?','목적지 슬롯을 예약한 뒤 경쟁 아이템을 넣어 전체 rollback을 확인하세요.')}<div class="econ-stage"><div class="capacity-track"><div class="bag"><h4>A · 2칸 필요</h4><div class="bag-slots">${'<i class="is-filled"></i>'.repeat(6)}<i></i><i></i></div></div><div class="capacity-gate" data-capacity-gate>PRECHECK</div><div class="bag"><h4>B · 1칸 필요</h4><div class="bag-slots" data-bag-b>${'<i class="is-filled"></i>'.repeat(7)}<i></i></div></div></div></div><div class="concept-controls"><button data-econ-action="reserve">슬롯 예약</button><button data-econ-action="fill">경쟁 아이템 유입</button><button class="primary" data-econ-action="committrade">교환 commit</button><button data-econ-action="reset">초기화</button></div>${status('용량 검사 전','읽기 시점 빈칸이 아니라 commit까지 유효한 reservation이 필요합니다.')}</section>`}
function reserve(){active.reserved=true;all('.bag-slots i:not(.is-filled)').forEach(n=>n.classList.add('is-reserved'));say('슬롯 reservation','거래 T-10이 필요한 목적지 공간을 revision과 함께 예약했습니다.')}
function fill(){const empty=all('[data-bag-b] i:not(.is-filled)')[0];if(empty){empty.className='is-filled';active.conflict=true}say('경쟁 변경 발생','예약을 무시한 쓰기라면 expected revision이 달라 commit에서 감지됩니다.')}
function commitTrade(){const gate=one('[data-capacity-gate]');if(!active.reserved||active.conflict){gate.className='capacity-gate is-stop';gate.textContent='ROLLBACK';all('.bag-slots i.is-reserved').forEach(n=>n.className='is-rollback');say('전체 rollback','한쪽 capacity precondition이 깨져 차감·이동 모두 취소됐습니다.')}else{gate.className='capacity-gate is-go';gate.textContent='COMMIT';say('원자적 교환','예약한 공간과 같은 revision에서 양쪽 이동을 함께 확정했습니다.')}}
function q65(){return `<section class="concept-demo">${head('Q65 · mail claim CAS','같은 우편을 두 서버가 동시에 열면 보상이 두 번 생길까?','두 서버가 같은 mail revision으로 claim을 경쟁해 한 쪽만 상태 전이를 성공시키세요.')}<div class="econ-stage"><div class="mail-race"><div class="mail-letter">MAIL M-77<br>UNCLAIMED rev 5</div><div class="mail-server" data-mail-server="A"><b>SERVER A</b>claim rev 5</div><div class="mail-server" data-mail-server="B"><b>SERVER B</b>claim rev 5</div><div class="mail-claim" data-mail-claim>owner 없음 · reward R-77 미발급</div></div></div><div class="concept-controls"><button class="primary" data-econ-action="claimrace">동시 claim 실행</button><button data-econ-action="reset">초기화</button></div>${status('CAS 대기','UNCLAIMED rev 5 → CLAIMED rev 6 전이는 한 서버만 성공할 수 있습니다.')}</section>`}
function claimRace(){one('[data-mail-server="A"]').classList.add('is-winner');one('[data-mail-server="B"]').classList.add('is-loser');text('[data-mail-claim]','A 승리 · CLAIMED rev 6 · reward R-77 / B는 기존 결과 replay');say('한 번만 수령','B의 CAS는 revision mismatch로 실패하고 M-77의 이미 확정된 R-77 결과를 반환합니다.')}
const makers={61:q61,62:q62,63:q63,64:q64,65:q65};
function open(id){close(false);document.dispatchEvent(new CustomEvent('interview-demo-open',{detail:{id}}));active={id,bought:false,ready:new Set(),reserved:false,conflict:false};const h=document.querySelector(`[data-flow-host="${id}"]`),b=document.querySelector(`[data-flow-open="${id}"]`);if(b){b.hidden=true;b.setAttribute('aria-expanded','true')}h.innerHTML=makers[id]()}
function reset(){const id=active.id;active={id,bought:false,ready:new Set(),reserved:false,conflict:false};host().innerHTML=makers[id]()}
function close(focus=true){if(!active)return;const id=active.id,h=document.querySelector(`[data-flow-host="${id}"]`),b=document.querySelector(`[data-flow-open="${id}"]`);if(h)h.innerHTML='';if(b){b.hidden=false;b.setAttribute('aria-expanded','false');if(focus)b.focus({preventScroll:true})}active=null}
function init(){document.addEventListener('click',e=>{const o=e.target.closest('[data-flow-open]');if(o){const id=+o.dataset.flowOpen;if(id>=61&&id<=65){open(id);return}}const b=e.target.closest('[data-econ-action]');if(!b||!active)return;const x=b.dataset.econAction;if(x==='close')close();if(x==='reset')reset();if(x==='reconcile')reconcile();if(x==='buy')buy(false);if(x==='retrybuy')buy(true);if(x==='ready')ready(b.dataset.player);if(x==='reserve')reserve();if(x==='fill')fill();if(x==='committrade')commitTrade();if(x==='claimrace')claimRace()});document.addEventListener('interview-demo-open',e=>{if(active&&active.id!==e.detail.id)close(false)})}
window.EconomyCore={init};
})();
