(function(){'use strict';let a=null;
const H=(k,t,d)=>`<div class="concept-head"><div><span>${k}</span><h3>${t}</h3><p>${d}</p></div><button data-pp-action="close">닫기</button></div>`,S=(l,m)=>`<div class="concept-status" aria-live="polite"><b data-pp-label>${l}</b><span data-pp-message>${m}</span></div>`;
const h=()=>a?document.querySelector(`[data-flow-host="${a.id}"]`):null,q=s=>h()?.querySelector(s)||null,qa=s=>h()?[...h().querySelectorAll(s)]:[],tx=(s,v)=>{const n=q(s);if(n)n.textContent=v},say=(l,m)=>{tx('[data-pp-label]',l);tx('[data-pp-message]',m)};
function m106(){const steps=[['UPLOAD','size·type'],['SCAN','malware'],['SCHEMA','version'],['SANDBOX','budget'],['PUBLISH','signed ID']];return `<section class="concept-demo">${H('Q106 · staged UGC trust boundary','사용자 파일을 받은 즉시 게임 서버에서 실행해도 될까?','파일 유형을 바꾸고 격리·검사·호환성·sandbox 예산을 순서대로 통과시키세요.')}<div class="concept-controls"><label>업로드 유형 <select data-ugc-kind><option value="safe">safe map v3</option><option value="script">native executable</option><option value="old">map schema v1</option></select></label></div><div class="mm-arena"><div class="ugc-pipeline">${steps.map((x,i)=>`<div class="ugc-step" data-ugc="${i}"><b>${x[0]}</b>${x[1]}</div>`).join('')}</div></div><div class="concept-controls"><button class="primary" data-pp-action="ugcstep">다음 검증 단계</button><button data-pp-action="reset">초기화</button></div>${S('quarantine upload','검증 전 객체는 실행·배포 경로에서 격리합니다.')}</section>`}
function ugc106(){const kind=q('[data-ugc-kind]').value;if(a.failed)return;a.phase=Math.min(5,a.phase+1);qa('[data-ugc]').forEach((n,i)=>n.classList.toggle('is-on',i<a.phase));if(kind==='script'&&a.phase===2){q('[data-ugc="1"]').classList.add('is-failed');a.failed=true;say('native code 차단','허용 목록 밖 executable은 sandbox로도 넘기지 않습니다.');return}if(kind==='old'&&a.phase===3){q('[data-ugc="2"]').classList.add('is-failed');a.failed=true;say('schema v1 격리','지원 중인 v3 converter가 없으므로 호환되지 않는 콘텐츠를 publish하지 않습니다.');return}if(a.phase===5){qa('[data-ugc]').forEach(n=>n.classList.add('is-safe'));say('UGC U-106 publish','검증 hash·schema·resource budget이 서명된 immutable 콘텐츠 ID에 묶였습니다.')}else say(`검증 ${a.phase}/5`,'다음 trust boundary로 넘기기 전에 현재 단계 결과를 영속화합니다.')}
function m107(){return `<section class="concept-demo">${H('Q107 · account link merge plan','PC와 콘솔 계정을 연결하면 숫자를 무조건 더할까?','진행도·고유 아이템·소비 재화별 merge 규칙을 적용해 결과를 미리 확인하세요.')}<div class="mm-arena"><div class="merge-ledgers"><div class="merge-account"><h4>PC · A1</h4><div class="merge-asset">level 42</div><div class="merge-asset">mount M7</div><div class="merge-asset is-conflict">gem 500</div></div><div class="merge-gate">→</div><div class="merge-account"><h4>CONSOLE · B8</h4><div class="merge-asset">level 35</div><div class="merge-asset">mount M9</div><div class="merge-asset is-conflict">gem 900</div></div><div class="merge-result" data-merge-result>명시적 merge plan 없음</div></div></div><div class="concept-controls"><button data-pp-action="preview107">merge 미리보기</button><button class="primary" data-pp-action="commit107">link L-107 commit</button><button data-pp-action="reset">초기화</button></div>${S('자산 유형별 규칙','진행도는 max, 고유 권리는 union, 소비 재화는 중복 출처를 검사하는 식으로 따로 정의합니다.')}</section>`}
function preview107(){a.preview=true;tx('[data-merge-result]','PREVIEW · level 42 · mounts M7+M9 · gem 900 (중복 구매 출처 제거)');say('merge plan 고정','두 원장을 직접 덮지 않고 source revision과 결과 hash를 사용자에게 확인시킵니다.')}
function commit107(){if(!a.preview){say('commit 차단','먼저 되돌릴 수 있는 merge plan을 생성하세요.');return}q('[data-merge-result]').classList.add('is-done');tx('[data-merge-result]','LINK L-107 · canonical account C3 · audit + unlink window');say('원자적 계정 연결','canonical identity와 자산 mapping을 한 번에 바꾸고 원본 provenance를 보존합니다.')}
function m108(){return `<section class="concept-demo">${H('Q108 · verified entitlement ledger','플랫폼 상점 화면과 게임 아이템이 다르면 어느 쪽 숫자를 믿을까?','platform receipt를 검증해 entitlement를 발급하고 환불 notification으로 회수하세요.')}<div class="mm-arena"><div class="entitlement-grid"><div class="entitlement-col"><h4>PLATFORM</h4><div class="ent-row">receipt R-108</div><div class="ent-row">SKU DLC-1</div></div><div class="entitlement-col"><h4>GAME LEDGER</h4><div class="ent-row is-missing" data-ent>entitlement 없음</div></div><div class="entitlement-col"><h4>INVENTORY</h4><div class="ent-row is-missing" data-ent-item>DLC item 잠김</div></div></div></div><div class="concept-controls"><button class="primary" data-pp-action="verify108">platform receipt 검증</button><button data-pp-action="refund108">환불 webhook</button><button data-pp-action="reset">초기화</button></div>${S('권리 불일치','플랫폼 receipt는 증거이고 게임 entitlement ledger가 플레이 권리의 운영 기준입니다.')}</section>`}
function verify108(){q('[data-ent]').className='ent-row is-granted';tx('[data-ent]','E-108 ACTIVE · receipt R-108');q('[data-ent-item]').className='ent-row is-granted';tx('[data-ent-item]','DLC item 사용 가능');a.granted=true;say('entitlement 발급','서명·SKU·계정·소비 여부를 서버 대 서버로 검증했습니다.')}
function refund108(){if(!a.granted){say('회수 대상 없음','활성 entitlement가 없습니다.');return}q('[data-ent]').className='ent-row is-revoked';q('[data-ent-item]').className='ent-row is-revoked';say('E-108 REVOKED','환불 event를 멱등 처리하고 사용 중 콘텐츠의 안전한 종료 정책을 적용합니다.')}
function m109(){const steps=[['PLATFORM','invite handle'],['IDENTITY','friend mapping'],['SESSION','join token'],['WORLD','seat lease'],['CLIENT','connect']];return `<section class="concept-demo">${H('Q109 · deep-link join exchange','콘솔 알림의 친구 ID만으로 월드에 바로 접속할 수 있을까?','플랫폼 초대를 내부 identity·session·world reservation으로 교환하는 단계를 실행하세요.')}<div class="mm-arena"><div class="join-exchange">${steps.map((x,i)=>`<div class="join-node" data-join="${i}"><b>${x[0]}</b>${x[1]}</div>`).join('')}</div></div><div class="concept-controls"><label><input type="checkbox" data-party-full> target party full</label><button class="primary" data-pp-action="joinstep">다음 join 단계</button><button data-pp-action="reset">초기화</button></div>${S('platform invite 수신','초대는 세션 권한이 아니므로 현재 차단·연령·정원·월드 상태를 서버에서 다시 검사합니다.')}</section>`}
function join109(){if(a.failed)return;a.phase=Math.min(5,a.phase+1);qa('[data-join]').forEach((n,i)=>n.classList.toggle('is-on',i<a.phase));if(a.phase===4&&q('[data-party-full]').checked){q('[data-join="3"]').classList.add('is-failed');a.failed=true;say('seat reservation 실패','초대가 유효해도 현재 정원이 없어 재시도 가능한 명시적 결과를 반환합니다.');return}if(a.phase===4)q('[data-join="3"]').classList.add('is-reserved');if(a.phase===5)say('짧은 join token으로 연결','account·target session·world·expiry가 묶인 일회용 token을 소비했습니다.');else say(`join 교환 ${a.phase}/5`,'각 경계에서 최신 권한과 상태를 다시 확인합니다.')}
function m110(){const rows=[['TEXT CHAT',['ALLOW','DENY','ALLOW']],['VOICE',['ALLOW','DENY','DENY']],['PURCHASE',['ALLOW','PARENT','DENY']],['UGC',['ALLOW','DENY','DENY']]];return `<section class="concept-demo">${H('Q110 · server capability policy','클라이언트가 지역·나이를 보고 버튼만 숨기면 충분할까?','정책 profile을 바꿔 서버가 발급·실행 경계에서 동일 capability를 강제하는지 보세요.')}<div class="concept-controls"><label>정책 profile <select data-policy-profile><option value="adult">성인·일반 지역</option><option value="minor">미성년자</option><option value="restricted">제한 지역</option></select></label></div><div class="mm-arena"><div class="capability-matrix"><div class="cap-cell head">CAPABILITY</div>${['ADULT','MINOR','RESTRICTED'].map(x=>`<div class="cap-cell head">${x}</div>`).join('')}${rows.map((r,i)=>`<div class="cap-cell head">${r[0]}</div>${r[1].map((v,j)=>`<div class="cap-cell" data-cap="${i}-${j}">${v}</div>`).join('')}`).join('')}</div><div class="cap-revision" data-cap-rev>policy rev 60 · ADULT</div></div>${S('권위 capability 계산','UI는 설명을 위해 숨기지만 서버 API·토큰 발급·결제 경계가 실제 정책을 강제합니다.')}</section>`}
function policy110(){const idx={adult:0,minor:1,restricted:2}[q('[data-policy-profile]').value],name=['ADULT','MINOR','RESTRICTED'][idx];qa('[data-cap]').forEach(n=>{const [,j]=n.dataset.cap.split('-').map(Number);n.classList.toggle('is-allow',j===idx&&n.textContent==='ALLOW');n.classList.toggle('is-deny',j===idx&&n.textContent!=='ALLOW')});tx('[data-cap-rev]',`policy rev 60 · ${name} · server enforced`);say(`${name} capability 적용`,'채팅·보이스·구매·UGC가 같은 policy snapshot을 사용합니다.')}
const M={106:m106,107:m107,108:m108,109:m109,110:m110};
function open(id){close(false);document.dispatchEvent(new CustomEvent('interview-demo-open',{detail:{id}}));a={id,phase:0,failed:false,preview:false,granted:false};const x=document.querySelector(`[data-flow-host="${id}"]`),b=document.querySelector(`[data-flow-open="${id}"]`);if(b){b.hidden=true;b.setAttribute('aria-expanded','true')}x.innerHTML=M[id]();if(id===110)policy110()}
function reset(){const id=a.id;a={id,phase:0,failed:false,preview:false,granted:false};h().innerHTML=M[id]();if(id===110)policy110()}
function close(f=true){if(!a)return;const id=a.id,x=document.querySelector(`[data-flow-host="${id}"]`),b=document.querySelector(`[data-flow-open="${id}"]`);if(x)x.innerHTML='';if(b){b.hidden=false;b.setAttribute('aria-expanded','false');if(f)b.focus({preventScroll:true})}a=null}
function init(){document.addEventListener('click',e=>{const o=e.target.closest('[data-flow-open]');if(o){const id=+o.dataset.flowOpen;if(id>=106&&id<=110){open(id);return}}const b=e.target.closest('[data-pp-action]');if(!b||!a)return;const x=b.dataset.ppAction;if(x==='close')close();if(x==='reset')reset();if(x==='ugcstep')ugc106();if(x==='preview107')preview107();if(x==='commit107')commit107();if(x==='verify108')verify108();if(x==='refund108')refund108();if(x==='joinstep')join109()});document.addEventListener('change',e=>{if(e.target.matches('[data-ugc-kind]')){a.phase=0;a.failed=false;qa('[data-ugc]').forEach(n=>n.className='ugc-step')}if(e.target.matches('[data-policy-profile]'))policy110()});document.addEventListener('interview-demo-open',e=>{if(a&&a.id!==e.detail.id)close(false)})}window.PlatformPolicy={init}})();
