(function(){
'use strict';let active=null;
const H=(k,t,d)=>`<div class="concept-head"><div><span>${k}</span><h3>${t}</h3><p>${d}</p></div><button data-scale-action="close">닫기</button></div>`,S=(l,m)=>`<div class="concept-status" aria-live="polite"><b data-scale-label>${l}</b><span data-scale-message>${m}</span></div>`;
const host=()=>active?document.querySelector(`[data-flow-host="${active.id}"]`):null,q=s=>host()?.querySelector(s)||null,qa=s=>host()?[...host().querySelectorAll(s)]:[],tx=(s,v)=>{const n=q(s);if(n)n.textContent=v},say=(l,m)=>{tx('[data-scale-label]',l);tx('[data-scale-message]',m)};
function m71(){return `<section class="concept-demo">${H('Q71 · 병목 분해','사람이 많아 느린데 서버 CPU만 올리면 해결될까?','군중·이펙트·복제량을 따로 움직여 CPU, GPU, 네트워크 중 먼저 포화되는 자원을 찾으세요.')}<div class="mm-arena"><div class="bottle-lanes">${[['CPU','cpu'],['GPU','gpu'],['NET','net']].map(x=>`<div class="bottle-row" data-bottle="${x[1]}"><span>${x[0]}</span><div class="bottle-track"><i style="--load:0%"></i></div><output data-bottle-v="${x[1]}">0%</output></div>`).join('')}</div></div><div class="concept-controls"><label>플레이어 <input type="range" min="50" max="500" value="180" data-crowd><output data-crowd-v>180</output></label><label>이펙트 품질 <input type="range" min="1" max="10" value="6" data-effects><output data-effects-v>6</output></label><label>복제 상세 <input type="range" min="1" max="10" value="7" data-detail><output data-detail-v>7</output></label></div>${S('부하 계산','각 자원의 원인이 다른지 먼저 분해해야 올바른 완화책을 선택할 수 있습니다.')}</section>`}
function load71(){const crowd=+q('[data-crowd]').value,fx=+q('[data-effects]').value,detail=+q('[data-detail]').value;tx('[data-crowd-v]',crowd);tx('[data-effects-v]',fx);tx('[data-detail-v]',detail);const v={cpu:Math.min(150,Math.round(crowd/5+detail*3)),gpu:Math.min(150,Math.round(crowd/9+fx*8)),net:Math.min(150,Math.round(crowd/7+detail*7))};let worst='cpu';Object.keys(v).forEach(k=>{const row=q(`[data-bottle="${k}"]`);row.classList.toggle('is-hot',v[k]>=100);row.querySelector('i').style.setProperty('--load',`${Math.min(100,v[k])}%`);tx(`[data-bottle-v="${k}"]`,`${v[k]}%`);if(v[k]>v[worst])worst=k});say(`${worst.toUpperCase()}가 첫 병목`,worst==='cpu'?'판정 빈도·공간 질의를 줄입니다.':worst==='gpu'?'표현 LOD와 이펙트 예산을 낮춥니다.':'AOI·전송 주기·필드 정밀도를 조정합니다.')}
function m72(){const ents=[['ALLY',20,23,'ally'],['ENEMY',68,24,'enemy'],['BOSS',78,55,'boss'],['NPC',18,72,'npc'],['FAR',72,82,'far'],['CAST',40,16,'cast']];return `<section class="concept-demo">${H('Q72 · 중요도 기반 복제','수백 명 중 누구의 이동을 자세히 보내야 할까?','거리만이 아니라 위협, 파티, 현재 행동을 조합해 full·summary 복제를 나누세요.')}<div class="mm-arena"><div class="priority-field"><div class="priority-player">YOU</div>${ents.map(x=>`<div class="priority-entity" style="--x:${x[1]}%;--y:${x[2]}%" data-priority="${x[3]}">${x[0]}</div>`).join('')}</div></div><div class="concept-controls"><label><input type="checkbox" checked data-priority-rule="distance"> 근거리</label><label><input type="checkbox" data-priority-rule="threat"> 공격자·시전자</label><label><input type="checkbox" data-priority-rule="party"> 파티원</label></div>${S('거리 규칙만 적용','규칙을 켜면 먼 boss·시전자도 높은 의미 때문에 full update로 승격됩니다.')}</section>`}
function priority72(){const rules=new Set(qa('[data-priority-rule]:checked').map(n=>n.dataset.priorityRule));qa('[data-priority]').forEach(n=>{const k=n.dataset.priority,full=(rules.has('distance')&&['ally','enemy'].includes(k))||(rules.has('threat')&&['enemy','boss','cast'].includes(k))||(rules.has('party')&&k==='ally');n.classList.toggle('is-full',full);n.classList.toggle('is-summary',!full)});const n=qa('.priority-entity.is-full').length;say(`FULL ${n}명 · SUMMARY ${6-n}명`,'중요도 변화가 생기면 다음 replication budget부터 단계가 바뀝니다.')}
function cells(){return Array.from({length:32},(_,i)=>`<div class="aoe-cell" data-cell="${i}">${Array.from({length:(i*7)%4},(_,j)=>`<i style="--x:${15+j*21}%;--y:${25+(i+j)%3*22}%"></i>`).join('')}</div>`).join('')}
function m73(){return `<section class="concept-demo">${H('Q73 · spatial broad phase','광역기마다 모든 캐릭터와 충돌 검사할까?','격자 후보 수집과 실제 원형 판정을 분리해 검사량이 어떻게 줄어드는지 실행하세요.')}<div class="mm-arena"><div class="aoe-grid">${cells()}</div><div class="aoe-metrics"><span data-aoe-broad>전체 후보 48</span><span data-aoe-narrow>정밀 검사 48</span></div></div><div class="concept-controls"><button data-scale-action="naive">전수 검사</button><button class="primary" data-scale-action="spatial">격자 broad phase</button><button data-scale-action="reset">초기화</button></div>${S('AOE 요청 대기','먼저 겹치는 cell만 찾고 그 후보에만 정확한 피해 판정을 수행합니다.')}</section>`}
function aoe(spatial){qa('.aoe-cell').forEach((n,i)=>{n.classList.toggle('is-query',spatial&&[10,11,18,19].includes(i));n.classList.toggle('is-hit',[11,18].includes(i))});tx('[data-aoe-broad]',spatial?'격자 후보 13':'전체 후보 48');tx('[data-aoe-narrow]',spatial?'정밀 검사 6':'정밀 검사 48');say(spatial?'검사량 축소 · 결과 동일':'전수 검사','broad phase는 정답을 바꾸지 않고 비싼 narrow phase 후보만 줄입니다.')}
function m74(){return `<section class="concept-demo">${H('Q74 · 서버 시간 패턴','각 클라이언트 타이머가 보스 패턴을 시작하면 왜 갈라질까?','클라이언트 clock drift를 바꾼 뒤 서버 event time으로 재정렬하세요.')}<div class="mm-arena"><div class="boss-clock"><div class="boss-axis"></div><i class="boss-event" style="--x:58%"></i><div class="client-cursor" data-clock="A" style="--x:48%;--y:30%">A · 9.8s</div><div class="client-cursor" data-clock="B" style="--x:64%;--y:68%">B · 10.4s</div><div class="client-cursor" data-clock="C" style="--x:54%;--y:84%">C · 10.1s</div></div></div><div class="concept-controls"><label>추가 drift <input type="range" min="-400" max="400" step="50" value="0" data-drift><output data-drift-v>0ms</output></label><button class="primary" data-scale-action="sync">server event 10.0s 동기화</button></div>${S('로컬 타이머 분산','패턴 ID와 authoritative start tick을 보내 각 클라이언트가 자신의 clock offset으로 표시합니다.')}</section>`}
function drift74(v){tx('[data-drift-v]',`${v}ms`);const base=[48,64,54];qa('[data-clock]').forEach((n,i)=>{n.style.setProperty('--x',`${base[i]+(+v/100)*(i-1)}%`);n.classList.remove('is-synced')});say('로컬 drift 적용','같은 duration을 재도 서로 다른 프레임에서 패턴이 시작됩니다.')}
function sync74(){qa('[data-clock]').forEach(n=>{n.style.setProperty('--x','58%');n.classList.add('is-synced')});say('authoritative tick 600 정렬','네트워크 도착 시각이 아니라 서버가 선언한 시작 tick을 공통 기준으로 사용합니다.')}
function m75(){return `<section class="concept-demo">${H('Q75 · boss intent 우선 채널','보스가 보는 방향을 늦게 알면 큰 패킷부터 보내야 할까?','타깃 의도, 실행 tick, 표현 데이터를 순서대로 보내 회피 가능 시간을 확보하세요.')}<div class="mm-arena"><div class="intent-stage"><div class="boss-avatar">BOSS<br><span data-boss-target>target ?</span></div><div class="intent-wire">→</div><div class="player-avatar">PLAYER B<br><span data-player-warning>경고 없음</span></div><div class="intent-signal"><div class="intent-step" data-intent-step="0">1. target ID</div><div class="intent-step" data-intent-step="1">2. execute tick</div><div class="intent-step" data-intent-step="2">3. animation detail</div></div></div></div><div class="concept-controls"><button class="primary" data-scale-action="intent">다음 우선 신호</button><button data-scale-action="reset">초기화</button></div>${S('의도 미수신','게임플레이 의사결정에 필요한 작은 reliable event를 표현 데이터보다 먼저 보냅니다.')}</section>`}
function intent75(){active.phase=Math.min(3,active.phase+1);qa('[data-intent-step]').forEach((n,i)=>n.classList.toggle('is-on',i<active.phase));if(active.phase>=1)tx('[data-boss-target]','target PLAYER B');if(active.phase>=2)tx('[data-player-warning]','회피까지 850ms');if(active.phase>=3)q('[data-intent-step="2"]').classList.add('is-late');const msg=[['타깃 즉시 식별','작은 target intent로 먼저 회피 방향을 결정할 수 있습니다.'],['실행 tick 수신','clock offset을 적용해 남은 시간을 예측합니다.'],['표현 데이터 도착','애니메이션 세부는 늦어도 판정 정보는 이미 확보됐습니다.']][active.phase-1];say(msg[0],msg[1])}
const M={71:m71,72:m72,73:m73,74:m74,75:m75};
function open(id){close(false);document.dispatchEvent(new CustomEvent('interview-demo-open',{detail:{id}}));active={id,phase:0};const h=document.querySelector(`[data-flow-host="${id}"]`),b=document.querySelector(`[data-flow-open="${id}"]`);if(b){b.hidden=true;b.setAttribute('aria-expanded','true')}h.innerHTML=M[id]();if(id===71)load71();if(id===72)priority72()}
function reset(){const id=active.id;active={id,phase:0};host().innerHTML=M[id]();if(id===71)load71();if(id===72)priority72()}
function close(f=true){if(!active)return;const id=active.id,h=document.querySelector(`[data-flow-host="${id}"]`),b=document.querySelector(`[data-flow-open="${id}"]`);if(h)h.innerHTML='';if(b){b.hidden=false;b.setAttribute('aria-expanded','false');if(f)b.focus({preventScroll:true})}active=null}
function init(){document.addEventListener('click',e=>{const o=e.target.closest('[data-flow-open]');if(o){const id=+o.dataset.flowOpen;if(id>=71&&id<=75){open(id);return}}const b=e.target.closest('[data-scale-action]');if(!b||!active)return;const x=b.dataset.scaleAction;if(x==='close')close();if(x==='reset')reset();if(x==='naive')aoe(false);if(x==='spatial')aoe(true);if(x==='sync')sync74();if(x==='intent')intent75()});document.addEventListener('input',e=>{if(e.target.matches('[data-crowd],[data-effects],[data-detail]'))load71();if(e.target.matches('[data-priority-rule]'))priority72();if(e.target.matches('[data-drift]'))drift74(e.target.value)});document.addEventListener('interview-demo-open',e=>{if(active&&active.id!==e.detail.id)close(false)})}
window.ScaleCombat={init};
})();
