(function(){
'use strict';let active=null;
const H=(k,t,d)=>`<div class="concept-head"><div><span>${k}</span><h3>${t}</h3><p>${d}</p></div><button data-vs-action="close">닫기</button></div>`,S=(l,m)=>`<div class="concept-status" aria-live="polite"><b data-vs-label>${l}</b><span data-vs-message>${m}</span></div>`;
const host=()=>active?document.querySelector(`[data-flow-host="${active.id}"]`):null,q=s=>host()?.querySelector(s)||null,qa=s=>host()?[...host().querySelectorAll(s)]:[],tx=(s,v)=>{const n=q(s);if(n)n.textContent=v},say=(l,m)=>{tx('[data-vs-label]',l);tx('[data-vs-message]',m)};
function m101(){const nodes=[['CLIENT','private candidate'],['STUN','server reflexive'],['DIRECT','UDP path'],['TURN','relay fallback'],['SFU','voice media']];return `<section class="concept-demo">${H('Q101 · ICE 경로 선택','NAT 뒤 보이스가 안 되면 게임 서버 소켓으로 우회할까?','NAT 유형을 바꾸고 direct·STUN·TURN 후보 연결을 순서대로 검사하세요.')}<div class="concept-controls"><label>NAT 환경 <select data-nat><option value="open">Open / cone</option><option value="symmetric">Symmetric NAT</option><option value="udpblocked">UDP blocked</option></select></label></div><div class="mm-arena"><div class="ice-path">${nodes.map((x,i)=>`<div class="ice-node" data-ice="${i}"><b>${x[0]}</b>${x[1]}</div>`).join('')}</div></div><div class="concept-controls"><button class="primary" data-vs-action="ice">다음 ICE candidate</button><button data-vs-action="reset">초기화</button></div>${S('candidate 수집','보이스는 게임 상태와 분리된 실시간 미디어 plane에서 NAT 경로와 품질을 선택합니다.')}</section>`}
function ice101(){const nat=q('[data-nat]').value;active.phase=Math.min(4,active.phase+1);qa('[data-ice]').forEach((n,i)=>n.classList.toggle('is-tried',i<=active.phase));if(active.phase===2&&nat==='open'){q('[data-ice="2"]').classList.add('is-selected');say('direct UDP 선택','STUN으로 발견한 candidate pair의 지연과 연결성을 확인했습니다.');active.phase=4}else if(active.phase===2){q('[data-ice="2"]').classList.add('is-failed');say('direct 경로 실패','NAT mapping이 candidate pair를 허용하지 않아 relay 후보로 진행합니다.')}else if(active.phase>=3){q('[data-ice="3"]').classList.add('is-selected');q('[data-ice="4"]').classList.add('is-selected');say(nat==='udpblocked'?'TURN/TCP relay':'TURN/UDP relay','게임 패킷과 별개로 media relay 경로를 선택해 연결성을 확보했습니다.')}else say('candidate 검사 중','private→server reflexive→relay 순서로 가능한 pair를 검증합니다.')}
function m102(){const users=[['송신 A','good'],['송신 B','loss'],['송신 C','good']];return `<section class="concept-demo">${H('Q102 · 경로별 media 적응','한 사람의 회선 손실 때문에 팀 전체 codec을 낮춰야 할까?','B의 손실률과 per-path 적응을 바꿔 각 수신 경로의 bitrate·FEC를 비교하세요.')}<div class="concept-controls"><label>B packet loss <input type="range" min="0" max="35" value="18" data-voice-loss><output data-voice-loss-v>18%</output></label><label><input type="checkbox" checked data-voice-adapt> per-subscriber adaptation</label></div><div class="mm-arena"><div class="voice-matrix"><div class="voice-cell head">stream</div>${['A','B','C','D'].map(x=>`<div class="voice-cell head">recv ${x}</div>`).join('')}${users.map((u,r)=>`<div class="voice-cell head">${u[0]}</div>${[0,1,2,3].map(c=>`<div class="voice-cell" data-media="${r}-${c}">64kbps</div>`).join('')}`).join('')}</div></div>${S('경로별 feedback','송신자·수신자 pair의 loss·jitter·RTT에 따라 bitrate, redundancy, packetization을 다르게 적용합니다.')}</section>`}
function media102(){const loss=+q('[data-voice-loss]').value,adapt=q('[data-voice-adapt]').checked;tx('[data-voice-loss-v]',`${loss}%`);qa('[data-media]').forEach(n=>{const [r,c]=n.dataset.media.split('-').map(Number),bad=c===1||r===1;let value='64kbps',cls='is-high';if(loss>12&&(adapt?bad:true)){value=loss>25?'24kbps + FEC':'40kbps + FEC';cls=loss>25?'is-drop':'is-low'}n.className=`voice-cell ${cls}`;n.textContent=value});say(adapt?'나쁜 경로만 보호':'채널 전체 품질 하락',adapt?'B와 관련된 path에만 FEC·낮은 bitrate를 적용합니다.':'한 경로의 손실이 모든 송수신 pair 품질을 낮춥니다.')}
function m103(){return `<section class="concept-demo">${H('Q103 · 필요한 범위의 순서','길드 채팅과 파티 채팅을 하나의 전역 순서로 맞춰야 할까?','각 channel writer가 부여한 sequence로 늦게 도착한 메시지만 제자리 정렬하세요.')}<div class="mm-arena"><div class="order-streams"><div class="order-channel" data-channel="party"><h4>PARTY · writer P</h4><div class="order-msg">P#41 준비</div><div class="order-msg is-late" data-late>P#43 출발</div><div class="order-msg" data-missing>P#42 버프</div></div><div class="order-channel"><h4>GUILD · writer G</h4><div class="order-msg">G#801 모집</div><div class="order-msg">G#802 완료</div></div></div><div class="order-clock" data-order-note>arrival order · PARTY 41→43→42</div></div><div class="concept-controls"><button class="primary" data-vs-action="reorder">channel sequence 정렬</button></div>${S('채널별 순서 경계','같은 대화 흐름 안에서만 단일 writer sequence를 보장하고 무관한 채널의 전역 clock은 만들지 않습니다.')}</section>`}
function reorder103(){const ch=q('[data-channel="party"]'),late=q('[data-late]'),missing=q('[data-missing]');ch.insertBefore(missing,late);[late,missing].forEach(n=>n.classList.add('is-fixed'));tx('[data-order-note]','PARTY 41→42→43 · GUILD는 독립 순서');say('채널 내부 수렴','P sequence gap만 buffer해 정렬하고 G channel과의 상대 순서는 정의하지 않습니다.')}
function m104(){const routes=[['CHAT','message API'],['PARTY','invite API'],['VOICE','media token'],['MATCH','teammate fill']];return `<section class="concept-demo">${H('Q104 · 공통 contact policy','채팅에서만 차단하면 파티 초대와 보이스는 계속 와도 될까?','차단 revision을 발행하고 각 접촉 서비스의 정책 cache를 갱신해 보세요.')}<div class="mm-arena"><div class="block-graph">${routes.map((x,i)=>`<div class="block-route is-open" data-block-route="${i}"><b>${x[0]}</b>${x[1]}<br>ALLOW</div>`).join('')}</div><div class="policy-revision" data-policy-rev>policy rev 17 · no block</div></div><div class="concept-controls"><button data-vs-action="blockone">채팅만 로컬 차단</button><button class="primary" data-vs-action="blockall">서버 policy rev18 발행</button><button data-vs-action="reset">초기화</button></div>${S('접촉 경로 4개','차단 관계를 공통 정책 서비스가 소유하고 모든 발급·전송 경계에서 강제합니다.')}</section>`}
function blockOne104(){q('[data-block-route="0"]').className='block-route is-blocked';say('부분 차단 · 우회 가능','CHAT만 막혀 PARTY·VOICE·MATCH 경로로 접근이 남습니다.')}
function blockAll104(){qa('[data-block-route]').forEach(n=>n.className='block-route is-blocked');tx('[data-policy-rev]','policy rev 18 · A blocks B · all contact capabilities DENY');say('공통 정책 수렴','각 서비스가 rev18을 확인하고 신규 초대·voice token·message를 서버에서 거부합니다.')}
function m105(){const items=[['텍스트','신고 전후 20줄'],['음성','동의된 30초 clip'],['메타','account·channel'],['원본 로그','전체 세션']];return `<section class="concept-demo">${H('Q105 · 목적 제한 evidence vault','욕설 신고 때문에 모든 음성·채팅을 무기한 저장해도 될까?','증거 범위와 보존 기간을 바꿔 최소 목적 데이터만 보관·만료시키세요.')}<div class="concept-controls"><label>보존 기간 <input type="range" min="1" max="90" value="14" data-retention><output data-retention-v>14일</output></label><label><input type="checkbox" checked data-consent> voice 신고 동의</label></div><div class="mm-arena"><div class="evidence-vault">${items.map((x,i)=>`<div class="evidence-item" data-evidence="${i}"><b>${x[0]}</b>${x[1]}</div>`).join('')}</div><div class="evidence-policy" data-evidence-policy>scope 계산 중</div></div><div class="concept-controls"><button class="primary" data-vs-action="expire105">보존 기간 만료 실행</button></div>${S('목적·동의·수명','신고 처리에 필요한 최소 context만 암호화하고 역할 기반 접근과 자동 삭제를 적용합니다.')}</section>`}
function evidence105(){const days=+q('[data-retention]').value,consent=q('[data-consent]').checked;tx('[data-retention-v]',`${days}일`);qa('[data-evidence]').forEach((n,i)=>n.classList.toggle('is-kept',i===0||i===2||(i===1&&consent)));tx('[data-evidence-policy]',`case E-105 · ${consent?'text+voice clip+meta':'text+meta'} · TTL ${days}일 · full session 제외`)}
function expire105(){qa('.evidence-item.is-kept').forEach(n=>{n.classList.remove('is-kept');n.classList.add('is-expired')});tx('[data-evidence-policy]','TTL 만료 · evidence key 삭제 · audit tombstone만 보존');say('민감 증거 자동 만료','처리 목적이 끝난 원문은 복구 불가능하게 삭제하고 접근 이력만 남깁니다.')}
const M={101:m101,102:m102,103:m103,104:m104,105:m105};
function open(id){close(false);document.dispatchEvent(new CustomEvent('interview-demo-open',{detail:{id}}));active={id,phase:0};const h=document.querySelector(`[data-flow-host="${id}"]`),b=document.querySelector(`[data-flow-open="${id}"]`);if(b){b.hidden=true;b.setAttribute('aria-expanded','true')}h.innerHTML=M[id]();if(id===102)media102();if(id===105)evidence105()}
function reset(){const id=active.id;active={id,phase:0};host().innerHTML=M[id]();if(id===102)media102();if(id===105)evidence105()}
function close(f=true){if(!active)return;const id=active.id,h=document.querySelector(`[data-flow-host="${id}"]`),b=document.querySelector(`[data-flow-open="${id}"]`);if(h)h.innerHTML='';if(b){b.hidden=false;b.setAttribute('aria-expanded','false');if(f)b.focus({preventScroll:true})}active=null}
function init(){document.addEventListener('click',e=>{const o=e.target.closest('[data-flow-open]');if(o){const id=+o.dataset.flowOpen;if(id>=101&&id<=105){open(id);return}}const b=e.target.closest('[data-vs-action]');if(!b||!active)return;const x=b.dataset.vsAction;if(x==='close')close();if(x==='reset')reset();if(x==='ice')ice101();if(x==='reorder')reorder103();if(x==='blockone')blockOne104();if(x==='blockall')blockAll104();if(x==='expire105')expire105()});document.addEventListener('input',e=>{if(e.target.matches('[data-voice-loss],[data-voice-adapt]'))media102();if(e.target.matches('[data-retention],[data-consent]'))evidence105()});document.addEventListener('change',e=>{if(e.target.matches('[data-nat]')){active.phase=0;qa('[data-ice]').forEach(n=>n.className='ice-node')}});document.addEventListener('interview-demo-open',e=>{if(active&&active.id!==e.detail.id)close(false)})}
window.VoiceSocial={init};
})();
